docs/config.md
sample_configs/bottom.toml
src/canvas.rs
src/canvas/canvas_colours.rs
src/canvas/canvas_colours/colour_utils.rs
src/main.rs

This is in comparison to previous behaviour where it just took the first CPU colour possible.
Also adds average cpu colouring options in config files.

Separate avg cpu colour from the other colours.

---

src/app.rs

Skips control characters that might be passed in (ie: caps lock to search).  We would want to ignore this case.
Issue: #14 
Remove the irrelevant one.
Provide any other relevant information.

Skip control characters if they are somehow passed in as a char

---

src/main.rs

Fixes a problem in windows where the shift key + char is considered a different switch statement tier.  It was therefore missing an overall `on_char_key()` call for anything w/ a shift modifier.
EDIT: Also fixes the alt-key behaviour on powershell.
Issue: #26
Remove the irrelevant one.
Provide any other relevant information.

Fix for issue in powershell.

---

.travis.yml
README.md
src/app.rs
src/canvas.rs
src/constants.rs
src/main.rs

Added different colours to search options if selected; added F1-3 keys as an alternative for searching.  Both are available, but on macOS F1-3 will be suggested instead.
Two main things:
* Add colours if search options are toggled on (and no colour if off)
* Add F1, F2, and F3 as case, whole word, and regex options as alternatives.  Both the original bindings work if available, but on macOS, F1-F3 will be suggested rather than their Alt counterparts.
Finally a documentation fix in README and ? menu where ``Alt-W`` was labelled incorrectly.
Issue: #29 
- Tested …

Colours if selected and F1-3 keys for search options

---

src/canvas.rs

Fix as per https://old.reddit.com/r/kde/comments/6fxf5t/konsole_font_issue/
Fixes an issue with the arrow not being displayed properly on Konsole
Closes #35 
Tested on Konsole, Kitty, and Terminator on Arch Linux.

Add space after arrow due for Konsole

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/pull_request_template.md
Cargo.toml
README.md
src/app.rs
src/canvas.rs
src/canvas/drawing_utils.rs
src/main.rs

Fixes unicode characters in search causing a crash.
Closes: #33 
Tested on Arch Linux, Kitty.  Used a variety of unicode characters, CJK, and normal ASCII, and tested backspace, delete, cursor movement, and adding characters.
Tested on macOS Catalina on Terminal.  See above.
Commit also contains some irrelevant commits to change some github file formats and README.

Fix unicode

---

src/canvas.rs
src/canvas/canvas_colours.rs
src/canvas/canvas_colours/colour_utils.rs
src/main.rs

Adds colouring options to config files + colours by default for total rx and tx.
Closes: #17 
Tested on macOS Catalina and Arch Linux on Terminal and Kitty respectively.

Colouring of rx tx

---

src/canvas.rs

Switches the character we used for arrows from ⯆⯅ to ▼▲
Seems like the old one caused rendering issues for macOS.
Closes: #45
Potentially #42 
Tested whether the arrow shows on Konsole, Terminator, and Kitty on Arch Linux.
Tested on macOS Catalina with Terminal and Kitty.

Switch to another arrow.

---

Cargo.toml

Switch to "fat" for lto and change codegen units to 1.  May revert.
This should improve binary size (and potentially performance) a bit.
Closes: #
Builds.

Cargo optimization

---

src/canvas.rs

Fixes an overlapping issue on basic bars.
Closes: #66 
Checked to work on small windows on macOS and Arch Linux.

Fix basic bars overlapping

---

README.md
src/app.rs
src/app/data_farmer.rs
src/canvas.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/mem_graph.rs
src/canvas/widgets/network_graph.rs
src/constants.rs
src/data_conversion.rs
src/main.rs
src/options.rs
tests/arg_rate_tests.rs
tests/arg_tests.rs

Adds time scaling to bottom.  This allows a user to use the mouse wheel and/or the `+/-` keys to zoom in and out based on time scale (currently capped to [300, 30] in terms of time limits).
The `=` button resets the scaling too.
Closes: #20 
Linux: Tested on Arch Linux with Kitty by allowing it to stack 10 minutes, allowing it to freeze and scrolling, and scrolling in general.
Windows: Tested on Powershell.
macOS: Tested on Kitty.
_Provide any other …

Time scaling

---

src/canvas.rs

Fixes resizing breaking scrolling, caused by forgetting to set the height/width fields upon the first detection of a resize
Closes: #80 
Tested on Arch Linux to fix the issue.

Fix resizing breaking scrolling

---

src/app/data_harvester.rs
src/app/data_harvester/cpu.rs
src/canvas/widgets/cpu_graph.rs
src/data_conversion.rs
src/main.rs

Fixes cpu legend colouring when hidden due to using the incorrect index, as well as merges two separate iterations together.
Closes: #79 
Tested to fix the problem on Arch Linux with no performance or feature regressions.

Fix cpu legend colouring

---

src/app/data_farmer.rs

The total memory values may be zero when bottom is run on an unsupported
(or not-fully-supported) platform.
The previous behavior resulted in a NaN value for the memory datapoints,
which was passed through to tui-rs which ultimately panicked when
attempting to graph the memory widget.
_Closes:_ #

Fix division by zero when memory data is not available

---

CHANGELOG.md
src/main.rs

Fixes the process sort by name not being case insensitive.
Closes: #109

bug: Fix sorting processes by name being case-sensitive

---

CHANGELOG.md
src/app/data_harvester.rs
src/app/data_harvester/processes.rs
src/canvas/widgets/process_table.rs
src/data_conversion.rs
src/main.rs

Adds process state.  Note this is not 100% finished but will end up getting changed in the future anyways.  Main issue is tabbed (combine by PID) mode - I'm thinking of something like:
```
U:2/S:2
```
for example, rather than the current`UUSS`.  But that's for later when I go and prettify everything.
Also fixes bug caused by #113 where process harvesting would fail for some processes due to I/O permission errors.
Closes: #
_Provide any other relevant …

feature: Show process state

---

CHANGELOG.md
README.md
src/app.rs
src/canvas.rs
src/canvas/dialogs/help_dialog.rs
src/canvas/drawing_utils.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temp_table.rs
src/constants.rs
src/main.rs

Adds scrolling to the help menu to make it easier to add to and not have to deal with text overflowing.
Closes: #

change: add scrolling to help menu

---

src/app.rs

Add `hjkl` as navigation keys in kill dialog.
Closes #133
The dialog

Kill dialog: vim navigation

---

.travis.yml
tests/arg_tests.rs
tests/invalid_config_tests.rs

MSRV testing for Travis breaks for `cargo test` since it uses a 1.43.0 version feature, but otherwise builds fine... so I'll just skip it.
Also, update travis a bit to deal with some warnings I was getting.
Closes: #

chore: update travis a bit for msrv

---

CHANGELOG.md
README.md
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/mem_graph.rs
src/canvas/widgets/network_graph.rs

Automatically hides the time labels on the X axis if the graph draw height is too small.
Closes: #
Run through on a variety of small and large console sizes.  Kitty was used.

Autohide time on small

---

CHANGELOG.md
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/mem_graph.rs
src/canvas/widgets/network_graph.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temp_table.rs
src/constants.rs

Hide the table gap (if there is one) if the widget height is too small.
A bit of a followup to #149.
Closes: #

change: hide table gap if widget height is small

---

src/app/data_farmer.rs

Fixes the disk widget not showing anything on macOS.
Closes: #151 

Macos disk fix

---

src/app.rs
src/app/states.rs
src/canvas/canvas_colours.rs
src/canvas/canvas_colours/colour_utils.rs
src/canvas/drawing_utils.rs
src/canvas/widgets/basic_table_arrows.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/cpu_basic.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/mem_basic.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temp_table.rs
src/constants.rs
src/main.rs

Minor refactor change, removes a lot of `as usize` conversions and just makes some types natively usize.
Closes: #
Seems to still work as before.  No regressions AFAIK.

refactor: reduce unchecked type conversions to usize

---

CHANGELOG.md
README.md
src/canvas/widgets/process_table.rs
src/data_conversion.rs

Adds process state back to the process widget.
Closes: #160  

feature: add back states to unmerged processes

---

CHANGELOG.md
src/app/query.rs
src/app/states.rs

Fixes `or` being read as a prefix rather than a keyword.
Furthermore, updated how we process various query parts to make it work a bit better.  Key points are:
- AND using spaces is way less... weird.  Especially within a bracket.
- Updated some error messages to be more descriptive.
- Better catch some errors - some of them would just fall through to the most general error message.
- Made things like `()` an error.
Closes: #165 
Tested queries:
`discord`
`(discord)`
`(discord) …

bug: fix or statement in queries

---

README.md

If you run `yay` without `-S` it'll perform a search instead of a direct match.

Prefer explicit yay installation command

---

CHANGELOG.md
src/app/data_harvester/processes.rs
src/canvas/widgets/process_table.rs

Fixes a bug caused by incorrectly reading the `/proc/{pid}/stats` file.  Due to splitting by whitespace, the string parsing was read incorrectly if the process also contained spaces.
Closes: #

Fix bug w/ parsing  file

---

src/app.rs
src/app/layout_manager.rs
src/app/query.rs
src/canvas/drawing_utils.rs
src/lib.rs

Fixes searching by command name being broken.
Closes: #

bug: fix searching by command being broken

---

CHANGELOG.md
src/app/layout_manager.rs

Fixes a bug where you could move down in a process widget even if search was disabled while in basic mode.
Closes: #210

bug: fix bug where you could move down in basic proc when search was disabled

---

src/app.rs
src/canvas/widgets/battery_display.rs

Allows `Ctrl-F` and `/` to work in the sort widget.
Closes: #

feature: Allow Ctrl-F and / to work in sort

---

.cargo/config.toml
.travis.yml
.vscode/settings.json
Cargo.toml
README.md
build.rs
deployment/linux/arch/PKGBUILD.template
deployment/linux/arch/PKGBUILD_BIN.template
deployment/macos/homebrew/bottom.rb.template
src/bin/main.rs
src/clap.rs
src/lib.rs

Adds shell completion generation as part of the build, as well as tweaking install scripts/templates/CI to use them.
Many of the changes are unashamedly based on ripgrep's setup.  For future reference:
- [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/ripgrep/trunk/PKGBUILD)
- [build.rs file](https://github.com/BurntSushi/ripgrep/blob/master/build.rs)
- [Documentation/install method for completion](https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#complete)
Closes: #140 
_Furthermore, please tick which platforms …

other: Add autocomplete file generation

---

CHANGELOG.md
src/app/data_harvester/temperature.rs
src/data_conversion.rs

Update temperature sensors in Linux to use labels + names rather than just names.
Note that this change does cause some of the names to be rather large... for example, the sensor known before as `edge` is now `amdgpu: edge`.  I plan to address this later since I want to rewrite how column widths are done.
Closes: #

bug: Use correct labels for sensors in Linux

---

.vscode/settings.json
src/app.rs
src/canvas/widgets/network_graph.rs

Fixes a bug where you could click on a widget when dd's dialog was open.
Closes: #

bug: fix being able to click widgets when dd-dialog was open

---

CHANGELOG.md
src/app.rs
src/lib.rs

Fixes sorting by count being available, but doing nothing.  This fix makes it sortable.
Closes: #

fix: Fixes count being sortable, but nothing occuring

---

CHANGELOG.md
Cargo.toml
src/bin/main.rs
src/canvas.rs
src/canvas/widgets/network_graph.rs

Fix for an index out-of-bounds by resizing to a smaller terminal _just_ after the program got the terminal size, but right before the terminal started drawing.
Based off of https://github.com/fdehau/tui-rs/issues/343.  
Closes: #237 

bug: Fix for index oob caused by terminal size mismatch

---

src/app/data_harvester/processes.rs
src/bin/main.rs
src/clap.rs
src/lib.rs
src/utils/logging.rs

Uses a less hard-coded method of writing to /tmp/.  Mainly because that doesn't work for Windows.
Closes: #

other: Use tmp_dir rather than /tmp/ for debug flag

---

CHANGELOG.md
src/app/data_harvester.rs
src/app/data_harvester/processes.rs
src/bin/main.rs
src/lib.rs
src/options.rs

Change inspired by https://github.com/heim-rs/heim/issues/154.  This was the cause of some process names getting cut off and looking weird for Linux (and Linux only, I'm not directly responsible for the other OSes).
This also adds spaces in between command line flags.  Before, they were usually separated by either spaces (which looked fine) or null terminators (which meant it looked like something was broken).
Before on left, after on right.
Closes: #
_If relevant, all of these …

bug: use cmdline for Linux proc name if >=15 chars

---

CHANGELOG.md
src/canvas/dialogs/dd_dialog.rs
src/canvas/dialogs/help_dialog.rs

Fixes styling for dialog titles.  Cherry picked from commit 06573becfa3c089ac4b2a17c9443f84b6a5af3e8.
Closes: #

bug: Fix widget highlighting styling for dialogs

---

src/canvas.rs
src/canvas/dialogs/dd_dialog.rs
src/canvas/screens/config_screen.rs
src/canvas/widgets/basic_table_arrows.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/cpu_basic.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/mem_basic.rs
src/canvas/widgets/network_basic.rs
src/canvas/widgets/network_graph.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temp_table.rs
src/lib.rs

Minor refactor to remove redundant `as_ref()` calls.
Closes: #

refactor: Remove redundant `as_ref()` calls

---

CHANGELOG.md
src/app.rs
src/canvas.rs
src/canvas/screens/config_screen.rs

Adds a simple indicator to help users know when they've frozen data updating using `f`.  For example:
Closes: #
- Tested on Linux for basic, expanded, and normal modes, where it *should* show up.
- It should *not* show up for the dd and help dialogs.

feature: Add simple indicator for when data updating is frozen

---

Cargo.lock
Cargo.toml

Updates dependencies that depend on uom (battery and heim), due to requiring 0.30 for the newest nightly version of Rust.
Closes: #271
Closes: #280

deps: Bump dependencies that require uom <0.29.0

---

src/canvas/widgets/basic_table_arrows.rs

Removes some `unwrap_or_else` calls when `unwrap_or` would suffice that were caught by clippy nightly.
Closes: #

clippy: fix unwrap_or_else usage

---

src/canvas/widgets/cpu_graph.rs

Fixes an incorrect offset affecting the CPU colour when scrolling.
Closes: #

bug: fix incorrect CPU colour offset

---

CHANGELOG.md
src/canvas/widgets/cpu_basic.rs

Fixes the CPU basic widget showing incorrect data due to an incorrect offset when displaying the data.
Closes: #288

bug: fix incorrect offset for cpu list in cpu basic widget

---

CHANGELOG.md
src/app.rs
src/canvas/widgets/cpu_basic.rs

Fixes a bug with CPU spacing on basic mode.
Before:
After:
Closes: #

bug: fix incorrect basic cpu spacing

---

src/canvas/widgets/cpu_basic.rs
src/data_conversion.rs

Gives better and less jank responsiveness when resizing the window in narrow sizes for the cpu basic widget.
Closes: #

refactor: Better responsiveness when resizing cpu basic widget

---

.vscode/settings.json
CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/bin/main.rs
src/canvas.rs
src/canvas/canvas_colours.rs
src/canvas/canvas_colours/colour_utils.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/process_table.rs
src/clap.rs
src/constants.rs
src/options.rs
tests/invalid_config_tests.rs
tests/invalid_configs/empty_battery.toml

Adds some default colour choices to choose from.
Default:
Gruvbox:
Default-light:
Gruvbox-light:
Closes: #240 

feature: default colour schemes

---

CHANGELOG.md
src/canvas.rs
src/canvas/canvas_colours.rs
src/canvas/canvas_colours/colour_utils.rs
src/canvas/widgets/cpu_graph.rs
src/constants.rs

Removes the random automatically generated colours for the CPU metrics.  This was not supported in all terminal emulators, and would cause some of them to break (namely macOS Terminal).
Instead we'll default to colours we can be more certain will work and loop through them as required.  Users can still override these colours with their own.
Closes: #307 
_Provide any other …

bug: remove buggy auto-generated CPU colour implementation

---

CHANGELOG.md
README.md
src/app.rs
src/app/states.rs
src/clap.rs
src/constants.rs
src/lib.rs
src/options.rs

Adds a new flag, `--mem_as_value` (and its corresponding config option, `mem_as_value = true`), which defaults to showing process memory values by their amount rather than percentage.
Closes: #295 

feature: Add mem_as_value flag

---

CHANGELOG.md
README.md
src/app/states.rs
src/canvas/screens/config_screen.rs
src/clap.rs
src/constants.rs
src/options.rs

Adds a `--tree` flag that defaults to tree mode for the process widget.
Closes: #

feature: add tree flag

---

src/options.rs

Fixes inverted behaviour of the `hide_avg_cpu` config entry.
Closes: #325 

bug: Fix inverted hide_avg_cpu option in config

---

CHANGELOG.md
src/canvas/canvas_colours.rs
src/canvas/widgets/battery_display.rs

Fixes colour theming for batteries being flipped.
Closes: #330

bug: Fix inverted battery colours

---

.github/workflows/deployment.yml

Previously it was CURL-ing from a non-existent URL, giving the wrong SHA hashes.
Changed to upload the binaries as artifacts and using those directly.

ci: Fix post-deploy step to actually use the correct files

---

.github/workflows/deployment.yml
CHANGELOG.md
README.md
src/app.rs
src/app/layout_manager.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temp_table.rs
src/clap.rs
src/options.rs

Adds the option to enable an "out of" indicator for scrollable table widgets (using `--show_table_scroll_position`).
For example:
Closes: #

feature: Add scroll indicator to keep track of table position in widgets.

---

CHANGELOG.md
src/canvas/widgets/cpu_graph.rs

Turns out there was yet another bug with the CPU colour allocation.  I had forgotten to use the same index calculation for the "all" position.
Closes: #

bug: Fix incorrect cpu colour matching again in all position

---

Cargo.lock
Cargo.toml
src/app/data_harvester.rs
src/app/data_harvester/disks.rs
src/app/data_harvester/network.rs
src/app/data_harvester/temperature.rs

Update to heim 0.1.
Closes: #341 

deps: Update to heim 0.1

---

.github/ISSUE_TEMPLATE/bug_report.md
Cargo.lock
Cargo.toml
README.md
src/app/data_harvester.rs
src/app/data_harvester/cpu.rs

Refactors to use only heim for Linux builds.  This is now much easier to do since the 0.1 version of heim works fine for ARM.  This is ideal since having to rely on two separate sources of data isn't the greatest if we can avoid it.
Sysinfo is still required for macOS and Windows, though.  Temperature sensors do not work for those from heim, and for some reason, networks also don't work on Windows with heim...?
My personal CPU core calculation is also currently Linux-only, and as such, I'll still rely on sysinfo for Windows and macOS for now.
This isn't really a big optimization or anything btw.  Just something I wanted to try.
_If applicable, what issue does this …

refactor: Cut out sysinfo from Linux builds

---

src/app/data_farmer.rs
src/app/data_harvester/mem.rs
src/bin/main.rs
src/canvas.rs
src/canvas/widgets/mem_basic.rs
src/canvas/widgets/mem_graph.rs
src/data_conversion.rs

Firstly, note this currently won't affect basic mode.  There is code changes due to it, but instead, we'll just display `0B/0B` instead.  I'm personally not really sure if we want to get rid of it in basic mode, since it'll leave an ugly gap in that mode.
Anyways, this change is mainly for the normal mode.  All this does is hide the legend entry and chart if the total SWAP drops to 0 KB. It also has a small change to do a unit check on the memory used, as well as slightly adjusting the calculation we use.
Closes: #370 
_Furthermore, please tick …

feature: Hide SWAP graph and legend in normal mode if SWAP is 0

---

src/canvas/widgets/cpu_basic.rs

Fixes the colour order being off in basic mode, and not using the average CPU colour.
Side by side comparison (first is new, second is old):
Closes: #

bug: Fixes incorrect colours being used the CPU widget in basic mode

---

.cargo/config.toml

Comment out some linkers set in `.config/cargo.toml` for ARM targets.
Closes: #

other: Comment out cross ARM targets

---

CHANGELOG.md
README.md
sample_configs/demo_config.toml
src/app/states.rs
src/clap.rs
src/constants.rs
src/options.rs

Adds a `process_command` flag and config option to default to showing the full command in the process widget on startup.
Closes: #305

feature: Add process_command to default to the process command

---

src/canvas/widgets/battery_display.rs

Fixes the `hide_table_gap` option not working with the battery widget.
Example now:
`cargo r -- --battery`:
`cargo r -- --battery --hide_table_gap`
Closes: #385

bug: Fix hide table gap option not working in battery widget

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/app.rs

Fixes a bug where you could make the sorting arrow disappear in the mem column if you did:
1. Go to proc widget
2. Switch to memory values from %
3. Press `m`
Closes: #

bug: Fix missing sorting arrow when for non-% mem

---

src/data_conversion.rs

Shows temperatures in Celsius/Fahrenheit with a degree symbol. (Kelvin is absolute, so it doesn't use a degree symbol.)
N/A
Closes: #
Built and run.
N/A

Show Celcius/Fahrenheit with degree symbol

---

src/app/data_harvester/processes.rs

When running without elevated permissions under macOS, sysinfo cannot
query states of processes by root user, which results in 0.0% CPU usage
for all this kind of processes (and state = Unknown).
Here we use `ps`, which has SUID, as a fallback to query CPU usages.
This can be potentially applied to other properties if needed in the
future (we'll need a proper struct and parser).
Closes: #380
I admit this is quite hacky and I'm not sure if it's worth the effort maintaining, but unfortunately users are not always able to run `btm` with elevated permissions and this has come quite helpful to myself.

feature: Use `ps` as fallback to query CPU usage under macOS (#380)

---

CHANGELOG.md
src/app/data_harvester/cpu.rs
src/canvas.rs
src/canvas/widgets/cpu_basic.rs

So it seems that tui-rs doesn't like rendering my CPU bars if the height is exactly 1.  It needs at least 2.  I have no idea why, this is probably something weird with how I render.
This, of course, breaks when there is only one row to report (i.e. with a dual core setup in #397).
The workaround switches the gap between the CPU and mem/net parts to 0, and increases the CPU's draw height by 1, *only* when the height is otherwise 1 (so the draw height is now at least 2).  This does have the side effect of including an extra line to the side borders, but I think it's fine.
Before:
After:
Closes: #397
_Remove the irrelevant …

bug: Workaround for strange rendering when there are <4 CPU entries reported

---

Cargo.lock
Cargo.toml
README.md

Uptick to 0.5.7 to release a build with 4 bug fixes:
- [#373](https://github.com/ClementTsang/bottom/pull/373): Fixes incorrect colours being used the CPU widget in basic mode.
- [#386](https://github.com/ClementTsang/bottom/pull/386): Fixes `hide_table_gap` not working in the battery widget.
- [#389](https://github.com/ClementTsang/bottom/pull/389): Fixes the sorting arrow disappearing in proc widget under some cases.
- [#398](https://github.com/ClementTsang/bottom/pull/398): Fixes basic mode failing to report CPUs if there are less than 4 entries to report.
Closes: #
_If relevant, please …

uptick: 0.5.7

---

Cargo.lock
Cargo.toml

Fix for RUSTSEC-2020-0122, as per https://github.com/ClementTsang/bottom/issues/401.
Closes: #401

deps: Update beef as per RUSTSEC-2020-0122

---

CHANGELOG.md
README.md
src/app.rs
src/app/layout_manager.rs
src/app/process_killer.rs
src/app/query.rs
src/canvas.rs
src/clap.rs
src/constants.rs
tests/arg_tests.rs
tests/invalid_config_tests.rs

Adds colour schemes for [Nord](https://www.nordtheme.com/docs/colors-and-palettes), along with a light variant.
nord:
nord in basic mode:
nord-light:
nord-light in basic mode:
Issue: #403 

feature: add nord and nord-light colours

---

CHANGELOG.md
README.md
src/app.rs
src/canvas/widgets/process_table.rs
src/constants.rs
src/lib.rs

`Ctrl-w` deletes one word backwards from the current cursor location.  `Ctrl-h` is just an alias for backspace.
Closes: #270, also affects #407 

feature: Add ctrl-w and ctrl-h support in the search

---

.vscode/settings.json
CHANGELOG.md
README.md
src/app.rs
src/app/states.rs
src/canvas.rs
src/canvas/widgets/process_table.rs
src/constants.rs

Adds mouse support for sorting columns within the process widget.  You can now click on the column header to sort (or invert the sort).
https://user-images.githubusercontent.com/34804052/108419041-071f7280-7200-11eb-9d5e-3559495c1154.mp4
Closes: #395 

feature: Add mouse support to sorting columns

---

CHANGELOG.md
src/canvas/widgets/process_table.rs

Fixes grouped mode having different spacing than non-grouped mode.
Video below compares the fixed version (first one) to the release version (0.5.7):
https://user-images.githubusercontent.com/34804052/108430548-88323600-720f-11eb-8367-a194a220d7ad.mp4
Closes: #415 

bug: fix inconsistent spacing with grouped vs non-grouped in the process widget

---

CHANGELOG.md
src/app.rs
src/app/states.rs

Fixes sorting menus and shortcuts not syncing correctly if the sorting window is open.
Closes: #414 

bug: Fix sorting menu and sort shortcuts desync if menu is open

---

CHANGELOG.md
src/app.rs

For consistency, we now don't automatically jump to the top of the list when using a sort shortcut.  This behaviour already occurred with the sort menu and sorting by mouse clicks, so this is just now more consistent (and IMO less annoying, you can also always jump to the top via `gg`).
Closes: #

change: Don't jump to top when using sort shortcuts

---

.vscode/settings.json
CHANGELOG.md
src/app/data_harvester.rs
src/app/data_harvester/disks.rs
src/data_conversion.rs

Two issues were highlighted as a result of using either Void Linux with disk encryption, or just disk encryption on Linux in general:
Two fixes:
1. Fixes a failed `usage()` call in the `get_disk_usage` function from failing the entire result.  Now it only returns an entry with N/A results.  This occurred in some distros and disk encryption setups, for example, [the one for Void Linux](https://docs.voidlinux.org/installation/guides/fde.html).
2. Fixes a potential mapping issue with disk encryption on Linux in general.  Since the disk might map to `/dev/mapper/whatever`, but the I/O harvester was using another name, the mappings would not match.  As such, we now also …

bug: Fix bugs with disk widget and disk encryption

---

src/app/data_farmer.rs
src/app/data_harvester.rs
src/app/data_harvester/load_avg.rs
src/app/data_harvester/loadavg.rs
src/bin/main.rs
src/canvas.rs
src/canvas/widgets/cpu_graph.rs
src/lib.rs

Add support for showing load average (as part of the CPU display).
Addresses one part of what is mentioned in #235. Please comment on how display is done.
Tested by running on Linux.

Add support for displaying load average

---

src/app/data_harvester/processes.rs

Fixes a rare segfault if a uid does not have a passwd entry. The unsafe block [here](https://github.com/ClementTsang/bottom/blob/master/src/app/data_harvester/processes.rs#L137) can return a null pointer as specified [here](https://www.gnu.org/software/libc/manual/html_node/Lookup-User.html). 
Closes: #
_Provide any other relevant information to …

Fix getpwuid segfault

---

CHANGELOG.md
src/data_conversion.rs

In particular, use non-binary prefixes for disk and memory usage in a process.  Ideally everything is configurable by the user, but this is fine for now IMO until I can get around to doing in-app config.
Closes: #

change: Make proc widget unit consistent with disk

---

CHANGELOG.md
src/data_conversion.rs
src/lib.rs

~~This change adds a decimal + single digit to memory usage in the process widget.  Note that this only affects all cases where the value is less than 0.05, so we don't have `0.0B` displayed.  Otherwise, it's a fairly straightforward change.~~
This change adds a decimal + single digit to memory usage values over the 1 GiB threshold.  Otherwise, there is no visible change.
(Note to self: implement the per-column width system soon, this change causes some values to potentially look a bit weird in mem-non-percent mode as it is if the value is really large, like 530.2GiB pushing right up against the column width, but it's currently tied to …

change: Add decimal to actual memory usage in proc

---

CHANGELOG.md
src/app/data_farmer.rs
src/constants.rs
src/data_conversion.rs

A bit of a followup to #449, this adds decimal places for values over 1GB in regards to disk usage.  This affects the disk widget (for the read/write per second) and process widgets (total read, total write, read/write per second).
Closes: #

change: Add decimal to disk values larger than 1GB

---

CHANGELOG.md
src/canvas.rs
src/canvas/widgets/basic_table_arrows.rs
src/canvas/widgets/cpu_basic.rs
src/canvas/widgets/mem_basic.rs
src/canvas/widgets/network_basic.rs

Fixes basic mode having broken click hitboxes (they were 1 unit too long in both directions).  I'm pretty sure normal mode does too, but it's less noticeable due to bounding boxes.
Closes: #

bug: Fixes basic mode hitboxes being broken

---

CHANGELOG.md
src/app.rs
src/app/states.rs
src/canvas.rs
src/canvas/dialogs/dd_dialog.rs
src/canvas/widgets/basic_table_arrows.rs
src/canvas/widgets/cpu_basic.rs
src/canvas/widgets/mem_basic.rs
src/canvas/widgets/network_basic.rs

Fixes the mouse hitbox checks overextending by 1.  Also reverts the bandaid fix done for #458.
Closes: #

bug: Fix mouse hitboxes

---

src/app/data_harvester/cpu.rs
src/canvas.rs

Removes the gap between the CPU section and other columns in basic mode.
Before:
After:
Closes: #

change: remove gap between CPU and columns in basic

---

src/constants.rs
src/lib.rs

Adds `advanced_kill` to the default config gen.
Closes: #

other: adds advanced_kill to default config gen

---

README.md
src/clap.rs
src/constants.rs
src/options.rs

We make the advanced kill menu the default instead.  You can opt out with `disable_advanced_kill`.
Closes: #

other: make advanced kill default

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml

Removes `strip` from the Windows build in deploy/nightly.  It seems to cause VirusTotal to report some [false positives](https://www.virustotal.com/gui/file/97dbaa07d3934166bc1bb50ecea6d1bd9dcd96109a20d3ecc0dfe506e8442c6c/detection).
[Meanwhile](https://www.virustotal.com/gui/file/8c320c2594c882c2b89df95e52810e20e6b6a3c0e1b82c592f1b2310bc63f0f6/detection), without `strip`.
Also updates some small stuff in the script.
Closes: #
_If relevant, all of …

github: Remove strip from Windows deploy/nightly

---

CHANGELOG.md
src/data_conversion.rs

Adds a line to actually *build* the string of the summed memory usage.  I forgot to make the string after summing the values.
Before:
After:
Closes: #

bug: forgot to create memory usage string when collapsed

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml

Since we're moving all 16.04 ubuntu builds to 18.04, I thought this would be a good idea in case anyone needed it.
Not sure if we should have just made ALL Linux builds use the older Linux container... for now I'll just make one extra build.
Closes: #

github: add old Linux build to nightly/deploy for older glibc

---

README.md

The .config directory works on my Mac. It makes scripting setup with Ansible easier if more OSes use the same path.

docs: List macOS as also supporting XDG config directory

---

Cargo.lock
Cargo.toml
src/lib.rs

Since it's supported again, seems like a good time to switch back to dirs.
This change shouldn't do anything breaking, dirs-next 2 has the same (relevant) behaviour as dirs 3.
Closes: #

deps: Switch back from dirs-next to dirs

---

README.md

Bottom is available in the GURU project overlay so I added a note for that in the installation instructions for Gentoo.
Since [Gentoo wiki](https://wiki.gentoo.org/wiki/Project:GURU) refers to GURU as *an official repository of new Gentoo packages*, more people are likely to prioritise/prefer to enable GURU overlay over others so I think it's a nice idea to mention GURU in the docs.
Some people, such as me, like to use more *official* ways, than *personal* ones ([dm9pZCAq](https://github.com/gentoo-mirror/dm9pZCAq): *personal overlay with different packages*) hence I made this PR.

docs: mention GURU overlay in installation instructions

---

src/app/data_harvester/processes/linux.rs

Fixes a clippy warning regarding hashmap vacancy check and inserts.
Closes: #

refactor: Fix clippy lint for entry vacancy check

---

.github/workflows/ci.yml
docs/content/usage/widgets/process.md
src/app.rs
src/constants.rs
src/lib.rs

Adds `F9` as an alternative kill shortcut to `dd`.

feature: add F9 as an alternative process kill key

---

CHANGELOG.md
src/app/data_harvester/processes/macos.rs
src/app/data_harvester/processes/windows.rs

Fixes a bug displaying the CPU usage of a process in Windows due to not dividing by the number of processors.
Closes: #523

bug: Divide Windows process cpu usage by number of processors

---

tests/arg_tests.rs
tests/empty_config.toml

Fixes a bug where running `cargo test` would try to create a configuration file for the user.
Closes: #535
Walked through the steps to reproduce from #535. All tests now pass.
Tested on these platforms:
The following have been met:

bug: Tests try to modify user home directory

---

.github/workflows/ci.yml

Seems like we have a few too many tests that aren't really needed for just asserting CI is passing.
The goal for CI (IMO) is just to ensure things still build on the various supported platforms after changes are made.  However, there were a few tested scenarios like Windows GNU or musl which I feel weren't really too important in this regard, and added extra time to an already long CI process.
Commented out the following tests since there aren't any architecture-specific features that require running these in addition to other already-existing tests:
- Windows GNU
- Linux musl (both x86 and x86_64)
Of course, should we add changes that …

ci: reduce the number of tests in CI

---

docs/content/configuration/command-line-flags.md
docs/content/configuration/config-file/flags.md
src/clap.rs
src/constants.rs
src/options.rs

Adds the missing `hide_time` and `battery` config option to the default config and corresponding documentation.
Should probably automate the generation of this somehow tbh, though this might change when I add in-app config (soon™)
Closes: #541 

bug: Fix missing config options in docs and default config

---

CHANGELOG.md
src/app/data_harvester/memory/heim.rs
src/data_conversion.rs

Fixes the accuracy of the memory widget for Linux and macOS, and uses binary prefixes instead to be more accurate.
Regarding the first part, it turns out that the way I was calculating memory usage was *slightly* incorrect for a few reasons:
- Regarding macOS, it seems like the way I was determining usage (`usage = total - available`) is not the most accurate.  The better way of doing this is apparently `usage = wire + active`, where `wire` is memory always marked to stay in RAM, and `active` is memory currently in RAM.  This seems to be much closer to other applications now.
- Regarding Linux, this was somewhat due to two issues - one was …

bug: fix inaccuracy in memory usage/total on macOS and Linux

---

src/app/data_farmer.rs
src/app/data_harvester/memory/heim.rs
src/data_conversion.rs

Workaround for Linux heim memory units not being correct for swap.

bug: Fix swap calculation for Linux

---

CHANGELOG.md
docs/content/usage/widgets/memory.md
src/app/data_harvester/memory/general.rs
src/app/data_harvester/memory/mod.rs

Swap to manually calculating the mem total and usage via procfs.  The usage calculation is now:
```
total - (free + cached + buffers + slab_reclaimable - shmem)
```
This follows the same usage calculation as htop.  See the PR for more details.

bug: switch over to procfs for linux mem usage

---

Cargo.lock
Cargo.toml
docs/content/usage/widgets/memory.md
src/app/data_harvester/memory/general.rs

Manually parse `/proc/meminfo` for the purposes of memory usage.
Tested by observing the values and comparing to htop and the previous master build.

refactor: switch to manual implementation of meminfo parse

---

README.md

Update the documentation in regards to installation on Arch Linux.
`bottom` is now in the community repository. :)

docs: update reference to Arch Linux package

---

.github/workflows/ci.yml
.github/workflows/deployment.yml
.github/workflows/nightly.yml
Cargo.toml
docs/content/usage/widgets/battery.md
src/app/data_farmer.rs
src/app/data_harvester.rs
src/app/layout_manager.rs
src/bin/main.rs
src/clap.rs
src/data_conversion.rs

Allows disabling of the battery dependency through a feature flag.  This also aims to disable all related features.
Partially solves: #569 

other: Make the battery dependency/features optional

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Fixes a panic caused by the procfs library where it would crash for kernel patch versions > 255.
Closes: #574

bug: fix crashes for kernel patch versions > 255

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml

Adds an explicit `mkdir` to the completions directory. No idea why it was bugging out before though, it worked fine on nightly builds.
Closes: #
Tested with a test run: https://github.com/ClementTsang/bottom/actions/runs/1227180644

ci: fix deploy script for completion directory copy

---

README.md

Now that bottom is [in Homebrew](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/bottom.rb), people don't need to bother with the `brew cask` stuff anymore.
This doesn't address any preexisting issues.
This change was not tested.

README.md: bottom is in Homebrew proper now

---

tests/layout_management_tests.rs

test_default_battery_movement() is now feature gated on the
battery feature.
fixes #581
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>
See #581 - Gentoo now passes tests with and without the feature enabled.
Closes: #581
I ran the test suite with and without the feature enabled, both on Fedora 33 and Gentoo's ebuild environment.

Feature gate test_default_battery_movement

---

Cargo.lock

There are three commits in this PR. The first two address [RUSTSEC-2021-0003](https://rustsec.org/advisories/RUSTSEC-2021-0003) and [RUSTSEC-2021-0093](https://rustsec.org/advisories/RUSTSEC-2021-0093), and the third runs a general `cargo update` just to get on the latest compatible versions of all dependencies.
I ran `cargo test`, `cargo check`, and `cargo run` on Fedora 33 (x86_64).

RUSTSEC-2021-0003, RUSTSEC-2021-0093, and cargo update

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml
Cargo.toml

Moves debian and winget/msi generation to a separate job, so it can run in parallel to the other jobs.
Nightly test: https://github.com/ClementTsang/bottom/actions/runs/1267798598
Deploy test: https://github.com/ClementTsang/bottom/actions/runs/1267798112

ci: move winget/msi and deb gen to separate steps

---

docs/content/usage/widgets/process.md
src/constants.rs

Removes an incorrect shortcut. No idea when that got there.

bug: remove incorrect shortcut from docs/help

---

README.md

This is purely a documentation change to prominently feature the name of the binary. The formatting was adopted from the [ripgrep](https://github.com/BurntSushi/ripgrep) project, which also has a mismatch between the project and binary name, but any other placement of the binary name in the title or first few lines of the README would also be a good fix.
Currently the only mention of the binary name is in the `Usage` section, near the bottom of the README. A more prominent placement of the name of the binary is probably a good idea from a usability perspective.

Prominently display the binary name in the README.

---

.github/workflows/ci.yml

Reverts to using `paths_ignore` for CI workflow.

ci: go back to a paths_ignore for ci workflow

---

.github/workflows/ci.yml

Due to how matrices work with if/skipping, it seems like this ugly hack is the only way to skip CI based on the files updated without clogging the PR pipeline.

ci: deal with skipping and matrix

---

.github/workflows/ci.yml

This time, the problem is that since the matrix jobs rely on another job, they never trigger and clog up CI.

ci: deal with skipping, matrices, reliant jobs

---

src/app/states.rs
src/bin/main.rs
src/canvas.rs

Fixes the `process_command` flag/config not properly toggling off the `name` column and on the `command` column on initialization.  This would cause sorting of that column to bug out.
Closes: #626

bug: Fix process command flag breaking sorting

---

.github/workflows/docs.yml
.github/workflows/post-release.yml

Adds a CFP hook to deploy.  This is a workaround since we currently cannot disable non-production branch builds.

ci: adds cloudflare pages deploy hook

---

CHANGELOG.md
src/app/data_harvester/processes/linux.rs

Addresses a potential case where processing would fail if there were missing values from the CPU line of `/proc/stat`, and allows it to successfully return.
Closes: #636 

bug: Fix process CPU calculation if /proc/stat CPU line has less values than expected

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml
Cargo.toml

Fixes completion file generation being broken while the `.deb` file is made, due to using an incorrect path.
Closes: #644
Tested by running the nightly pipeline in mock, which will trigger the `.deb` file generation.
Action run: https://github.com/ClementTsang/bottom/actions/runs/1628351846

bug/ci: fix debian file generation breaking completions

---

CHANGELOG.md
docs/content/usage/general-usage.md
src/app.rs
src/canvas.rs
src/constants.rs
src/lib.rs

Adds page up/down scrolling support to respectively scroll up/down by a full page.
Note that this is mostly just to get the feature out for those interested, and is admittedly a bit rushed - I will be rewriting all logic involving event handling as part of state refactor anyways, so this will also get changed in the work done there, and therefore, I kinda just sped through this.
Closes: #620 …

feature: add basic page up/down scrolling

---

.github/workflows/post-release.yml

Adds an indicator in the form of `$version (stable)` to make it easier to see which is the most recent stable version.
This is done via CI and mike:
1. Set the previous title to just `$version`. We can get this value by `mike list stable` and grepping for valid version tags (otherwise this might have issues with `$version (stable)`).
2. Deploy `$new_version` and alias to stable.
3. Update the `$new_version` to have a new title of `$new_version (stable)`.
This is what it looks like:
Tested via manually executing the commands in the deploy script for …

docs: indicate stable version in selector on deploy

---

README.md

Centers the title and description in the README via some ugly HTML.

docs: center the title/description in the README

---

Cargo.toml
src/canvas.rs
src/canvas/drawing_utils.rs

Due to a missing check, you could resize the window to a width that was too small, and it would trigger an endless while-loop for any table while trying to redistribute remaining space. This has been rectified with an explicit check, as well as a smarter method of redistributing remaining space borrowed from the rewrite.
This also adds explicit width checks for widgets that have borders; if the width is <2, before, it would panic.
Note that the rewrite I have kinda fixes all these issues already, so I don't want to invest too hard into this, but this should be fine as a patch for now.
Also note that minimal heights don't seem to be causing …

bug: fix issues caused by having a width that is too small

---

src/app/data_harvester.rs

Without this now sysinfo `sys.processors().len()` returns 0, and makes a lot of CPU usages in process list `inf%`.
N/A

Refresh sysinfo CPU

---

.github/workflows/deployment.yml
deployment/windows/choco/choco_packager.py
deployment/windows/choco/chocolateyinstall.ps1.template

Seems like the 32-bit binary triggers false positives on VirusTotal. Going to disable this for now.

ci: disable 32-bit in choco generation

---

Cargo.lock
Cargo.toml
src/app/data_harvester/temperature/heim.rs
src/app/data_harvester/temperature/mod.rs
src/app/data_harvester/temperature/nvidia.rs
src/app/data_harvester/temperature/sysinfo.rs

I added the support for nvidia's GPUs temperature using the crate nvml-wrapper that load the nvml library only if it exists, so you can use it optionally even if the nvidia flag is setted. Interestingly on my test on my Windows machine no sensors are found except the nvidia's one. I tested it on Windows 10 with GeForce 1080, on the same machine with ArchLinux and on a Mid 2014 MacBook Pro 14" Retina. I let the tests run on Github Actions' CI and seems that nothing brokes.
Here some screenshots:
- Windows 10:
- ArchLinux:
- MacOS:

Add support for nvidia GPUs

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml
Cargo.toml

Removes the manual `strip` used in favour of the now native functionality in Cargo.
Closes: #

ci: enable strip on release builds with Cargo.toml

---

Cargo.lock
Cargo.toml

Updates the `dirs` dependency to 4.0.0. This is a breaking change but should not affect bottom.

deps: update dirs to 4.x

---

Cargo.lock
Cargo.toml
build.rs
src/clap.rs
src/options.rs
tests/arg_tests.rs

Updates bottom to use clap 3.x.x, along with some small refactoring changes.
Closes: #

deps: update clap to 3.x

---

Cargo.lock
Cargo.toml

Addresses [this CVE](https://blog.rust-lang.org/2022/03/08/cve-2022-24713.html) with the recommended fix of updating to 1.5.5.
Closes: #

deps: update regex to 1.5.5 due to CVE

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml
README.md

Adds `--locked` to the build process for nightly and deploy workflows.
Deploy: https://github.com/ClementTsang/bottom/actions/runs/2142876557
Nightly: https://github.com/ClementTsang/bottom/actions/runs/2142876145
Tested both workflows:

ci: use locked builds in deploy and nightly

---

.github/workflows/ci.yml
CHANGELOG.md
src/canvas.rs
src/canvas/dialogs/dd_dialog.rs

This changes various `as_ref()` calls as needed in order for bottom to successfully build in Rust beta 1.61, as they were causing type inference issues. These calls were either removed or changed to an alternative that does build (e.g. `as_slice()`).
Functionally, there should be no change.
Closes: #708 

bug: change as_ref() calls as needed to build in Rust beta 1.61.0

---

.github/workflows/coverage.yml

Experiment with [llvm-cov](https://github.com/taiki-e/cargo-llvm-cov) over tarpaulin.
Tarpaulin is supposed to be switching to something similar to how this works in the future as well, so I might switch back then if I switch now.

ci: try using llvm-cov instead of tarpaulin

---

.github/workflows/audit.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/deployment.yml
.github/workflows/nightly.yml
src/clap.rs
src/options.rs

Cleaned up and updated the primary GitHub CI workflow. Also fixes a bug caught during this check.
Tested by this PR, which should trigger the CI workflow.

ci: clean up CI workflow

---

.github/workflows/ci.yml

Moves the `rustfmt` step into the `supported` job, to avoid having to wait too long for machine spinup time if they are separate jobs.
This PR tests the CI flow.

ci: move cargo fmt step into supported job

---

Cargo.lock
Cargo.toml
src/app/data_harvester.rs
src/app/data_harvester/batteries/battery.rs

Migrates the `battery` dependency to the more actively maintained [`starship-battery` fork](https://github.com/starship/rust-battery). See https://github.com/svartalf/rust-battery/pull/92 for more information.
Partially addresses: #597 

deps: migrate to starship-battery

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml

Adds musl targets to the nightly and deployment workflows.
Closes: #725 
Tested on the following mock action runs:
- [nightly](https://github.com/ClementTsang/bottom/actions/runs/2287383286)
- [deployment](https://github.com/ClementTsang/bottom/actions/runs/2287383745)

deployment: add arm musl targets

---

.github/workflows/coverage.yml

Just adds back the paths field to the coverage workflow, since it really shouldn't be running if I, say, change documentation only.

ci: add back paths field to coverage workflow

---

src/canvas/components/time_graph.rs

This makes the graph legend the same color as the rest of the graph.

other: make the graph legend the same color as the graph

---

.github/workflows/ci.yml
README.md

Fixes typo leading to no aarch64 CI builds.

ci: fix missing aarch64 build

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml
Cargo.toml
Cross.toml
README.md
build.rs

Adds .deb generation for aarch64 and armv7 gnu targets in the nightly and deploy workflows.
Closes: #736 
The affected workflows were tested:
- [Deployment](https://github.com/ClementTsang/bottom/actions/runs/2402077115)
- [Nightly](https://github.com/ClementTsang/bottom/actions/runs/2402061049)
Also tested the armv7 and aarch64 .deb files was on my local Pis.

deployment: add aarch64/armv7 gnu .deb generation

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml

Deletes the generated debian folder in nightly/deploy workflows, as I don't want to cache it.
Tested on [Nightly](https://github.com/ClementTsang/bottom/actions/runs/2402242758).

deployment: deletes the debian folder in case of unwanted leftover files

---

Cargo.toml
src/app/data_harvester/batteries/battery.rs
src/canvas.rs
src/lib.rs

Enables lib docs, primarily intended for dev use. Also change some existing documentation based on warnings (mainly broken/bare links).
Tested locally to properly generate.

docs: re-enable lib docs for development purposes

---

docs/requirements.txt

Bumps mkdocs-material to [8.3.5](https://github.com/squidfunk/mkdocs-material/releases/tag/8.3.5).
Should pass CI.

docs: bump mkdocs-material to 8.3.5

---

.github/workflows/build_releases.yml

Locks cross in deployment builds to 0.2.1, as 0.2.2 seems to break some things for now.
First noted in [this scheduled nightly run](https://github.com/ClementTsang/bottom/actions/runs/2562433609). Some investigation seems to point to the current configuration ignoring env passthrough unless I specify for every single target.
[Manually running a nightly workflow should pass with these changes](https://github.com/ClementTsang/bottom/actions/runs/2562658767).

deployment: force usage of cross 0.2.1 for now

---

CHANGELOG.md
src/bin/main.rs
src/lib.rs

Adds a warning if the user is calling bottom from an environment where the output is not a terminal.

feature: add check for whether the output is to a terminal

---

src/lib.rs

Addition to #760, adds an extra message so users know how to exit in this scenario.
Should simply pass CI.

feature: add note on how to exit if running in non-terminal

---

docs/requirements.txt

The markdown Python lib seems to be causing some issues with certain extensions. Bumping mkdocs to 1.3.1 seems to resolve this issue (the alternative is pinning markdown to < 8.4.0).
For more info, see https://github.com/mkdocs/mkdocs/issues/2892

docs: bump mkdocs to fix markdown breaking exts

---

.github/workflows/build_releases.yml

Adds macOS ARM to the build workflow for nightly/release.
Related to #382 
Relevant workflows are to be run:

ci: add ARM macOS to build workflow

---

src/app.rs
src/app/states.rs
src/canvas/dialogs/help_dialog.rs
src/constants.rs
src/lib.rs

adds Ctrl-u/Ctrl-d for scrolling half a page
Closes: #765  

Feature: half page scrolling

---

src/app.rs
src/canvas/dialogs/help_dialog.rs

Tweaks `max_scroll_index` usage in the help menu to better reflect its name of being a max index, not a max index bound.
For example, before, the index could not be equal to or more than `max_scroll_index`, but the name would have implied that it should be less than or equal to it.
Closes: #
_If this is a code change, please also indicate which platforms were tested. All platforms directly affected by the change **must** be tested:_

refactor: change max_scroll_index usage to better reflect name

---

src/components/text_table/state.rs

Clamp scrolling to the top/bottom when trying to scroll past the top/bottom.
This makes the scrolling behaviour correspond more to how other applications handle scrolling.
~Closes: #~
_If relevant, please state how this was tested. All changes **must** be tested to work:_ 
adjusted the `test_scroll_update_position` test

Feature: clamp scrolling

---

Cargo.lock
Cargo.toml
src/app/data_farmer.rs
src/app/data_harvester.rs
src/app/data_harvester/cpu/sysinfo.rs
src/app/data_harvester/memory/general/heim.rs
src/app/data_harvester/memory/general/sysinfo.rs
src/bin/main.rs
src/canvas.rs
src/canvas/canvas_colours.rs
src/canvas/widgets/mem_basic.rs
src/canvas/widgets/mem_graph.rs
src/constants.rs
src/data_conversion.rs
src/lib.rs
src/options.rs

Adds arc support for linux and freebsd.
This is enabled by default with the zfs feature flag but only shown at runtime when arc collection support is detected.
Linux with arc:
Linux no arc:
FreeBSD with arc:
FreeBSD no arc:
Windows no arc:
This does not include extra arc information like compression ratio.
refs: https://github.com/ClementTsang/bottom/issues/688
I did **not** test for macOS arc support...(it may work with sysctl like freebsd?)
Feel free to close the PR if the implementation is too erroneous

Add zfs feature flag for arc memory

---

Cargo.lock
Cargo.toml
docs/content/support/unofficial.md
src/app/data_harvester/cpu/sysinfo.rs
src/app/data_harvester/processes.rs
src/app/data_harvester/processes/linux.rs
src/app/data_harvester/processes/macos_freebsd.rs
src/app/data_harvester/processes/windows.rs

Update [sysinfo](https://github.com/GuillaumeGomez/sysinfo) to 0.26.2. This dependency update has some nice things in store for us:
- MacOS M1 temperature support
- Bevy of bug fixes
Closes: #382 
This **must** be tested on all three platforms! Additionally, we'll want to test on M1 and (if possible) x86 macOS.

deps: update sysinfo to 0.26.2

---

src/app/data_harvester/temperature/heim.rs

This commit replaces heim sensor reading with manual sysfs sensor reading, and skips reading sensors for any device that is in ACPI D3cold, instead returning 0.
This has the notable downside of still keeping a device awake, which I hope to solve in a later commit or PR
Another notable potential issue with this PR is that, while heim has its own method for async reading of files, bottom itself does not seem to, and I didnt want to arbitrarily pull in a dependency to do that, so even though `get_temperature_data` is async, I used the normal sync I/O methods. I justify this by the fact that sysfs is in-memory and presumably shouldnt block for the operations being done here.
Changing this should be relatively easy if need be and a path is decided
To the best of my knowledge, this change has …

Replace heim with sysfs and dont wake devices

---

src/app/data_harvester/temperature.rs
src/app/data_harvester/temperature/heim.rs

Since we no longer rely on heim to do temperatures in Linux, we can skip using their conversion code and just use some pre-existing temp conversion code.

refactor: replace heim temp conversion code

---

src/app/data_harvester/temperature/linux.rs

Checks `/sys/class/hwmon/hwmon*/device/` and `/sys/class/thermal_zone*/` as additional fallback temperature sources.
Closes: #814

bug: fix missing temp path locations to check on Linux

---

Cargo.lock
Cargo.toml
src/app/data_harvester/memory/general/sysinfo.rs
src/app/data_harvester/processes/macos_freebsd.rs
src/app/data_harvester/processes/windows.rs

During a sysinfo update, the default unit changed from kilobytes -> bytes in memory contexts, which wasn't accounted for.
Closes: #

fix wrong unit being used for memory in sysinfo data

---

src/app/widgets/process_table/proc_widget_column.rs
src/components/data_table/sortable.rs

Use an associated type for `SortsRow`.
Closes: #

refactor: switch to associated type for SortsRow

---

README.md

Bottom is now available in the official Gentoo repo, overlay information is now outdated and can be removed
Bottom is no longer in the Guru repo
The official Gentoo package can be viewed here
https://packages.gentoo.org/packages/sys-process/bottom

Update gentoo install instructions

---

src/app.rs
src/app/data_harvester.rs
src/app/data_harvester/memory/general/heim.rs
src/app/data_harvester/memory/general/sysinfo.rs
src/app/layout_manager.rs
src/canvas/widgets/mem_basic.rs
src/clap.rs
src/options.rs

Follow-up to #794, this makes GPU memory collection toggleable.
Closes: #

other: make gpu memory collection configurable

---

docs/content/configuration/command-line-flags.md
docs/content/configuration/config-file/flags.md
docs/content/configuration/config-file/theming.md
sample_configs/default_config.toml
src/constants.rs
src/options.rs

Enables use of cli argument `enable_gpu_memory` and adds it to the default config file.
Updates some of the docs for arc/gpu styles, gpu flag and gpu cli flag.
Follow-up to https://github.com/ClementTsang/bottom/pull/794 and https://github.com/ClementTsang/bottom/pull/835
I did **NOT** update the changelog.
Feel free to close if unwanted.

enable gpu mem cli and update docs for arc/gpu mem

---

src/app.rs

The PageUp and PageDown keys weren't doing anything in the help dialog, so I added some lines to make them work.
Easier navigation in the help dialog.
I ran `cargo test` after my changes. For the behavior of the keys themselves, I tested it manually.
- [  ] _Windows_
- [  ] _macOS_
- [ x ] _Linux_
- [ x ] _Areas your change affects have been linted using rustfmt (`cargo fmt`)_
- [ x ] _The change has been tested and doesn't appear to cause any unintended breakage_
- [  ] _Documentation has been added/updated if needed (`README.md`, help menu, etc.)_
- [  ] _The pull request passes the provided CI pipeline_
- [ x ] _There are no merge conflicts_
- [  ] _If relevant, new tests were added (don't worry too much about coverage)_

Implement PgUp and PgDown in the help dialog.

---

.cirrus.yml
.github/workflows/ci.yml

Adds CirrusCI testing for FreeBSD and M1 platforms. 
Closes: #

ci: add basic Cirrus CI testing for FreeBSD + M1

---

.cirrus.yml
.github/workflows/audit.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/deployment.yml
.github/workflows/test-docs.yml

See [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) (deprecated `set-output`) and [here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) (Node 12 is deprecated) - this was causing a bunch of warnings/spam in CI/workflows.
The updated CI changes are as follows:
- Use `macos-12` rather than `macos-latest` (which pointed to 11, and was warning that it was going to move to 12)
- Use `Swatinem/rust-cache` pinned to `22c9328bcba27aa81a32b1bef27c7e3c78052531` (version 2.0.1)
- Use `dtolnay/rust-toolchain` pinned to …

ci: update GitHub CI to remove deprecated/unmaintained actions and commands

---

.cirrus.yml
README.md

Adds M1 macOS and FreeBSD binary builds via Cirrus CI. Note I need to still add some code to grab the generated binaries from Cirrus CI for releases here.
Closes: #843

ci: add FreeBSD and macOS M1 builds

---

.cirrus.yml
README.md

Adds a build alias for Cirrus to make it easier to reference build artifact URLs. 
Closes: #

ci: add Cirrus build alias for easier build artifact URLs

---

src/app/data_harvester/temperature/linux.rs

This changes how temperature sensors are displayed, in a way I believe to be much better.
This PR is based on top of and requires #805 
Comparison
Before:
After:
Tested on my personal machine. This will likely need additional testing due to the apparent lack of a standard way to get better sensor names.

More human friendly temperature sensor naming

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/nightly.yml
.github/workflows/test-docs.yml

Seems a bit redundant to take up cache space with release builds, especially since it usually just runs once a day (nightly) or occasionally (stable releases).
Closes: #
CI should pass, [nightly build](https://github.com/ClementTsang/bottom/actions/runs/3392307949) should pass.

ci: remove caching for release building

---

CHANGELOG.md
docs/content/usage/widgets/temperature.md
src/app.rs
src/app/widgets/process_table.rs
src/app/widgets/temperature_table.rs
src/bin/main.rs
src/lib.rs

Add sorting + shortcuts to the temp widget.
I don't really want to break the current behaviour, so the default sort is still ascending + by temp sensor name.
Nice to haves later:
- Currently doesn't have a sort table added, maybe needed?
- I want to do some refactoring
- Maybe an option for setting default order/index (e.g. temp)
Closes: #429 

feature: basic sortable temp

---

.github/workflows/audit.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml

Only able caching if triggered by a non-PR event or a non-fork PR.
Closes: #
CI should pass.

ci: only enable ci cache if not a PR or not a fork

---

CHANGELOG.md
docs/content/usage/widgets/process.md
src/app.rs
src/app/widgets/process_table.rs
src/bin/main.rs
src/lib.rs

Adds paste support to the process search bar.
Unix support is primarily implemented using paste events. Windows falls back to keyboard inputs; to support this, I removed the key event throttler since it doesn't really seem to be necessary anymore.
This also fixes a potential issue of the grapheme cursor increment occasionally failing if it doesn't have enough context - luckily, the unicode library has a fix for that.
Closes: #880 
_If this is a code change, please also indicate which …

feature: search paste support

---

.github/workflows/build_releases.yml
.github/workflows/deployment.yml

This resolves [this](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) GitHub Actions deprecation warning.
For more context, see #846.
Closes: #
All affected workflows *should* pass, though it might be hard to test deployment without some extra work. We'll mainly just test nightly instead, which should be fine as there are no breaking changes. The previous …

ci: update upload-artifact to 3.1.1 to remove set-output warnings

---

.github/workflows/nightly.yml

This resolves [this](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) GitHub Actions deprecation warning by switching over to a personal fork of the action.
For more context, see #846.
Closes: #
Non-mock nightly should work. Workflow: https://github.com/ClementTsang/bottom/actions/runs/3443381845/jobs/5744852253

ci: switch delete-tag-and-release to personal fork to avoid node16 warning

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docs/content/configuration/command-line-flags.md
docs/content/configuration/config-file/flags.md
sample_configs/default_config.toml
src/app.rs
src/bin/main.rs
src/clap.rs
src/constants.rs
src/options.rs

Allows for custom data retention ranges by setting either `--retention` or the `retention` field in the config flags. This supports a human-readable time (e.g. `5m, 1d`).
Closes: #239

feature: add custom retention periods for data

---

Cargo.lock
Cargo.toml
src/app/data_harvester.rs
src/bin/main.rs

A really ugly band-aid fix to stop stderr messages from being printed on only FreeBSD systems due to data gathering.
Closes: #798 

bug: redirect stderr on FreeBSD to avoid drawing on UI

---

Cargo.lock
Cargo.toml
src/canvas/canvas_colours/colour_utils.rs
src/utils/error.rs
tests/invalid_configs/invalid_colour_name.toml

I actually don't know why I was doing it like that before.
This commit removes the phf crate, as it's not needed anymore.
Closes: #

other: don't use manual map for color name mapping

---

CHANGELOG.md
docs/content/configuration/command-line-flags.md
docs/content/configuration/config-file/flags.md
sample_configs/default_config.toml
src/app.rs
src/app/data_harvester.rs
src/app/data_harvester/processes/freebsd.rs
src/app/data_harvester/processes/linux.rs
src/app/data_harvester/processes/macos.rs
src/app/data_harvester/processes/macos_freebsd.rs
src/app/data_harvester/processes/windows.rs
src/clap.rs
src/constants.rs
src/lib.rs
src/options.rs

Some cleanup around the non-normalized process CPU% feature, and updating relevant documentation. Also renames the flag to `unnormalized_cpu`, though I'm open to changing it.
Closes: #

other: non-normalized process CPU% cleanup and docs

---

src/app/data_harvester/temperature/linux.rs

On Linux, when an `iwlwifi` (Intel Wi-Fi) device is disabled, its `temp1_input` file becomes empty and causes `fs::read_to_string` to return an error. This PR fixes the issue by ignoring the error and skipping the file.
Did not open one since I quickly worked out the fix.

bug: fix reading temperature from disabled devices

---

CHANGELOG.md
src/canvas.rs

Fixes an occasional gap appearing due to how rect spacing was previously calculated.
Closes: #896

bug: fix possible gaps with widget layout spacing

---

.cirrus.yml
scripts/cirrus/build.py

This adds FreeBSD 12-3 as a Cirrus target for builds and checks.
Closes: #
- CI workflow should succeed
- Nightly workflow should succeed: https://github.com/ClementTsang/bottom/actions/runs/3605977724

ci: add freebsd 12 as a build/check target

---

src/bin/main.rs

The frozen case or cleaning cases don't really need to force a screen redraw.
Closes: #

other: don't draw on non-updating events

---

src/components/data_table/sortable.rs
src/utils/gen_util.rs
src/widgets/cpu_graph.rs
src/widgets/disk_table.rs
src/widgets/process_table/proc_widget_data.rs
src/widgets/process_table/sort_table.rs
src/widgets/temperature_table.rs

The previous "new" way I was calculating width seems to be wrong... as was the one before that, probably. This new version should hopefully be a bit more accurate in terms of emoji/CJK/unicode width calculations for our purposes, with more tests to check for intended behaviour.
Closes: #

bug: fix incorrect text calculation

---

sample_configs/default_config.toml
src/app.rs
src/bin/main.rs
src/clap.rs
src/constants.rs
src/options.rs

Addresses #822: Adding option to expand widgets on startup. Also adding the corresponding option to config file.
Closes: #822 
testing by `debug_assert()` from `clap`.

Adding default expanded option to commandline and config (closes #822)

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml

Add a 30m timeout for build and CI workflows; they should never take that long.
Closes: #
Tested using CI + [nightly](https://github.com/ClementTsang/bottom/actions/runs/3655754107).

ci: add a timeout for builds and CI

---

src/app/data_harvester/temperature/linux.rs
src/app/process_killer.rs
src/canvas.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/cpu_basic.rs
src/canvas/widgets/process_table.rs
src/components/data_table/draw.rs
src/components/time_graph.rs
src/components/tui_widget/time_chart.rs
src/options.rs

Fixes marker settings being ignored by time graphs. Was caused by me forgetting to pass the argument into the builder. This also fixes a bevy of clippy warnings brought on by Rust 1.66.
Partly address: #933

bug: fix dot marker setting not being considered

---

CHANGELOG.md
src/app.rs
src/app/query.rs
src/app/states.rs
src/canvas/drawing_utils.rs
src/canvas/widgets/process_table.rs
src/components/data_table/state.rs
src/utils/gen_util.rs
src/widgets/process_table.rs

This should help make search scrolling more reliable larger Unicode characters like CJK/flag characters.
Closes: #882 

bug: fix search scrolling with wider Unicode characters.

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/app.rs
src/data_conversion.rs
src/widgets/disk_table.rs

Denotes both usage and usage percentage. This also redoes the calculation for percentage to be based on the sum of avail + used, rather than on total, as otherwise we get potentially confusing percentages.
Closes: #

feature: split usage into usage percentage and value

---

.cirrus.yml
.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/build_releases.yml
README.md
build.rs
scripts/cirrus/build.py
src/clap.rs

This adds the build hash to the `btm -V` output for nightly builds, making it easier to troubleshoot when someone might have obtained a nightly build, and what commit it corresponds to.
Closes: #
Manually run nightly build workflows:
- [Nightly test one](https://github.com/ClementTsang/bottom/actions/runs/3821914007), should show the hash.
- [Nightly test …

ci: add build hash to nightly builds for version

---

CHANGELOG.md
src/components/data_table/draw.rs
src/widgets/cpu_graph.rs
src/widgets/disk_table.rs
src/widgets/process_table/proc_widget_data.rs
src/widgets/process_table/sort_table.rs
src/widgets/temperature_table.rs

Fixes the "All" label being missing on small windows. This was a regression due to #918. We work around it by moving the width skip check into the implementors.
Before vs after:
Closes: #

bug: fix CPU 'all' label missing on small sizes 

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/test-docs.yml

Seems like we want `github.ref`, not `github.event.ref`, which is blank. See [here](https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency) for details.
Closes: #

ci: fix CI concurrency grouping

---

src/app.rs
src/widgets/disk_table.rs

This is a temp change, this commit will be reverted after 0.7.1 comes out. Effectively reverses #950 for now without reverting the sorting fixes.
Closes: #

other: revert disk usage change for now

---

CHANGELOG.md
src/app.rs
src/canvas/widgets/battery_display.rs

Skips drawing the battery duration row if the duration is unknown.
Closes: #

other: skip battery duration draw if unknown

---

docs/content/usage/widgets/battery.md
src/options.rs

For bottom to know that there are no batteries on the system, I added the `battery::Manager` to the options.rs file because here is the first moment bottom verifies battery configuration by reading the config file, which may or may not contain the battery field, but for a better UX, it doesn't matter what bottom finds in the config file now, if it doesn't retrieve battery data, it just ignores the battery widget all together. Added cfg checks for `battery` feature.
If needed, it can be adjusted so that if the config file contains the battery field, it will still show the widget even without batteries on the system.
PR …

Dynamic battery widget

---

README.md

It is removing `-yu`, because it updates the system before downloading the package. ArchLinux is updated constantly and can crash the system, so it's better just to install the package.

feat: :wrench: Update ArchLinux install command

---

src/canvas/dialogs/dd_dialog.rs

This just explicitly styles the text "buttons" used for dd.
Closes: #

other: explicitly style dd text colours

---

build.rs
src/bin/main.rs
src/lib.rs

Appease clippy's new lints from 1.67. And by appease, I mean ignore the `uninlined-format-args` lint for now.
Closes: #

other: ignore uninlined_format_args clippy lint for now

---

Cargo.lock
Cargo.toml
src/bin/main.rs
src/clap.rs
src/lib.rs
src/options.rs

Replaced deprecated `value_of` and `is_present`, builds with no warnings, clap 3.2.2
Tested on Mac OS X and Fedora 36 with rust 1.67
``` bash
cargo test
btm
```

Replaced deprecated `value_of` and `is_present`, no warnings, clap 3.2.2

---

src/app/data_harvester.rs
src/app/data_harvester/processes.rs
src/app/data_harvester/processes/windows.rs
src/app/query.rs
src/widgets/process_table.rs
src/widgets/process_table/proc_widget_column.rs
src/widgets/process_table/proc_widget_data.rs

This adds the "User" column to the process table on Windows. Usernames are extracted using the `sysinfo` library.
The main reason for adding this is that it allows filtering of the processes that belong to the current user.
Tested by visual inspection:
- The name of the user running the application is correctly displayed.
- When running un-elevated, the usernames of other processes are shown as "N/A".
- When running elevated, the usernames for _some_ of the other processes are displayed. This appears to be a limitation of how `sysinfo` gathers usernames.
Tested on:

Add support for displaying process usernames on Windows

---

CHANGELOG.md
scripts/packager.py
src/canvas/canvas_styling/colour_utils.rs
tests/invalid_config_tests.rs
tests/invalid_configs/invalid_colour_hex_3.toml

Support three-character hex colours (e.g. "#fff").
Closes: #

feature: support 3-char hex colours

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
CHANGELOG.md
README.md
docs/content/support/official.md
docs/content/support/unofficial.md

Since I have a macOS M1 laptop to test on now, I think it's a good time to bump it to being officially supported, especially since it's going to be the main macOS platform for the foreseeable feature.
Closes: #

other: promote macOS aarch64 to official support

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/app/data_harvester/temperature/sysinfo.rs

Add simple support for FreeBSD-based systems that may get temperatures using sysctl and `hw.temperature`.
Closes: #797
I tested whether the code works for *some* sysctl - I tried it with `dev.cpu` on my FreeBSD box, and it works. I did **not** test it for `hw.temperature`, as that does nothing for my x86-64-based FreeBSD machine.

other: support hw.temperature-based temps on FreeBSD

---

src/lib.rs
src/widgets/process_table.rs

In tree mode, we already show an entry if any descendant matches. We now show as well if any ancestor matches.
Comparison having searched `"lightdm"`, with the current behaviour on the left and the new behaviour on the right:
Searching `"radeon"` (no change):
Comparison searching for `"code"`, current on the left and new on the right:
Closes: #668 

change: show process in tree if any ancestor or descendent matches

---

src/bin/main.rs

Move the terminal check to after the config check. This is just so if the config is invalid, that should warn first (e.g. in a test).
Closes: #

other: move terminal check after the config check

---

.github/workflows/audit.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml

Reduce the CI to 18 minutes since the current 30 minutes is unnecessarily long. Also add timeouts in some workflows.
Closes: #

ci: reduce CI timeout to 18 minutes

---

src/app/data_harvester/network/heim.rs
src/app/data_harvester/temperature.rs

Use filter logic from network/sysinfo in temperature and network/heim harvesters. Previously is_list_ignored=false filter configs would silently accept every sensor and every interface.
Network: with debug `eprintln!` of matched interface names
Temperature: by configuring the filter and checking that it now actually filters

Fix is_list_ignored=false filters for network and temperature

---

Cargo.toml
src/app/data_harvester/memory/sysinfo.rs
src/data_conversion.rs

Re-enable the zfs feature flag by default for deployment. 
Show zfs arc stats when available on linux/freebsd.
The code and comments come from the removed heim memory backend. 
(PR's for macos/windows zfs support are being reviewed upstream?)
Compiled on linux/freebsd.
Ran with basic and graph on linux/freebsd. 
Ran with and without zfs enabled on linux/freebsd.

re-enable zfs feature

---

Cargo.toml
src/app/data_harvester.rs
src/app/data_harvester/memory.rs
src/app/data_harvester/memory/sysinfo.rs
src/app/data_harvester/memory/windows.rs

Basically, we're going back to displaying the total `committed` usage, as we were when using heim.
I'm considering further breaking this down (and clarifying this isn't technically swap on Windows) in later PRs. See #1052 for more details/further work later.
Closes: #1043

refactor: use internal committed memory calculation for Windows

---

.github/workflows/build_releases.yml
.github/workflows/deployment.yml

Update the `upload-artifact` action hash to point from v3.1.1 to v3.1.2.
Changelog can be found [here](https://github.com/actions/upload-artifact/releases/tag/v3.1.2).
Closes: #
Tested using the [nightly workflow](https://github.com/ClementTsang/bottom/actions/runs/4372151573), seems to work fine for my use cases.

ci: update the upload artifact action to v3.1.2

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

Go back to using the default cache key with the target added, and bump `rust-cache` to 2.2.1.
Closes: #

ci: go back to using default cache key + target, update to 2.2.1

---

Cargo.lock
Cargo.toml

All key events are currently doubled on Windows. A quick guess/bisect found it to be because of #1033, so as a quick fix I'll revert for now.
For the root cause, it's possibly because now there is a keyup event in Windows.
Closes: #1065 

deps: temporarily revert crossterm 0.26.1 to fix double input bug on Windows

---

src/lib.rs

Explicitly ignore anything but `Press` key events from crossterm.
Related to #1065 

deps: switch back to crossterm 0.26.1 with fix to double keypress

---

Cargo.lock
Cargo.toml

I forgot to also bump crossterm back to 0.26.1 in the PR for #1068, I think the version changes got eaten due to some git branch/PR logic.
Closes: #

deps: forgot to bump crossterm back to 0.26.1

---

Cargo.lock
Cargo.toml
src/lib.rs

Updates sysinfo to 0.28.4, which contains a bunch of nice improvements and fixes.
Might affect/close: #1050?

deps: bump sysinfo to 0.28

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml

Runs a build instead of just a check, and bumps cross to 0.2.5 on CI actions.
Closes: #

ci: run build on unsupported platforms instead of check, bump cross

---

.gitignore
Cargo.lock
Cargo.toml
src/bin/main.rs

Now that we've removed heim, I can bump up other dependencies that relied on newer versions of once_cell.
Closes: #

deps: bump once_cell and related dependencies

---

.github/workflows/clear-workflow-cache.yml
scripts/clear_cache.py

Since there's occasionally stragglers, this runs the script 2x and adds some delays in between.
Closes: #

ci: run wf cache clear script twice with delays

---

CHANGELOG.md
src/app/data_harvester.rs
src/app/layout_manager.rs
src/bin/main.rs

This PR has two main changes:
- Draw once ASAP after initialization to quickly produce a visual UI, even if devoid of data.
- Shorten data initialization sleep (for many cases) and load it earlier to load the first batch of data a bit faster.
Closes: #

other: Speed up first draw and first data collection

---

CHANGELOG.md
docs/content/usage/widgets/battery.md
src/app/data_harvester/batteries/battery.rs
src/canvas/widgets/battery_display.rs
src/data_conversion.rs

Adds an additional field to clarify the current charging state, and update one of the fields from `consumption` to `rate`. Also tweak some auto text hiding logic.
Closes: #

feature: add current battery charging state, update field names

---

src/constants.rs

Seems like I broke this when migrating from tui-rs to ratatui. This just uses explicit enum variants to set my side borders and a test to try and make sure this doesn't happen again.
Closes: #

bug: fix side borders in basic mode

---

Cargo.lock
Cargo.toml
src/widgets/process_table.rs

I was importing it for just one use case, but I could just define the const string manually and not pull it in at all.
Closes: #

deps: remove const_format dependency

---

CHANGELOG.md
src/app/data_harvester/processes.rs
src/app/data_harvester/processes/linux.rs
src/app/data_harvester/processes/macos_freebsd.rs
src/app/data_harvester/processes/windows.rs
src/app/query.rs
src/options/process_columns.rs
src/utils/error.rs
src/widgets/process_table.rs
src/widgets/process_table/proc_widget_column.rs
src/widgets/process_table/proc_widget_data.rs

Add a column to the processes table to show the running time of a process

feature: show running time of processes

---

src/bin/main.rs

This just makes it so that even if the logger is enabled, if it fails to initialize (e.g. read-only directory), bottom will still continue to start up, and just print a warning that the logger encountered an issue.
Closes: #1131

other: keep running even if logger fails to initialize

---

Cargo.toml
docs/content/contribution/development/build_process.md

This makes it so that you need to opt-in to debug log logging when building by using `--features logging` (which makes more sense since only devs would be using it for now).
Related to: #1131
Tested by building and observing `fern` and `log` are not compiled by default. Enabling the feature does rope them in and debug logging works.

other: disable logging when building with default features

---

CHANGELOG.md
src/canvas/canvas_styling.rs
src/constants.rs

The hex string was incorrectly defined (missing a `"#"`). This PR just fixes it and adds a test to check it in the future.
Closes: #

bug: fix gruvbox cache colour being invalid

---

src/bin/main.rs
src/canvas.rs
src/canvas/canvas_styling.rs
src/canvas/canvas_styling/colour_utils.rs
src/components/data_table/styling.rs
src/options.rs
src/widgets/cpu_graph.rs
src/widgets/disk_table.rs
src/widgets/process_table.rs
src/widgets/temperature_table.rs

Greatly simplify a bunch of logic around setting colours. This also renames `CanvasColours` to `CanvasStyling` since we'll probably add non-colour-related text styling fields to the struct (e.g. bold modifiers).
Closes: #

refactor: use macros for initializing canvas styles

---

src/options.rs

refactor: remove unused typed-builder proc macro usage in options

---

src/app/layout_manager.rs
src/options/layout_options.rs

Incrementally rolling out changes to remove `TypedBuilder`. This removes it for `BottomColRow`; I'll probably rewrite this in general in the future but I want to remove the dependency since I don't really need it otherwise.
Closes: #

refactor: remove TypedBuilder for col row

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/options.rs

This adds support for using human times (e.g. "1s", "20 min") `time_delta` and `default_time_value` flags.
Closes: #

feature: support human times for `default_time_value` and `time_delta`

---

src/app/data_harvester/temperature/linux.rs

This meant that if hwmon failed, it would never try and get temperatures from thermal or GPU. The same is true for thermal failing leading to GPU never running.
I'm guessing this could happen if, for example, `hwmon` doesn't exist --> returns an `Err`, which then meant the entire pipeline ends with an `Err`.
See: https://github.com/ClementTsang/bottom/discussions/1185
_If relevant, ensure the following have been …

bug: when getting Linux temps, don't bail ASAP if they fail

---

CHANGELOG.md
src/app/data_harvester/temperature/linux.rs

This adds some numerical counters if there are duplicate temp sensors found by `/sys/class/thermal`.
For example, if you had 3 `iwlwifi` sensors, it would be labelled `iwlwifi`, `iwlwifi (1)`, and `iwlwifi (2)`, for easier differentiation.
Closes: #

feature: use better names for duplicate temp sensors found by `/sys/class/thermal`

---

src/bin/main.rs
src/lib.rs

I think there shouldn't be any issues with enforcing this now...
Closes: #

other: enforce unused_imports lint again

---

src/app/data_harvester/disks/unix/file_systems.rs

Match `ntfs3` as NTFS. I didn't use `eq_ignore_ascii_case` because it's specific to Linux and the letters won't be uppercase.
Partitions mounted using the ntfs3 driver in linux (mainlined since 5.15) won't show up because the name didn't match.
Here's the relevant line in `/proc/mounts`:
```
/dev/sdb2 /mnt/hdd_4t ntfs3 rw,noatime,uid=0,gid=0,iocharset=utf8 0 0
```

bug: ntfs3 mounts don't show up

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This fixes an issue where M1 macOS would report far lower battery health values than reasonable; the fix was done upstream in the starship-battery crate which we rely on, and so updating it fixes the issue.
Much thanks to @WenqingZong for reporting the issue in the first place and making the fix upstream!
Closes: #1164 

deps: bump battery to 0.8.1 to fix M1 health bug

---

CHANGELOG.md
src/app/data_harvester/temperature/linux.rs
src/app/data_harvester/temperature/nvidia.rs

feature: on Linux, check coretemp and don't fail fast with name generation when gathering temps

---

Cargo.lock
Cargo.toml

Did `cargo update`. Only root dep change is bumping `clap`.
Probably merge this after publishing 0.9.2.
Closes: #

bump dependencies and Cargo.lock as of 2023-06-10

---

.github/workflows/build_releases.yml
Cargo.toml
docs/content/contribution/packaging-and-distribution.md

Closes: #
Tested with nightly: https://github.com/ClementTsang/bottom/actions/runs/5263689619

ci: add RPM package generation

---

src/app/data_harvester/processes.rs
src/app/data_harvester/processes/linux.rs
src/app/data_harvester/processes/unix/process_ext.rs
src/app/data_harvester/processes/windows.rs
src/app/frozen_state.rs
src/app/query.rs
src/clap.rs
src/widgets/process_table/proc_widget_data.rs

This cuts down memory by a tiny bit, and we don't need a full f64 for percentage values.
Closes: #

other: use f32 for process percentage values

---

CHANGELOG.md
src/clap.rs

clap v4 apparently changed it so arguments are not sorted by default like before - this manually sorts the arguments beforehand to achieve the same effect.
Closes: #

bug: fix arguments being unsorted

---

CHANGELOG.md
src/app.rs

Basically, you could overflow/underflow the time span which would skip checks.
Closes: #

bug: fix overflow/underflow with graph timespan zoom

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/lib.rs

The cause was:
- bottom thinks it's panicking if the terminal is closed.
- The panic hook tried to print out to the terminal - but the terminal was closed! It would unwrap and thus panic even harder.
- To solve this, we just make the panic hook calls not unwrap, since honestly if they fail it's whatever as far as I understand it.
Closes: #1227 

bug: fix core dump if the terminal is closed while bottom is open

---

CHANGELOG.md
src/app/process_killer.rs

On dropping the `Process` struct, we should close the handle to avoid keeping it open permanently.
Closes: #1242

bug: missing windows syscall to close the handle on drop when killing

---

Cargo.lock
Cargo.toml

deps: lock sysinfo to 0.29.4

---

src/app/data_farmer.rs
src/app/data_harvester/disks.rs
src/app/data_harvester/disks/freebsd.rs
src/app/data_harvester/disks/io_counters.rs
src/app/data_harvester/disks/unix/linux/counters.rs
src/app/data_harvester/disks/zfs_io_counters.rs

ZFS datasets in the disk menu lacked support for monitoring the read and written bytes.
This PR adds io-counters (read bytes and written bytes) for the named zfs datasets in the disks menu. 
Screens:
Linux:
FreeBSD:
Tested on linux and freebsd, with and without zfs.
I did **NOT** test with an extensive zfs setup (no draid/raidz/spares) just my simple mirror pools (maybe use file backed pools to test?)
If any of the Issues should be addressed or a different approach used please let me know.
Feel free to close this PR if it is unwanted.

add zfs io counters for linux and freebsd

---

Cargo.lock
Cargo.toml

deps: lock sysinfo to 0.29.5

---

src/app/data_harvester/memory/arc.rs

Previously the ARC usage showed it having a maximum size of the amount of ram in the system regardless of what [zfs_arc_max](https://docs.oracle.com/cd/E26505_01/html/E37386/chapterzfs-3.html) was set to.
Changes were tested by changing the arc max size and ensuring the value was reflected in bottom.

bug: display arc max size in arc usage instead of system memory

---

.github/workflows/build_releases.yml

I have no idea why, but builds are failing for musl now when I try to build release builds as of Rust 1.72.0. Hm.
This pins musl to 1.71.0 for now while leaving everything else at `stable`.
Closes: #

ci: pin musl to 1.71.0 for now when building releases

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

deps: pin serde to 1.0.188

---

.github/workflows/build_releases.yml

Bumping to Rust 1.72 and onward causes CI to fail when building release builds on musl. This might be related to https://github.com/rust-lang/rust/issues/115430.
Regardless, seems like building via `cross` solves the issue.
Closes: #
Tested [here](https://github.com/ClementTsang/bottom/actions/runs/6288578367) via GHA.

ci: test if building with musl on Rust > 1.71 works again

---

build.rs
src/app/data_harvester.rs
src/app/data_harvester/cpu/sysinfo.rs
src/app/data_harvester/disks/unix/linux/partition.rs
src/app/query.rs
src/args.rs
src/bin/main.rs
src/canvas.rs
src/canvas/canvas_styling.rs
src/data_conversion.rs
src/options.rs
src/utils/error.rs
src/utils/gen_util.rs
src/widgets/process_table.rs
src/widgets/process_table/proc_widget_column.rs
src/widgets/process_table/sort_table.rs
tests/util.rs

Keep code a bit tidier and consistent (i.e. if an identifier already has a `use` entry above, why in some cases still prove a full path to it?)

Chore: Minor cleanup - remove un-needed ident qualifiers

---

src/app/data_harvester/disks/unix/linux/partition.rs
src/components/data_table.rs
src/components/data_table/data_type.rs
src/components/data_table/sortable.rs
src/widgets/cpu_graph.rs
src/widgets/disk_table.rs
src/widgets/process_table/proc_widget_data.rs
src/widgets/process_table/sort_table.rs
src/widgets/temperature_table.rs

I am not certain if it will pass 1.70, but it does pass the latest Rust

Chore: Remove un-needed lifetimes in a few calls

---

src/app/data_harvester/disks/unix/file_systems.rs

Match `msdos` (fat32) as `vfat`
Partitions mounted using the fat32(msdos) driver in macOS (Sonoma 14.0) won't show up because the name didn't match.
Relevant information provided by `diskutil list`
```
/dev/disk4 (external, physical):
#:                       TYPE NAME                    SIZE       IDENTIFIER
0:     FDisk_partition_scheme                        *123.0 GB   disk4
1:             Windows_FAT_32 SANDISK                 123.0 GB   disk4s1
```
Manually check on macOS (Sonoma)

bug: fat32 mounts don't show up in macOS

---

docs/content/configuration/config-file/data-filtering.md
docs/content/configuration/config-file/flags.md
docs/content/configuration/config-file/layout.md
docs/content/contribution/development/build_process.md
docs/content/contribution/documentation.md
docs/content/contribution/packaging-and-distribution.md
docs/content/index.md
docs/content/usage/widgets/network.md
docs/requirements.txt

bumps mkdocs-material to 9.4.8, mkdocs to 1.5.3, mkdocs-material-extensions to 1.3
Closes: #

docs: bump mkdocs-related dependencies to latest

---

README.md

This has worked for a while (in a limited capacity at least) but I never added it to the README. Might as well.
Closes: #

docs: add Android as unsupported but builds in README

---

src/components/data_table.rs
src/utils/gen_util.rs

Adds `clamp_lower` and `clamp_upper` util functions for numeric types.
Closes: #

other: add additional clamping functions on numeric types

---

src/app/data_harvester/nvidia.rs
src/app/data_harvester/temperature.rs
src/app/data_harvester/temperature/linux.rs
src/app/data_harvester/temperature/sysinfo.rs

Just make it a function on the temperature type enum.
Closes: #

refactor: simplify temperature conversion function usage

---

CHANGELOG.md

docs: update changelog and fix heading sizes

---

src/utils/gen_util.rs

Another branch to skip slicing/iteration if the string is short enough compared to the width given that it _must_ fit. This makes it fast to have a small string and/or a lot of space to accommodate it, which is likely the most usual case.
The `faster_ascii` below shows benchmark speed of each function (`original` is the implementation before #1330).
Closes: #

refactor: add fast branch if the string is short enough to not be truncated

---

src/utils/gen_util.rs

This PR now does string truncation and ASCII detection side by side iteratively, as opposed to the previous method of doing one full ASCII check pass before building the string.
Benchmark code: https://gist.github.com/ClementTsang/e84ff878892928f4789ac724be3a56a9
Resulting charts:
Closes: #

refactor: iteratively detect ASCII and build string when truncating

---

.github/workflows/build_releases.yml

Looks like `checkout@v4` action causes some problems with the quay container (see https://github.com/actions/checkout/issues/1474), this PR just adds an exception for it to use the previous v3 checkout action.
Closes: #1351
[Test build job](https://github.com/ClementTsang/bottom/actions/runs/7118078437)

ci: downgrade to checkout v3 when building releases in non-GH containers

---

.cargo/config.toml
docs/content/configuration/config-file/cpu.md
sample_configs/default_config.toml
src/app.rs
src/components/data_table.rs
src/components/data_table/draw.rs
src/components/data_table/sortable.rs
src/constants.rs
src/options.rs
src/options/cpu.rs
src/widgets/cpu_graph.rs

feature: support default selection of average CPU graph

---

CHANGELOG.md
src/app/data_harvester/nvidia.rs
src/app/data_harvester/temperature.rs
src/app/data_harvester/temperature/linux.rs
src/app/data_harvester/temperature/sysinfo.rs
src/bin/main.rs
src/data_conversion.rs
src/utils/logging.rs
src/widgets/temperature_table.rs

SC immediately if a non-D0 state is encountered while grabbing temp data in Linux.
Maybe affects #1291?

other: if in a non-D0 state, short-circuit further logic

---

Cargo.lock
Cargo.toml
src/bin/main.rs
src/canvas.rs
src/canvas/dialogs/dd_dialog.rs
src/canvas/dialogs/help_dialog.rs
src/canvas/widgets/basic_table_arrows.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/cpu_basic.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/mem_basic.rs
src/canvas/widgets/mem_graph.rs
src/canvas/widgets/network_basic.rs
src/canvas/widgets/network_graph.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temperature_table.rs
src/components/data_table/draw.rs
src/components/time_graph.rs
src/components/tui_widget/time_chart/canvas.rs
src/data_conversion.rs

Update `ratatui` to version `0.25.0` (api changes: moved the `Backend` type, moved `widths` to `new` and added a `Marker` for half block)
Use `convert_mem_label` instead of `convert_arc_labels`
Ran on linux with arc enabled.
Feel free to close if the dependency should remained pinned.

update ratatui version

---

src/data_collection/disks/unix/file_systems.rs

Make sure that bcachefs mounts are also displayed in the disks widget. bcachefs is a file system that will be included in the upcoming Linux v6.7 kernel. Briefly tested this and it works on my system.

feature: Add support for bcachefs

---

CHANGELOG.md
Cargo.lock
Cargo.toml
build.rs
src/options/args.rs
src/options/args.template

Groups args together to be less confusing, both for dev work and in the help menu.
I'll also do a pass on all the arg options and consolidate some of the arg + config code after this.
Closes: #

refactor: rearrange/resort args

---

docs/content/index.md
docs/mkdocs.yml
docs/requirements.txt
docs/serve.sh

Some newer features of mkdocs-material.
Closes: #

docs: add copyright + auto palette + dates 

---

Cargo.lock
Cargo.toml
src/data_collection.rs
src/data_collection/cpu/sysinfo.rs
src/data_collection/disks/other.rs
src/data_collection/disks/windows.rs
src/data_collection/memory/sysinfo.rs
src/data_collection/network/sysinfo.rs
src/data_collection/processes/linux.rs
src/data_collection/processes/macos.rs
src/data_collection/processes/unix.rs
src/data_collection/processes/unix/process_ext.rs
src/data_collection/processes/windows.rs
src/data_collection/temperature/sysinfo.rs

deps: bump sysinfo to =0.30.5

---

Cargo.lock
Cargo.toml
src/canvas/styling/colour_utils.rs
src/options.rs
src/options/args.rs
src/options/config.rs
src/options/config/process_columns.rs
tests/integration/arg_tests.rs

This just cleans up even more arg/options-related code and some of the help text. Originally part of `simplify_options_and_args_merging` but pulled out to a separate PR.
Closes: #

other: flatten process config struct and clean up help text

---

.cirrus.yml
scripts/cirrus/build.py

Looks like the newest available FreeBSD images are 13-2 and 14-0, and the previously used ones aren't available anymore.
Closes: #
Nightly run [here](https://github.com/ClementTsang/bottom/actions/runs/7685249483).

ci: update cirrus-ci FreeBSD versions

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/docs.yml
.github/workflows/post-release.yml
.github/workflows/test-docs.yml

Fixes some node deprecation warnings in workflows. All that's left is wretry, which I've filed an issue for here: https://github.com/Wandalen/wretry.action/issues/126
Closes: #

ci: bump skip-duplicate-actions to v5.3.1 and setup-python to v5.0.0

---

.github/workflows/build_releases.yml
.github/workflows/nightly.yml

To avoid node deprecation warnings, this bumps the choco action to v3.0.0 and switches to `gh release delete` to clean up the nightly release.
Closes: #
Nightly run: https://github.com/ClementTsang/bottom/actions/runs/7689376083

ci: bump choco action to v3.0.0 and replace release deletion action

---

Cargo.lock
Cargo.toml
src/app.rs
src/canvas.rs
src/canvas/components/data_table.rs
src/canvas/components/data_table/column.rs
src/canvas/components/data_table/data_type.rs
src/canvas/components/data_table/draw.rs
src/canvas/components/data_table/sortable.rs
src/canvas/components/data_table/state.rs
src/canvas/components/time_graph.rs
src/canvas/components/tui_widget/time_chart.rs
src/canvas/components/tui_widget/time_chart/canvas.rs
src/canvas/components/tui_widget/time_chart/points.rs
src/canvas/widgets/network_graph.rs
src/utils/general.rs
src/widgets/cpu_graph.rs
src/widgets/disk_table.rs
src/widgets/process_table.rs
src/widgets/process_table/proc_widget_data.rs
src/widgets/process_table/sort_table.rs
src/widgets/temperature_table.rs

Bumps to 0.26. Followed the guide for breaking changes from 0.26: https://github.com/ratatui-org/ratatui/blob/main/BREAKING-CHANGES.md#v0260
Changes:
- The only real thing I think I needed to update was some code around the fields for `Text` and some column spacing code for drawing tables.
- Optimized some cases of non-zero u16s out since we were always just filtering them out anyway when doing column spacing.
- Also took advantage of this version update to refactor/update `TimeChart` and some `canvas.rs` code.
Another thing to check in a separate PR is to see if I can skip how I currently manually calculate widths for …

deps: bump ratatui to 0.26

---

CHANGELOG.md
docs/content/usage/widgets/process.md
src/widgets/process_table.rs

other: add process uptime as a default column

---

README.md

Fixes a broken link to configuration documentation in the `README`. 
Previous link:
New link (one level up):

docs: fix broken link to config documentation in README

---

.cirrus.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
scripts/cirrus/build.py

M1 macOS runners are now available on GHA, so we can use it instead of CirrusCI for builds/CI. This should hopefully be faster and better integrated than Cirrus is.
(More info: <https://github.com/orgs/community/discussions/102846>)
Closes: #
Mock nightly run: https://github.com/ClementTsang/bottom/actions/runs/8128068411

ci: migrate macOS ARM builds to use GHA

---

Cargo.lock
Cargo.toml

bottom doesn't have an MSRV, but if we can still build on older versions of Rust then I'm all for it. The updated clap versions didn't bring anything interesting so there's no real issue for me to downgrade IMO.
Also updates a few dependencies as they were also causing issues.
Closes: #

deps: downgrade clap and run cargo update to build on 1.70

---

.github/workflows/build_releases.yml

The ARM versions are going to be handled by updating the images (see https://github.com/ClementTsang/cargo-deb-arm/pull/15).
Of note, technical breaking change as per the upstream `cargo-deb` repo:
> Note Since v2.0.0 the deb package version will have a "-1" suffix. You can disable this by adding --deb-revision="" flag or revision = "" in Cargo metadata. The default suffix is for compliance with Debian's packaging standard.
Closes: #
Mock nightly build: …

ci: bump cargo-deb version to 2.1.0

---

Cargo.lock
Cargo.toml

This increases the "unofficial" MSRV to 1.74, and therefore we can also bump clap and related dependencies.
Closes: #

deps: bump clap-related dependencies, increase unofficial msrv to 1.74

---

docs/content/configuration/config-file/flags.md

- There is currently no indication under which [table](https://toml.io/en/v1.0.0#table) do "flags" go in the config file.
- I think having that being explicitly spelled out & having an example saves quite a bit of people's time. Would for me 🙃
- N/A, I just created a PR directly on GitHub, can spin up one if you want though.
- N/A

docs: Which table goes "flags" under?

---

.github/workflows/build_releases.yml

Seems like we've got a fun new feature to work with for validating builds, and it seems easy to integrate: https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
Closes: #

ci: try attestations for binaries

---

src/canvas/widgets/battery_display.rs

This changes the behavior of the battery widget when paired with the `skip_table_gap`.
Closes: #1457
Tested with and without the `skip_table_gap` argument, both times works as expected. I only have access to a macOS laptop so I cannot test on Windows or Linux. I'm not proficient in Rust, so I'm open to feedback. 

Battery table_gap patch

---

.github/workflows/nightly.yml

If we don't have a change a nightly build can be skipped.
Closes: #

ci: add skip for nightly build

---

.github/workflows/coverage.yml
src/options/args.rs
tests/integration/arg_tests.rs

I used the wrong flag casing (`-V` vs `-v`) which broke Cirrus CI, which expected to run `btm -V` as a sanity check.
This fixes it and adds a test to catch it in the future.
Closes: #

bug: fix -V not working and causing Cirrus CI to fail

---

.github/workflows/validate_schema.yml
Cargo.lock
Cargo.toml
sample_configs/default_config.toml
schema/nightly/bottom.json
scripts/schema/validator.py
src/constants.rs
src/main.rs
src/options.rs
src/options/colours.rs
src/options/config/cpu.rs
src/options/config/process.rs
src/widgets/process_table.rs

Add a test for an uncommented variant of the default config file.
Closes: #

other: add schema test for uncommented default config

---

src/data_collection/processes/unix/user_table.rs
src/data_collection/temperature/linux.rs
src/utils/error.rs

This knocks out `CrosstermError` (which wasn't used) and `ConversionError`.
Closes: #

refactor: clean up conversion and crossterm errors

---

src/canvas.rs
src/data_collection.rs
src/data_collection/cpu/sysinfo.rs
src/data_collection/disks/freebsd.rs
src/data_collection/error.rs
src/data_collection/processes.rs
src/data_collection/processes/linux.rs
src/data_collection/processes/unix.rs
src/data_collection/processes/unix/process_ext.rs
src/data_collection/processes/unix/user_table.rs
src/data_collection/processes/windows.rs
src/main.rs
src/utils/error.rs

Removes the `BottomError::InvalidIo` error type, which was mostly used for data collection and drawing, and updates the use sites.
Closes: #

refactor: migrate data collection and some others away from BottomError

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md
desktop/bottom.desktop
schema/v1.0/bottom.json

Because of https://github.com/ClementTsang/bottom/issues/1500 I had to hotfix 0.9.7 in; this just updates the changelog to match the `release` branch.
Closes:#1500
Closes: #

uptick: 0.9.7

---

Cargo.toml
src/canvas/widgets/battery_display.rs

#1500 made me realize I actually don't really need to pull in `time` as a root dependency anymore; I was mostly just using it for local log debugging and just to avoid converting seconds to h/m/s.
This PR makes it so we are only using it for local log debugging.
Closes: #

refactor: remove time as a dependency outside of logging

---

docs/content/configuration/config-file/styling.md
sample_configs/default_config.toml
schema/nightly/bottom.json
src/constants.rs
src/options/config/style.rs
src/options/config/style/battery.rs
src/options/config/style/cpu.rs
src/options/config/style/graphs.rs
src/options/config/style/memory.rs
src/options/config/style/network.rs
src/options/config/style/tables.rs
src/options/config/style/utils.rs
src/options/config/style/widgets.rs
tests/valid_configs/styling.toml
tests/valid_configs/styling_2.toml

Support a "simple" version of text styling configs if users just want to set the foreground colour like before. For example:
```toml
[styles.widgets]
selected_text = "#fff"
```
Note that this is just an enum; if the user wants to get more fancy, they still can, as per the recent change:
```toml
[styles.widgets]
headers = { color = "red", bg_color = "black", bold = true }
```
Closes: #
_If relevant, ensure the …

feature: support simple colour settings for text fields too

---

CHANGELOG.md
src/options/config/style/utils.rs

Support bold text as a styling configuration option.
Closes: #556 

feature: support bold text

---

CHANGELOG.md
sample_configs/default_config.toml
src/constants.rs
src/options/config/style/themes/default.rs
src/options/config/style/themes/gruvbox.rs
src/options/config/style/themes/nord.rs

Makes table headers bold by default. For example:
Closes: #

change: make table headers bold by default

---

CHANGELOG.md
schema/nightly/bottom.json
src/options/config/style.rs
src/options/config/style/utils.rs
tests/valid_configs/styling.toml

Support italics as a text styling option. For example:
Closes: #

feature: support italic text styling

---

src/main.rs

Adds the resolved config path to the error message returned from failed to get or create the config file. E.g.
```console
$ rm -rf ~/.config/bottom
$ chmod -w ~/.config
$ c r
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.09s
Running `target/debug/btm`
Error: Unable to parse or create the config file at: /home/cosmic/.config/bottom/bottom.toml
Caused by:
Error with the config file or the arguments: Permission denied (os error 13)
```
The motivation was that I was showing `btm` to a friend, but it was failing to run on their computer due to some cursed issues on their home folder: however, the specific path …

refactor: Add the config path to the error message

---

docs/content/configuration/config-file/flags.md

The docs set the colour theme as a config flag, but we moved colours to `styles.theme` so that's invalid.
Closes: #

docs: fix invalid flag in docs

---

.cirrus.yml
.gitignore
scripts/cirrus/release.py

Auto-cancel the previous job if it took too long.
Closes: #
Tested with https://github.com/ClementTsang/bottom/actions/runs/10209950184

ci: some more cirrus release tweaks

---

CHANGELOG.md
src/data_collection.rs

Looks like I wasn't updating processes correctly for sysinfo sources. This impacted macOS and Windows at the very least.
Closes: #1538

bug: fix not updating sysinfo processes correctly

---

docs/content/usage/widgets/process.md
docs/requirements.txt

docs: update docs and requirements as of 2024-08-05

---

CHANGELOG.md
src/data_collection/processes/unix/process_ext.rs
src/data_collection/processes/windows.rs

Seems like on other platforms, sysinfo will sometimes report a run time that starts from UNIX epoch - this gives a non-sensical value of 19000+ days, and it at least looks a little more reasonable to just return 0 in this case. I guess we can also make it return N/A in the future but this is a quick fix for now.
Closes: #

bug: fix occasionally wrong run time reported by sysinfo

---

sample_configs/default_config.toml
src/constants.rs
tests/valid_configs/filtering.toml

The filters didn't have their parent section names, and were parsed as top-level items.
Filters not working.

fix: missing parent section names in TOML

---

src/constants.rs
src/options/config.rs
src/options/config/cpu.rs
src/options/config/disk.rs
src/options/config/flags.rs
src/options/config/ignore_list.rs
src/options/config/layout.rs
src/options/config/network.rs
src/options/config/process.rs
src/options/config/style.rs
src/options/config/style/battery.rs
src/options/config/style/cpu.rs
src/options/config/style/graphs.rs
src/options/config/style/memory.rs
src/options/config/style/network.rs
src/options/config/style/tables.rs
src/options/config/style/widgets.rs
src/options/config/temperature.rs

Adds an additional test to ensure that the default config is valid TOML, as well as actually catch a typo in the default config.
This also adds scaffolding to check if it _matches_ the default config, but currently the way we do that internally is a _bit_ of a hack so I didn't actually enable the assert (as it fails). I'll handle that in another PR as I refactor some things like the internal layout.
Closes: #
_If …

other: add test to validate default config, fix typo in default config

---

src/constants.rs
src/data_conversion.rs
src/main.rs
src/utils/cancellation_token.rs

refactor: clean up some config and panic code

---

src/app/filter.rs
src/data_collection/disks.rs
src/data_collection/network/sysinfo.rs
src/data_collection/nvidia.rs
src/data_collection/temperature.rs
src/data_collection/temperature/linux.rs
src/data_collection/temperature/sysinfo.rs
src/options.rs

Something that I noticed; if we do see GPUs but can't get the temp, it's probably fine to return N/A rather than no entry at all.
Possibly related to #1554?

other: show N/A for Nvidia GPUs if we detect one but can't get temps

---

schema/nightly/bottom.json
src/constants.rs
src/options.rs
src/options/args.rs
src/options/config/flags.rs
tests/integration/arg_tests.rs

Rename `flags.enable_gpu` to `flags.disable_gpu` and make it `false` by default
Closes: #1554

refactor: rename `flags.enable_gpu` to `flags.disable_gpu` (`false` by default)

---

src/canvas.rs

With the new average CPU row there's a bug where the widget wouldn't fix the height accordingly if the average gauge wasn't already on a new line, causing cores on any system core count isn't divisible by 4 to be cut off.
This is a screenshot of my 14c Macbook Pro having cores cut off before the fix.
And here's after the fix on a 16c32t system and the same 14c mac
Tested by enabling `average_cpu_row` on a system where the core count wasn't divisible by 4 to the UI bug was fixed and by doing the same on a system where the core count is divisible by 4 to ensure there's no breakage.

fix: avg cpu row incorrect height

---

CHANGELOG.md
docs/content/configuration/config-file/index.md
src/options.rs
src/options/config/style.rs

Actually support `$XDG_CONFIG_HOME` on macOS. Apparently in our docs we also say we do, but we, uh, don't, because `dirs` doesn't.
Note this is backwards-compatible, in that if a config file exists in the old default locations, we will check those first.
Closes: #1569 

change: default config location on macOS considers `$XDG_CONFIG_HOME`

---

.cirrus.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/nightly.yml
src/app/data_farmer.rs

Ideally we minimize our usage of Cirrus CI, especially for typical PR CI workflows, since it's a bit cludgy to work with. This method is also more extendable to things like OpenBSD.
Fine for deploys I guess since that's not super frequent and at this point I have that working fairly well when automated + I don't usually have to wait for it.
Closes: #

ci: try using GHA instead of Cirrus for FreeBSD in basic CI

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/nightly.yml

Merges the two together as one step as it doesn't really make sense to separate the two.
Closes: #

ci: merge mock + init job in nightly

---

.github/workflows/ci.yml
README.md

docs: update README

---

README.md

As per [the changelog](https://github.com/ClementTsang/bottom/blob/d20dc49c95e085dd2ba3aa2b699c5a830ea9753a/CHANGELOG.md?plain=1#L90), `--color` was replaced by `--theme`. This updates the screenshot comment in the README to reflect this change.

Update reference to "--color" to say "--theme" instead

---

CHANGELOG.md
src/canvas/components/tui_widget/time_chart.rs
src/options.rs

Parse `"none"` when checking legend position in configs. This was being done in args but not config for whatever reason.
Closes: #1591

bug: fix using 'none' for chart legend position in configs

---

CHANGELOG.md
Cargo.lock
Cargo.toml
sample_configs/default_config.toml
src/constants.rs
src/options.rs
tests/integration/util.rs
tests/integration/valid_config_tests.rs

I had changed how this was parsed in-code but I forgot to update the default configs. This also adds some e2e tests to hopefully catch this all for real in the future, since the schema ones don't catch this stuff and the constants test doesn't actually run the binary for a proper e2e test.
From a discussion in https://github.com/ClementTsang/bottom/discussions/1592
_If relevant, ensure the following have been …

bug: fix incorrect default config definitions for chart legends

---

src/data_collection/disks/unix/file_systems.rs

Fix the problem that the nilfs2 file system partition is not displayed in the disk list.
Related discussions: #1595

bug: fix support for nilfs2 file system

---

Cargo.toml
build.rs
src/app/data_farmer.rs
src/app/layout_manager.rs
src/canvas/components/data_table.rs
src/data_collection/disks/freebsd.rs
src/data_collection/disks/unix/file_systems.rs
src/data_collection/disks/unix/linux/partition.rs
src/data_collection/disks/unix/macos/io_kit/bindings.rs
src/data_collection/disks/unix/other/partition.rs
src/data_collection/disks/unix/usage.rs
src/data_collection/processes/linux.rs
src/data_collection/processes/macos/sysctl_bindings.rs
src/main.rs
src/options.rs

A simple PR that bumps the unofficial MSRV to 1.81. This allows us to update some std code usage that is deprecated and use `expect` to replace `allow` for lints, which also caught some bad `allow` usages.
Closes: #

refactor: bump 'msrv' to 1.81 and update deprecated code

---

Cargo.lock
Cargo.toml
src/canvas.rs
src/canvas/components/tui_widget/pipe_gauge.rs
src/canvas/components/tui_widget/time_chart.rs
src/canvas/components/tui_widget/time_chart/canvas.rs
src/canvas/components/widget_carousel.rs
src/canvas/dialogs/dd_dialog.rs
src/canvas/dialogs/help_dialog.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/cpu_basic.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/mem_basic.rs
src/canvas/widgets/mem_graph.rs
src/canvas/widgets/network_basic.rs
src/canvas/widgets/network_graph.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temperature_table.rs

Following https://github.com/ratatui/ratatui/blob/main/CHANGELOG.md#0280---2024-08-07 and https://github.com/ratatui/ratatui/blob/main/BREAKING-CHANGES.md as a precursor to bumping to 0.29. This only bumps the versions + fixes any breakages, and not integrating any improvements at the moment.
Closes: #

deps: bump to ratatui 0.28

---

src/app.rs
src/app/states.rs
src/options.rs
src/widgets/process_table.rs
src/widgets/process_table/proc_widget_column.rs
src/widgets/process_table/proc_widget_data.rs
src/widgets/process_table/query.rs

Some renames and file movement. No functional changes.
Closes: #

refactor: quick variable/struct/file rename

---

CHANGELOG.md
sample_configs/default_config.toml
schema/nightly/bottom.json
scripts/schema/validator.py
src/app/data_farmer.rs
src/canvas/components/data_table/sortable.rs
src/constants.rs
src/data_conversion.rs
src/main.rs
src/options.rs
src/options/config/cpu.rs
src/options/config/disk.rs
src/options/config/network.rs
src/options/config/process.rs
src/options/config/temperature.rs
src/widgets/cpu_graph.rs
src/widgets/disk_table.rs
src/widgets/process_table/process_columns.rs
tests/integration/invalid_config_tests.rs
tests/invalid_configs/invalid_disk_column.toml
tests/valid_configs/theme.toml

Adds the ability to specify the process widget's columns.
For example, specifying all valid columns:
```toml
[disk]
columns = ["disk", "mount", "used", "free", "total", "used%", "r/s", "w/s"]
```
Or:
```toml
[disk]
columns = ["disk", "mount", "w/s", "r/s", ]
```
Also a bunch of internal cleanups/refactoring.
Closes: #1480

feature: add the ability to configure the disk widget's table columns

---

Cargo.toml
scripts/schema/generate.sh
src/bin/main.rs
src/bin/schema.rs
src/data_collection/processes/windows.rs
src/lib.rs
src/options.rs
src/options/args.rs
src/options/config.rs
src/options/config/disk.rs
src/options/config/style.rs
src/options/config/style/themes.rs
src/options/config/style/themes/default.rs
src/options/config/style/themes/gruvbox.rs
src/options/config/style/themes/nord.rs
src/options/config/style/utils.rs
tests/integration/valid_config_tests.rs

Decided it might be nicer to separate the schema generation bit to its own binary. This does mean that we have to go back to the lib-bin system, as otherwise passing shared code is _really_ hard.
Closes: #

refactor: move schema generation to its own binary, go back to lib-bin

---

src/options/config/style.rs
src/options/config/style/themes/default.rs
src/options/config/style/themes/gruvbox.rs
src/options/config/style/themes/nord.rs

Fix incorrectly selected colours for gruvbox-light theme after the refactor in #1499. Example:
Closes: #1631

bug: fix incorrect colours for gruvbox-light

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/post_release.yml
.github/workflows/test_docs.yml
.github/workflows/validate_schema.yml

ci: clean up CI, update python action + version

---

.cirrus.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/nightly.yml
scripts/cirrus/release.py

I would love to migrate off cirrus just to make things easier. Also update macOS targets since macOS-12 is deprecated, and fixes a bug regarding nightly mocks.
Closes: #

ci: migrate FreeBSD release builds to GHA, update macOS and FreeBSD targets

---

Cargo.lock
Cargo.toml
src/data_collection/amd.rs
src/utils/logging.rs

deps: bump root deps as of 2024-12-20

---

README.md

Bad pratice to use sudo with a aur helper on arch linux
Avoid using sudo for AUR helper
Closes: #
No test
A test nothing, just remove 2 word on the README.md

Remove sudo on Readme for Yay and Paru

---

src/app.rs
src/app/data_farmer.rs
src/canvas.rs
src/canvas/drawing_utils.rs
src/canvas/widgets.rs
src/canvas/widgets/battery_display.rs
src/data_collection.rs
src/data_collection/amd.rs
src/data_collection/batteries.rs
src/data_collection/memory.rs
src/data_collection/memory/arc.rs
src/data_collection/memory/sysinfo.rs
src/data_collection/nvidia.rs
src/data_conversion.rs
src/lib.rs

Another small PR to clean up some data conversion code.
Next PR will probably try to dedupe some `Point` code since that's a pretty bad waste of memory.
Closes: #

refactor: more data conversion cleanup

---

src/data_collection/nvidia.rs

Recently, NVIDIA CUDA repository packages started shipping only `libnvidia-ml.so.1` file, without `libnvidia-ml.so`. The upstream `nvml-wrapper` package has a fix proposed (https://github.com/Cldfire/nvml-wrapper/pull/63), yet the package is in search of a maintainer at the moment and the PR is not getting merged.
To allow `bottom` to correctly detect NVIDIA GPUs on Ubuntu with official NVIDIA packages, add a wrapper around `Nvml::init` to be more persistent in its search for the NVML library.
Note: I don't see a reason why we can't try looking for `libnvidia-ml.so.1` on non-Linux systems, thus simplifying the code. But I don't have a non-Linux machine with an NVIDIA GPU around to make sure this is indeed the case and nothing weird happens. The extra platform-specificity is, admittedly, …

other: handle systems with only libnvidia-ml.so.1

---

src/app/data_farmer.rs

On macOS we use an additional regex to check some things in disk; we initialize it using a `static OnceLock`, so despite it being in a loop, which causes clippy to think there's a problem, this doesn't actually pose a problem as it'll only ever be created once.
Proof: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=452c49b24c0a86787afcc2a407ac9f68
Closes: #
_If relevant, ensure the …

other: fix non-applicable warning about regex creation in loop

---

CHANGELOG.md
src/bin/main.rs
src/lib.rs

Looks like the panic hook doesn't get hit if `main` exits with an `Err`. This adds a catch for this scenario.
Tested by inserting a `bail!` into the main loop and seeing how it reacts.
Closes: #

bug: handle terminal cleanup if main.rs panics from an `Err`

---

build.rs
docs/content/contribution/packaging-and-distribution.md

This change simply makes it possible to optionally specify `COMPLETION_DIR` or `MANPAGE_DIR` via environment variables to specify the location where completion and manpage files are created. This is especially handy when using `cargo install` and is a similar approach used by [hyperfine](https://github.com/sharkdp/hyperfine/blob/master/build.rs).
This also makes sure the docs align with the implementation as **build_process.md** states the following:
> - Build a release build with:
> 
>   - `--features deploy`, which enables only crates needed for release builds.
>   - `--locked` to lock the dependency versions.
>   - The following env variables set:
> 
>     - `BTM_GENERATE: true`
>     - `COMPLETION_DIR: "target/tmp/bottom/completion/"`
>     - `MANPAGE_DIR: …

feature: make it possible to override generate dirs via env

---

.github/workflows/build_releases.yml
.github/workflows/post_release.yml
Cargo.toml
wix/main.wxs

pkg: add completion files to winget/msi installer

---

src/app/data/time_series.rs
src/canvas/widgets/network_graph.rs
src/widgets/network_graph.rs

This PR has two changes:
1. Fix a bug where we were using the wrong value when creating network y-axis labels; this was a mistake from #1663, where I used the upper limit (value * 1.5) as the value to create labels. Oops.
2. Cache previous results of height calculation; this means we don't have to always scan the full range of points each time we want to find the max height for the adjusting y-axis. Instead:
- If the cache is empty, scan the full range; store the best point, the right edge scanned, and the time range
- If the cache is not empty, and the point is inside the current range, scan from the right edge to the …

fix/other: fix bug with network y-axis labels and cache height calculations

---

src/app/data/store.rs
src/app/data/time_series.rs
src/canvas/widgets/mem_basic.rs
src/canvas/widgets/mem_graph.rs
src/collection.rs
src/collection/amd.rs
src/collection/memory.rs
src/collection/memory/arc.rs
src/collection/memory/sysinfo.rs
src/collection/nvidia.rs

Given that if total memory is 0 that usually indicates we should treat things specially, we can take advantage of `NonZeroU64` instead for better semantics.
Closes: #

refactor: use nonzero in mem data

---

README.md

This commit contains the following changes:
1. Corrects the source of the package in the Nix instructions: `bottom` isn't coming from `nix-community`, but Nixpkgs itself.
2. Updates the Nix install instructions to use the new Nix CLI.
3. The original link was pointing to a home-manager module for bottom. We now include instructions on how to enable said module.
Not an issue, but this is a follow-up to #294.
I... checked the rich preview in GitHub and it seems fine. It's just a README change.

README: update Nix install instructions

---

CHANGELOG.md
src/collection.rs
src/collection/amd.rs
src/collection/amd/amd_gpu_marketing.rs
src/collection/linux/utils.rs
src/collection/temperature.rs
src/collection/temperature/linux.rs

We were pulling the AMD GPU temps twice, so this fixes that. This also avoids checking AMD GPU details if the card is asleep.
This change also capitalizes the first letter of temp labels.
Closes: #
Looks fine to me:

refactor: don't duplicate AMD GPU temperature retrieval

---

src/canvas/components/time_graph/time_chart.rs

Currently, when some entries in a graph's legend are shorter than others, it's possible for the graph lines to show up through the legend. This can be seen in the following screenshot:
This pull request fixes the issue. In terms of how the fix is actually implemented, I'm not that familiar with ratatui so lmk if there's a better way to ensure the legend is fully opaque.
N/A
I visually examined the graphs to confirm that the bug no longer appears.

fix: prevent graph lines from showing up behind legend

---

CHANGELOG.md

docs: Update CHANGELOG.md for #1683

---

docs/content/contribution/documentation.md
docs/mkdocs.yml

Noticed this when doing https://github.com/ClementTsang/bottom/pull/1703
Closes: #

docs: use local link in docs to reference itself & missing CPU config

---

src/lib.rs

Looks like a bug slipped through in #1706 so when stopping the program click events would continue. I could just fix the condition but I think it's fine to just unconditionally disable click events on cleanup.
Closes: #

bug: fix incorrect disable mouse click condition on cleanup

---

desktop/bottom.desktop

The current desktop file caused an error and a hint from `desktop-file-validate` 0.28.
```console
> desktop-file-validate bottom.desktop
bottom.desktop: error: value "0.10.2" for key "Version" in group "Desktop Entry" is not a known version
bottom.desktop: hint: value "Utility;System;ConsoleOnly;Monitor;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
```
Especially, this error becomes a blocker when adding local patches for issues like https://github.com/ClementTsang/bottom/issues/1447. Because of `desktop-file-edit` also reports the same validation error.
This PR addresses those issues:
- The "Version" field must be empty or a desktop entry specification version (e.g., `1.0`, `1.5`), not …

bug: fix invalid values in desktop file

---

CHANGELOG.md
src/collection/disks/unix/linux/partition.rs

Turns out that in /proc/mount disk names may have weird escape characters, which led to incorrect path names, causing problems - these need to be changed when parsing it.
Closes: #

bug: fix parsing issue around certain disk names

---

src/canvas/components/data_table.rs

Current implementation refuses to paginate (e.g. page up) if there isn't enough rows. This is only an issue for widgets. (Pagination works just fine for help menu or kill process menu.)
This PR fixes the issue so that pagination behaves as one would expect.
Closes: #

bug: fix increment for data tables if the change is greater than the number of entries left

---

.github/ISSUE_TEMPLATE/bug_report.yml
README.md

This reverts commit 4416cf6b29701a67b093678e60e005de74c9642c.
Didn't mean to merge this yet -_-
Closes: #

docs: revert 0.11.0 docs change

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docs/content/usage/widgets/memory.md
src/collection/memory.rs
src/collection/memory/sysinfo.rs
src/collection/memory/windows.rs

This PR changes how we calculate swap in Windows.
Previously, we used sysinfo's [API](https://github.com/GuillaumeGomez/sysinfo/blob/master/src/windows/system.rs#L163), which calculates based on committed page values pulled by `GetPerformanceInfo`. This is a entirely valid way to interpret what "swap" is - however, this disagrees with what Windows reports using its performance counters (also task manager reports its own thing, we can add stuff like committed/virtual memory later).
We instead write our own swap function for Windows that copies what is done by psutil [here](https://github.com/giampaolo/psutil/pull/2160), …

other: change how we calculate swap usage in Windows

---

src/options.rs
src/options/config/disk.rs

I configured `[disk.name_filter]` and after upgrading to v0.11.0, the
disk widget became empty since `disk.columns` was parsed as an empty
vector unless I added `disk.columns` to my config as well.
N/A
Using a config like:
```toml
[disk]
[disk.name_filter]
is_list_ignored = true
list = ["^tank.*@"]
regex = true
case_sensitive = true
whole_word = false
```
v0.11.0 renders an empty disk widget. This PR uses the default disk
widget columns.

fix: use default disk.columns when only other disk.* configs exist

---

Cargo.lock
Cargo.toml
src/collection.rs
src/lib.rs
src/options.rs

Don't think we need this anymore; this also bumps sysinfo and cleans up some things.
May help with #1777.

other: skip the initial sleep on data collection initialization

---

README.md

Hello,
this PR adds to the documentation the installation method using [gah](https://github.com/marverix/gah/):
> gah is an GitHub Releases app installer, that DOES NOT REQUIRE SUDO! It is a simple bash script that downloads the latest release of an app from GitHub and installs it in ~/.local/bin. It is designed to be used with apps that are distributed as a single binary file.

docs: Add installation with gah

---

CHANGELOG.md
src/collection/processes/linux/mod.rs
src/collection/processes/linux/process.rs

This fixes an issue in Linux where some process names that ended with `':'` would appear when they shouldn't.
Note this is kinda an interim fix; turns out I misunderstood some things about comm/cmdline/basenames which I will address later.
Closes: #

bug: fix colon at end of process name for now on Linux

---

sample_configs/default_config.toml
src/canvas.rs
src/canvas/widgets/cpu_basic.rs
src/constants.rs

The basic mode cpu widget after 0.11.0 shows the AVG CPU entry in the core bars and the dedicated row when `hide_avg_cpu = false` and `average_cpu_row = true`. This was not the behaviour with 0.10.2. It is caused by an off by 1 error resulting in a core being hidden too(core 15 in screenshot). This change uses the index to skip the AVG in the `cpu_data`, includes `hide_avg_cpu` and updates the configuration for `average_cpu_row`.
Screenshot: Top is nightly with bug, bottom is this PR fixed
Ran on linux in basic mode with `hide_avg_cpu` and `average_cpu_row` set to true/false.

bug: skip avg cpu in basic mode with dedicated row

---

src/collection/processes.rs
src/collection/processes/linux/mod.rs
src/collection/processes/unix/process_ext.rs
src/collection/processes/unix/user_table.rs
src/collection/processes/windows.rs
src/widgets/process_table.rs
src/widgets/process_table/process_columns.rs
src/widgets/process_table/process_data.rs
src/widgets/process_table/query.rs

This tries to reduce the number of string clones when collecting usernames, by storing them in a `Option<Arc<str>>` up until we display them.
Closes: #

refactor: optimize username cloning for Unix processes
