ClementTsang/bottom

.github/pull_request_template.md
Cargo.toml
README.md
rustfmt.toml
src/app.rs
src/canvas.rs
src/canvas/drawing_utils.rs
src/main.rs

Fixes the cursor bug within the scrollbar.
Closes: #41 
Tested on Arch Linux, Kitty.  Tested by using a variety of unicode characters (CJK as well).

Fix cursor screen bug

---

src/data_conversion.rs

Removes the rounding on RAM, since it seems unneccesary.
Closes: #
Tested to not cause regressions on Arch and macOS.

Remove RAM rounding

---

src/app.rs
src/main.rs

Change all of update rate to u128.
Closes: #
N/A.  No effect, still builds.

Make update rate u128 across the board.

---

.travis.yml
Cargo.toml
README.md
src/canvas.rs
src/main.rs

Fixes a typo and ran rustfmt on everything again.
Closes: #
N/A

Formatting and typos

---

README.md
src/app.rs
src/app/data_harvester/network.rs
src/canvas.rs
src/canvas/drawing_utils.rs
src/constants.rs

Does three main things:
- Scroll label now truncates at smaller widths
- Temporary fix for help dialog being too small
- Kinda? (it's mostly fine) temporary fix for dd dialog being too small
Closes: #61 
Tested on Arch Linux and macOS to still work with no regressions.

Fix dialog box height and scroll label

---

src/app.rs
src/main.rs

Fixes cpu legend scrolling potentially being off screen due to how we determined scroll bar positioning and hiding cores conflicting.
Closes: #77 
Tested on Arch Linux, Kitty, to fix the problem.

Fix cpu scroll

---

README.md
src/main.rs

Update docs a bit more and remove an errant debug line.
Closes: #

(docs): Updates docs and removes a debug

---

README.md
src/app.rs
src/app/data_harvester.rs
src/app/data_harvester/disks.rs
src/app/data_harvester/mem.rs
src/app/data_harvester/network.rs
src/app/data_harvester/temperature.rs
src/app/layout_manager.rs
src/main.rs
src/options.rs

If using modularity, avoid redundant harvesting and steps.
Closes: #
Tested to still run on Linux.

(perf) Avoid harvesting if widget is not being displayed

---

Cargo.toml
src/app/data_harvester/network.rs

Updates two dependencies
Closes: #
Compiles, doesn't seem to cause obvious breakage.

deps: Upgrade crossterm and sysinfo

---

clippy.toml
src/app.rs
src/canvas/widgets/process_table.rs

Removes all but one cognitive complexity warning from clippy, also removes the clippy.toml as it's not needed.
Closes: #

refactor: Deal with some cognitive complexity

---

src/app.rs
src/canvas/widgets/process_table.rs

Fixes sizing in search and tab logic being invalid for the proc widget.
Closes: #

bug: Fix sizing in search and broken tab logic

---

CHANGELOG.md
README.md
src/app.rs
src/app/data_harvester.rs
src/app/data_harvester/processes.rs
src/canvas/widgets/process_table.rs
src/data_conversion.rs
src/main.rs

Adds I/O per process to process widget.
Closes: #58 

feature: add io and io/s for processes

---

CHANGELOG.md
src/app.rs

Cause was using the wrong interable length when checking for whether the cursor position was valid (was using the map's length).
Closes: #

bug: Fix dd failing on non-first entries

---

src/app.rs
src/canvas.rs
src/canvas/dialogs/help_dialog.rs
src/constants.rs
src/main.rs
src/options.rs

Minor refactoring of how we manage help text.
Closes: #

refactor: changed how we set help text on resize and init

---

Cargo.lock
src/app/data_harvester/battery_harvester.rs
src/canvas/widgets/battery_display.rs
src/data_conversion.rs

Adds battery health% as well to the list.
Closes: #

feature: add battery health percentage

---

CHANGELOG.md
README.md
src/constants.rs

Updates documentation for keybindings within help and README.
Closes: #

docs: update help and README for bindings

---

src/constants.rs

I'm fairly certain this was supposed to read processor usage instead of another memory usage.

Fix help (sort by cpu)

---

CHANGELOG.md
Cargo.lock
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/mem_graph.rs
src/canvas/widgets/network_graph.rs

Now that the fix for empty data is patched in tui, these checks are redundant.
Closes: #

refactor: remove redundant empty checks in graphs

---

.vscode/settings.json
CHANGELOG.md
README.md
src/constants.rs
src/main.rs

Update documentation and program to use the correct config directory as per the dirs package.
Closes: #

Update macOS config dir

---

CHANGELOG.md
src/app.rs

Fixes a bug caused by hitting enter w/ dd when it fails
Closes: #

Fixes a bug caused by hitting enter w/ dd when it fails

---

.travis.yml
.vscode/settings.json
deployment/linux/arch/PKGBUILD.template
deployment/linux/arch/PKGBUILD_BIN.template
deployment/macos/homebrew/bottom.rb.template
deployment/packager.py
deployment/windows/choco/bottom.nuspec.template
deployment/windows/choco/choco_packager.py
deployment/windows/choco/chocolateyinstall.ps1.template

Automatically builds packages for AUR, chocolatey, and homebrew on release.
Closes: #23 

ci: Automatically build package files on release

---

.github/workflows/deploy.yml
CONTRIBUTING.md
Cargo.toml
src/bin/main.rs
src/lib.rs
src/options.rs
tests/layout_management_tests.rs
tests/widget_movement_tests.rs

Refactor code so we use a lib, allowing for easier testing.  Adds additional tests for layouts.
Closes: #

refactor: Refactor code, add new tests

---

src/app.rs
src/app/data_harvester/processes.rs
src/app/query.rs
src/app/states.rs
src/canvas.rs
src/canvas/widgets/process_table.rs
src/data_conversion.rs
src/lib.rs

Fixes grouping not working properly after some refactoring done in 0.4.6.
Closes: #

bug: fix grouping being broken after refactor

---

deployment/linux/arch/PKGBUILD.template
deployment/macos/homebrew/bottom.rb.template

Mainly missing some `cd` lines in AUR builds and clarifying the macOS config location.
Closes: #

ci: minor CI fixes for automatic deploys

---

.all-contributorsrc
.vscode/settings.json
CHANGELOG.md
README.md
src/app.rs
src/app/layout_manager.rs
src/app/states.rs
src/bin/main.rs
src/canvas.rs
src/canvas/dialogs/help_dialog.rs
src/canvas/widgets/basic_table_arrows.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/cpu_basic.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/mem_basic.rs
src/canvas/widgets/mem_graph.rs
src/canvas/widgets/network_basic.rs
src/canvas/widgets/network_graph.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temp_table.rs
src/lib.rs
src/options.rs
tests/layout_movement_tests.rs

Adds mouse support to the application, to move between widgets and click on elements.
List of things to do/added:
Closes: #162 

feature: Add mouse click support for moving between widgets

---

.vscode/settings.json
CHANGELOG.md
README.md
src/clap.rs

Some more updates to arguments and documentation.
Closes: #

docs: Update some arguments, and documentation

---

.travis.yml

Fixes a bug with CI for armv7 builds.
Closes: #

ci: Fix missing equals sign

---

.cargo/config.toml
.github/ISSUE_TEMPLATE/bug_report.md
.travis.yml
.vscode/settings.json
deployment/windows/choco/bottom.nuspec.template

Some Windows compilation/deploy stuff.  Mostly just a catch-all for some chores.
Closes: #

other: Windows compilation stuff

---

.vscode/settings.json
clippy.toml
src/app.rs
src/app/data_farmer.rs
src/app/data_harvester/cpu.rs
src/app/data_harvester/disks.rs
src/app/states.rs
src/bin/main.rs
src/canvas.rs
src/canvas/drawing_utils.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/network_graph.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temp_table.rs
src/constants.rs
src/data_conversion.rs
src/lib.rs

Update how we position and generate column widths to look less terrible... I think.
For example, left is old, right is new:
This also adds truncation w/ ellipsis to the columns!
And, for processes, the state will automatically shrink to a short form (just a character) if there isn't enough space:
Closes: #225 

refactor: rewrite column algorithm

---

src/app/data_harvester.rs
src/app/data_harvester/disks.rs
src/app/data_harvester/mem.rs
src/app/data_harvester/network.rs
src/app/data_harvester/processes.rs
src/app/data_harvester/temperature.rs
src/canvas/widgets/process_table.rs

Just a simple rename.
Closes: #

refactor: rename data harvesting fns to what archs/oses they support

---

.travis.yml
.vscode/settings.json
CHANGELOG.md
Cargo.lock
Cargo.toml

Update to tui-rs, which fixes #255, as well as some miscellaneous things like updating changelogs and travis.
Closes: #255 
Update to dependencies.

bug: fix chart and data point overlap

---

README.md
src/app.rs
src/app/data_farmer.rs
src/app/data_harvester.rs
src/app/layout_manager.rs
src/bin/main.rs
src/clap.rs
src/lib.rs
src/utils/logging.rs

Adds a `--debug` flag to aid in debugging issues.  This saves to `/tmp/bottom_debug.log`.
Closes: #

feature: add --debug flag for logging

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/app/data_harvester.rs
src/bin/main.rs
src/clap.rs
src/lib.rs

Minor update to update some dependencies and remove some traces.
Closes: #

other: more traces to debug, update some deps

---

.travis.yml

Test against PowerPC64 LE CPU
N/A
N/A

[travis] Add ppc64le pipeline

---

Cargo.lock
Cargo.toml

Updates dependencies to their most recent versions as of Nov 02, 2020.
Closes: #
Update dependencies.

deps: update anyhow, crossterm, futures, regex, thiserror, toml

---

.vscode/settings.json
README.md

Adds nix installation instructions.
Closes: #
Documentation update.

docs: Add nix installation instructions

---

README.md

docs: Add Gentoo installation instructions

---

.vscode/settings.json
CHANGELOG.md
README.md
src/app.rs
src/app/states.rs
src/canvas.rs
src/canvas/widgets/process_table.rs
src/clap.rs
src/constants.rs
src/data_conversion.rs
src/lib.rs
src/options.rs

Adds collapsible trees to the tree mode for processes. These can be toggled via the + or - keys and the mouse by clicking on a selected entry.
Closes: #233 

feature: Add collapsible tree entries

---

.github/workflows/post-deploy.yml

ci: Update post-deploy script to include choco

---

.github/workflows/deployment.yml

ci: Update deployment script to also upload to github

---

.github/workflows/ci.yml
.github/workflows/deployment.yml

ci: Fix deployment GitHub Action script

---

.github/workflows/deployment.yml
.github/workflows/post-deploy.yml
README.md

Fixes an issue in the windows deployment action.

ci: Fix windows deployments

---

.github/workflows/deployment.yml
.github/workflows/post-deploy.yml
.vscode/settings.json

Move post deploy

---

.github/workflows/audit.yml
.github/workflows/ci.yml
.github/workflows/deployment.yml
.github/workflows/post-deploy.yml
deployment/windows/choco/choco_packager.py

- Fix bug with choco and homebrew using incorrect bash syntax causing broken downloads.  Why this didn't fail, idk.
- Add tag entry for manual runs to make it easier to deploy/re-run
- Fixed some typos
- Fixed incorrect string in choco python script
Closes: #

ci: Fix some bugs/typos with the deploy script and components

---

Cargo.lock
Cargo.toml

Update dependencies.
Closes: #

deps: update dependencies

---

.vscode/settings.json
Cargo.lock
Cargo.toml
src/app/data_harvester.rs
src/app/data_harvester/disks.rs
src/app/data_harvester/mem.rs
src/app/data_harvester/network.rs
src/app/data_harvester/processes.rs

Refactors the data harvesting system function names.
Closes: #

refactor: Simplify data harvesting

---

.cargo-husky/hooks/pre-push
Cargo.lock
Cargo.toml
src/app/data_harvester.rs
src/app/data_harvester/battery_harvester.rs
src/app/data_harvester/cpu.rs
src/app/data_harvester/disks.rs
src/app/data_harvester/mem.rs
src/app/data_harvester/network.rs
src/app/data_harvester/processes.rs
src/app/data_harvester/temperature.rs

Some other minor refactoring.
Closes: #

refactor: Clean up some parts of data harvesting

---

.github/workflows/ci.yml
FAQ.md
README.md

Adds an FAQ file for some questions.
Closes: #

docs: Add FAQ document

---

src/app/data_harvester/mem.rs
src/canvas.rs

Refactors some canvas code.
Closes: #

refactor: Refactor some canvas code

---

CHANGELOG.md
README.md
src/canvas/drawing_utils.rs
src/canvas/widgets/process_table.rs
src/clap.rs
src/options.rs

Fixes another change breaking states from showing in processes.
Closes: #

bug: Fix missing states in processes

---

.github/workflows/ci.yml
.github/workflows/deployment.yml

Use ubuntu-16.04 for linux gnu deploys and CI.
Closes: #

ci: Use ubuntu-16.04 for linux gnu deploys and CI

---

.github/workflows/deployment.yml
deployment/macos/homebrew/bottom.rb.template

Move from gnu to musl to avoid glibc issues.
Closes: #

ci: Switch to musl for homebrew linux

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

uptick: 0.5.4

---

.gitignore
Cargo.lock
Cargo.toml
src/app/data_harvester.rs
src/app/data_harvester/processes.rs
src/bin/main.rs
src/data_conversion.rs
src/lib.rs

Making some small changes that would hopefully improve performance a bit.
Closes: #

refactor: Another small optimization pass

---

.github/workflows/ci.yml
.github/workflows/deployment.yml
Cargo.toml
src/bin/main.rs
src/lib.rs
src/utils/error.rs
src/utils/logging.rs

refactor: Use feature flags to avoid building with fern and log

---

Cargo.lock
Cargo.toml
src/app/data_farmer.rs
src/app/query.rs
src/bin/main.rs
src/data_conversion.rs
src/options.rs
src/utils/error.rs

- Move data rather than cloning during data transferring step
- Try using beef?
Closes: #

refactor: More minor optimization changes

---

deployment/linux/arch/PKGBUILD.template

ci: Add --no-default-features to PKGBUILD

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

uptick: 0.5.5

---

Cargo.lock
Cargo.toml
src/data_conversion.rs

Updates the following dependencies:
- anyhow to 1.0.35
- typed-builder to 0.8.0
Closes: #

deps: Update various dependencies

---

src/app/data_harvester.rs

Fixed a missing component list refresh, causing macOS and Windows to not properly show sensors.
Closes: #

bug: Fix missing component list refresh

---

CHANGELOG.md
Cargo.toml
src/app/data_harvester.rs
src/app/data_harvester/disks.rs
src/app/data_harvester/mem.rs
src/app/data_harvester/network.rs
src/app/data_harvester/temperature.rs
src/utils/error.rs

Use heim on ARM targets again where appropriate.
Closes: #

refactor: re-use heim for ARM targets if possible

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/app/data_harvester.rs
src/app/data_harvester/network.rs

uptick: 0.5.6

---

Cargo.toml
README.md

other: Turn off debug and turn on LTO in release profile again

---

src/app/data_harvester/processes.rs

Just adds uid and gid collection to the process collection step.  This does not add GUI changes, that'll come later.
Does not close, but affects #236.

feature: Adds uid and gid collection (no GUI yet)

---

.github/workflows/audit.yml
.github/workflows/nightly.yml
.github/workflows/post-deploy.yml

ci: Create nightly build

---

.github/workflows/nightly.yml

ci: Fixes an incorrect action in the nightly build workflow

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/app.rs
src/bin/main.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/network_graph.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temp_table.rs
src/lib.rs

Update some dependencies as per 2021-02-19
Closes: #

deps: Update various deps as per 2021-02-19

---

deployment/macos/homebrew/bottom.rb.template

Adds fish completions to the homebrew template.
Similar fix manually added to existing homebrew .rb file [here](https://github.com/ClementTsang/homebrew-bottom/commit/ee6489bd2f7d162fc73af773b91a8d93f1b6cff3).
Closes: #426

other: Add fish completions to homebrew template

---

.github/workflows/ci.yml

Adds more testing to the ci suite.
Closes: #

ci: Test macOS ARM and Linux armv6

---

.github/workflows/ci.yml
.vscode/settings.json

Adds cache back again via [rust-cache](https://github.com/marketplace/actions/rust-cache).  This should avoid the previous macOS issues with caching.
Closes: #

ci: Add cache back again

---

.vscode/settings.json
Cargo.lock
Cargo.toml
src/app/data_harvester.rs
src/app/data_harvester/processes.rs
src/data_conversion.rs

Switches to fxhash from fnv, which should be a bit faster.
Closes: #

refactor: Switch from fnv to fxhash

---

.github/workflows/nightly.yml
.gitignore
.vscode/settings.json
Cargo.toml
src/data_conversion.rs
src/lib.rs

Refactor to unify the process disk usage -> string into one function.
Closes: #

refactor: Unify disk conversion to string step

---

CHANGELOG.md
src/constants.rs

Removes/tweaks some really light colours that might cause issues with a white background.  For example, yellow on white didn't look so great, so I adjusted the memory/rx colours for this mode.
Closes: #

change: Tweak default light colour scheme

---

src/constants.rs

Adds `nord` and `nord-light` as part of the description.
Closes: #

other: update built-in themes list in config

---

src/canvas/dialogs/help_dialog.rs
src/canvas/drawing_utils.rs

Refactor in regards to clippy nightly.  Mostly deals with suggestions with duplicate code on multiple branches.
Closes: #

refactor: Take clippy nightly suggestions into account

---

Cargo.lock
Cargo.toml
src/app/data_harvester/processes.rs

Did not update crossterm (and tui-rs) since it seems to have resulted in a massive CPU usage increase.  Also fix minor clippy error with a duplicated `to_string` call.
Closes: #

deps: Update dependencies 2021-05-08

---

src/app.rs

Lowers the timer for multi-digit inputs in `dd`.
I'm going to eventually completely rewrite the input part for the entire application though, but this will do for now.
Closes: #

other: lower the timer for multi-digit in dd times

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

Update versions to 0.6.0.
Closes: #

uptick: 0.6.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

uptick: 0.6.1

---

.github/workflows/ci.yml

Moves `cargo test` into the `cargo check` block.
Closes: #

github: move tests ci into check

---

Cargo.lock
Cargo.toml
src/app/data_harvester.rs
src/app/data_harvester/processes.rs
src/utils/error.rs

Switch the Linux proc parts to [the procfs library](https://crates.io/crates/procfs).
Closes: #

refactor: switch to procfs library

---

.github/workflows/nightly.yml

Fixes the mock build capabilities for nightly when testing.
Closes: #

github: fix nightly mocking

---

.github/workflows/ci.yml

Tweak PR CI a bit more.
Closes: #

github: more CI tweaks

---

Cargo.lock
src/app/data_farmer.rs
src/app/data_harvester.rs
src/bin/main.rs
src/lib.rs

Removes some old trace lines for cleanup
Closes: #

refactor: remove old traces

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml

Packages the completion files into a release alongside the other binaries.
Closes: #

ci: distribute completion files separately

---

.github/workflows/docs.yml
README.md

Fix for simple mkdocs deploy action.  I'll likely rewrite this if I add versioning, which I probably will.
Closes: #

ci: fix doc deploy action

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml

Removes the zip dependency for nightly and deploy actions.

ci: remove zip dependency for windows

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/packaging.md
CONTRIBUTING.md
README.md
docs/content/contribution/documentation.md

docs: update old documentation links

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

uptick: 0.6.2

---

.github/workflows/ci.yml
CHANGELOG.md

Update the changelog and add more files to skip CI checks on.

docs + ci: Update changelog and ignore some files in CI

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml
deployment/linux/arch/PKGBUILD.template
deployment/linux/arch/PKGBUILD_BIN.template
deployment/packager.py

Fixes some bugs in CI and updates PKGBUILD for ARM.

ci: update pkgbuilds for ARM, fix bugs

---

.github/workflows/post-release.yml

Adds an additional post-release action to trigger AUR PKGBUILD actions over [here](https://github.com/ClementTsang/aur-bottom).

ci: Add post-release action for AUR repo actions

---

docs/content/troubleshooting.md

Fixes a typo and clarifies a point in a troubleshooting section regarding the braille fonts.

docs: Fix typo and clarify in troubleshooting section

---

Cargo.lock
Cargo.toml
src/app/query.rs
src/options.rs
src/utils/error.rs

Small refactor to remove the beef dependency for now. 
This is likely just a tempoary change, I wanted to remove it just for clarity's sake among dependencies, and will probably add it back in the future.
For now I'll just stick to std's beef.

refactor: remove beef dependency for now

---

docs/content/configuration/config-file/flags.md
src/clap.rs

bug: scaling -> scale in some docs, help, and config

---

CHANGELOG.md
README.md

Uptick README and documentation to 0.6.3.

uptick: 0.6.3

---

docs/content/configuration/config-file/data-filtering.md

Fixes broken links in the documentation site.
Closes: #552 

docs: fix broken image link in data filtering

---

.github/workflows/deployment.yml
deployment/windows/winget/get_product_code.ps1
deployment/windows/winget/product_code.py
deployment/windows/winget/winget.yaml.template

Adds a `ProductCode`, `Scope`, and `Commands` field to the template, as well as additional changes to the deploy process to determine + fill in the `ProductCode` automatically.
Tested on a mock action ]workflow](https://github.com/ClementTsang/bottom/actions/runs/1054620404).

ci: update winget template + deploy for more info

---

sample_configs/default_config.toml

Update the default config file example in the repo as of 2021-07-25.

other: update default config file

---

.github/workflows/ci.yml
.github/workflows/deployment.yml
.github/workflows/nightly.yml

More usage of the caching action to CI/deploy.  Seems to save ~3-4 minutes on CI, not sure about deploy.

ci: add caching to more jobs

---

.github/workflows/ci.yml
.github/workflows/deployment.yml
.github/workflows/nightly.yml
docs/content/support.md
src/app.rs
src/app/data_harvester.rs
src/app/data_harvester/cpu/heim/mod.rs
src/app/data_harvester/network/heim.rs
src/app/data_harvester/network/sysinfo.rs
src/app/data_harvester/processes/linux.rs
src/app/states.rs
src/canvas.rs
src/canvas/widgets/mem_graph.rs
src/canvas/widgets/network_graph.rs
src/canvas/widgets/process_table.rs
src/lib.rs
src/options.rs

Adds CI actions and documentation for RISC-V.
Related to #564

Add RISC-V to unofficially supported targets

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

uptick: 0.6.4

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml
.github/workflows/post-release.yml

Disables homebrew CI file generation, since it's now handled by separate maintainers! See https://github.com/ClementTsang/bottom/pull/578 for some more details.
See https://github.com/ClementTsang/bottom/actions/runs/1252315120

ci: disable homebrew auto-gen

---

.github/workflows/nightly.yml

Fixes a missing step in nightly generation.
Nightly: https://github.com/ClementTsang/bottom/actions/runs/1272301139

ci: add missing step for compressing completion files

---

.github/workflows/nightly.yml

Disables an unnecessary use of cross for i686 Windows, and add multilib for i686 Linux since apparently that's needed now.
Mock nightly run here: https://github.com/ClementTsang/bottom/actions/runs/1301286196

ci: Disable cross for i686 Windows, add multilib for i686 Linux for Nightly

---

.github/workflows/nightly.yml

Reverts #592, this was done incorrectly, I changed the wrong thing and I also didn't need to change said thing.
Mock run: https://github.com/ClementTsang/bottom/actions/runs/1301336241

ci: revert previous i686 change

---

.github/workflows/ci.yml

Parallelizes the CI workflow better.
See CI checks for the PR.

ci: parallelize ci better

---

.github/workflows/codecov.yml
README.md

Adds a codecov badge for quick reference.

ci: add codecov to docs, update workflow name

---

.github/workflows/ci.yml
.github/workflows/codecov.yml

Skips duplicate runs in the CI/codecov pipelines.

ci: skip duplicate runs

---

.github/workflows/ci.yml
.github/workflows/codecov.yml

Forgot the if line to actually skip ci if duplicate...

ci: actually skip ci if duplicate

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
.github/workflows/test-docs.yml
docs/content/index.md

Updates CI to be more file-specific; adds a new build test for docs.

ci: More specifitivity and doc build testing

---

docs/content/index.md

docs: change contribution wording in docs page a bit

---

CONTRIBUTING.md

Small wording updates for what is expected from bug reports.

docs: change wording slightly for bug report contribution

---

.github/workflows/ci.yml

Seems to work now, my issue of it always triggering before was due to matrices.

ci: switch action's accepted files back to "paths"

---

.github/workflows/codecov.yml

This seems to be needed if I add unit tests due to the repo being both a binary and a lib.

ci: add run type to codecov action

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

Uptick to 0.6.5, update changelog.

uptick: 0.6.5

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/packaging.md
CHANGELOG.md
CONTRIBUTING.md
README.md
docs/content/contribution/documentation.md
docs/mkdocs.yml

I would prefer for the project to not be under `clementtsang.github.io/bottom`, so let's try out CFP.

docs: try switching over to Cloudflare Pages

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/packaging.md
CONTRIBUTING.md
README.md
docs/content/contribution/documentation.md
docs/mkdocs.yml

_A description of the change and what it does. If relevant (such as any change that modifies the UI), **please provide screenshots** of the change:
Well, that was fast.  There were some weird interactions that I'm not sure about (like if you do `bottom.pages.dev/asdf/` it infinitely redirects...?), so I'll revert for now.

docs: revert CFP for now

---

docs/requirements.txt

Updates the dependencies for mkdocs-related stuff.

docs: update mkdocs requirements

---

.github/workflows/docs.yml
.github/workflows/post-release.yml

Temporarily disable the Cloudflare Pages hook while investigating why mike isn't playing nicely.

docs: disable CFP hook for now while investigating issues

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

uptick: 0.6.6

---

.github/workflows/audit.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/deployment.yml
.github/workflows/nightly.yml
.github/workflows/test-docs.yml
docs/content/index.md

Pins some actions using a specific commit hash.
- audit: https://github.com/ClementTsang/bottom/actions/runs/1613197376
- ci: https://github.com/ClementTsang/bottom/actions/runs/1613196321
- codecov: https://github.com/ClementTsang/bottom/actions/runs/1613196322
- deployment: https://github.com/ClementTsang/bottom/actions/runs/1613271885
- docs: https://github.com/ClementTsang/bottom/actions/runs/1613200834
- nightly: https://github.com/ClementTsang/bottom/actions/runs/1613272119
- test-docs: https://github.com/ClementTsang/bottom/actions/runs/1613196323

ci: Use commit hash for some actions to pin them

---

Cargo.lock
Cargo.toml
src/utils/logging.rs

Updates [time to 0.3.5](https://github.com/time-rs/time/blob/main/CHANGELOG.md#035-2021-11-12).

deps: update time to 0.3.5

---

src/app/data_harvester/disks/heim/mod.rs
src/app/states.rs
src/canvas.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temp_table.rs
src/options.rs

Fixes warnings printed by Clippy when building the code.
Closes: #

Fix Clippy warnings

---

src/canvas/widgets/battery_display.rs
src/canvas/widgets/cpu_basic.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/mem_basic.rs
src/canvas/widgets/network_basic.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temp_table.rs
src/constants.rs

Micro-optimisation that doesn't have visible impact on performance but having more `const`s is nice.
No measurable build time change, size is down to 6069024 from 6084792.
Closes: #

Replace statics with consts where possible

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml

Add an additional validation step to the `.deb` file generation in nightly and deployment workflows.
Tested in the following nightly action: https://github.com/ClementTsang/bottom/actions/runs/1639386680

ci: test installing .deb in build

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
docs/content/support/official.md

Update support links in documentation; add section on WSL in Linux known issues.

docs: add section on WSL in Linux known issues, update links

---

.github/ISSUE_TEMPLATE/feature_request.md
docs/content/contribution/issues-and-pull-requests.md

Just adds an extra line to the template/docs to check if an existing issue already exists.

docs: add a line to feature request docs/template

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

Uptick to 0.6.7, with appropriate updates to the README and changelog.
Closes: #

uptick: 0.6.7

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

uptick: 0.6.8

---

Cargo.lock
Cargo.toml

Updates the sysinfo dependency to 0.23.4.
Closes: #

deps: update sysinfo to 0.23.4

---

.github/workflows/coverage.yml

Update to use a manual install of cargo tarpaulin.

ci: switch to a manual cargo tarpaulin installation

---

Cargo.lock
Cargo.toml

Just update a few small dependencies.

deps: update procfs and testing deps

---

.github/workflows/audit.yml

Manually install the audit crate as part of the audit CI since it seems to be using too old of a version of Rust.
Closes: #

ci: update audit workflow

---

src/app/data_harvester/temperature/mod.rs
src/data_conversion.rs
src/lib.rs

Fixes a few clippy lints around function parameters and using slices over vector references.

other: fix clippy lints on vector reference params

---

docs/content/contribution/documentation.md
docs/content/contribution/issues-and-pull-requests.md
docs/mkdocs.yml
docs/requirements.txt

Fixes a broken link, and mention when to use discussions over issues. Also updates mkdocs in the build process due to some broken dependencies.

docs: mention discussions, fix broken link, update mkdocs req

---

src/app.rs
src/app/data_farmer.rs
src/canvas/dialogs/dd_dialog.rs
src/canvas/drawing_utils.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/cpu_basic.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/mem_graph.rs
src/canvas/widgets/network_graph.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temp_table.rs
src/options.rs
tests/arg_tests.rs

Remove some simple as casts that are easy to change to `.into()`, or easy to check.

refactor: remove some simple as-casts

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml

Updates cargo-deb to 1.37.
Tested on [this mock nightly build.](https://github.com/ClementTsang/bottom/actions/runs/2117663112)

ci: update cargo deb to 1.37

---

docs/requirements.txt

Bumps mkdocs-material to 8.2.9.
Closes: #
CI checks build succeeds, quick check on the generated docs seems fine.

docs: update mkdocs-material to 8.2.9

---

docs/mkdocs.yml

Enables some search features for the mkdocs config.

docs: enables some search features to mkdocs config

---

codecov.yml

Increases codecov threshold to 5% for less annoying failures.
Closes: #

ci: increase codecov threshold to 5%

---

Cargo.lock
Cargo.toml
src/app/data_farmer.rs

Updates various dependencies in both `Cargo.toml` and `Cargo.lock`.
Closes: #

deps: update dependencies as of 2022-04-27

---

.github/workflows/coverage.yml

Super small change, install cargo-llvm-cov with `--locked`.

ci: lock cargo-llvm-cov install in script

---

src/app/states.rs
src/canvas/drawing_utils.rs

Small PR to quickly refactor some recent tests to avoid too much duplication.

refactor: refactor some tests to dedupe some code

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/deployment.yml
.github/workflows/nightly.yml

Disables incremental compilation and debug symbols in CI and other related workflows, since they're not used there at all. Also forces --locked as needed.
CI workflows below should pass. Also individually testing nightly + deploy scripts:
- [Deploy](https://github.com/ClementTsang/bottom/actions/runs/2247773865)
- [Nightly](https://github.com/ClementTsang/bottom/actions/runs/2247774473)

ci: disable debug symbols and incremental in CI, force locked

---

.github/workflows/ci.yml
.github/workflows/deployment.yml
.github/workflows/nightly.yml
Cargo.toml

Removes the caching step from the cargo fmt check as it does nothing. Also adds an extra test for if the battery feature is disabled (also to maybe help test cache reuse in CI).

ci: remove caching step from cargo fmt check

---

docs/requirements.txt

Updates mkdocs-material to 8.2.13.

docs: update mkdocs-material to 8.2.13

---

.cargo-husky/hooks/pre-push

Just adds a `cargo fmt` check to the husky pre-push check.

other: add fmt to husky hook

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml

Make a note of release sizes in the nightly/deploy scripts. This is mostly just in case I need to refer to it in the future (mainly for nightly, as the actual generated files are overwritten daily).
- Nightly run tested [here](https://github.com/ClementTsang/bottom/actions/runs/2348519983).
- Deploy not tested as its the exact same change.

ci: note release sizes in nightly/deploy

---

docs/requirements.txt

Bump mkdocs-material dependency to 8.2.15.

docs: bump mkdocs material to 8.2.15

---

.github/workflows/coverage.yml

Just updates the coverage tool to 0.4.4.
CI workflow tests the update.

ci: update cargo_llvm_cov to 0.4.4

---

.github/workflows/audit.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/deployment.yml
.github/workflows/docs.yml
.github/workflows/post-release.yml
.github/workflows/test-docs.yml

Bumps `checkout` calls to v3.
The following affected workflows were tested:

ci: bump checkout to v3

---

docs/requirements.txt

Bumps mkdocs-material to version [8.3.3](https://github.com/squidfunk/mkdocs-material/releases/tag/8.3.3).
CI should pass, and docs should be given a once-over at after merging to check for any obvious breakages.

 docs: bump mkdocs-material to 8.3.3

---

docs/requirements.txt

Bumps mkdocs-material to 8.3.8, which contains some bug fixes.
Should pass CI.

docs: bump mkdocs-material to 8.3.8

---

.github/workflows/coverage.yml

Just bumps `cargo-llvm-cov` to 0.4.8.
Should pass standard CI.

ci: bump cargo-llvm-cov to 0.4.8

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

Locks CI to cross 0.2.1.
Should pass CI.

ci: lock cross to 0.2.1 on CI as well

---

.github/workflows/ci.yml
tests/arg_tests.rs
tests/invalid_config_tests.rs
tests/util.rs

Fix missing `--target=${{ matrix.info.target }}` for primary test targets, and adjust integration tests to work with cross.
CI should pass as expected.

ci: fix missing target in tests

---

Cargo.toml

Adds files to exclude in `Cargo.toml`.
Should pass CI.

other: exclude some files in Cargo.toml

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml

Try to update to the newest cross version after 0.2.2 had some bugs causing a rollback to 0.2.1 (see https://github.com/ClementTsang/bottom/pull/755).
Must pass the following:

ci: try to update cross to 0.2.4

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml

Uses a personal action for simpler invocations of cargo/cross commands.
Must pass:

ci: try simpler cross/cargo action for builds and tests

---

CHANGELOG.md
README.md
docs/content/support/unofficial.md

Update some documentation to mention (currently unofficialish) FreeBSD support.

docs: mention FreeBSD works

---

docs/content/index.md

fix dead link

---

.github/workflows/build_releases.yml

Due to the [deprecation of Ubuntu 18.04](https://github.com/actions/runner-images/issues/6002) as a runner target this PR updates the OS to 20.04, the next supported version of Ubuntu.
Relevant workflows are to be run:

ci: update release build OS to ubuntu 20.04

---

CHANGELOG.md
docs/content/usage/general-usage.md

Updates documentation for the half-page scroll feature (see #774 for PR).
Documentation should build.

Half page scroll doc

---

docs/requirements.txt

Update mkdocs-material to 8.4.0.
Should build in CI and look fine after deployment.

docs: update mkdocs-material to 8.4.0

---

src/canvas.rs
src/canvas/dialogs/help_dialog.rs
src/constants.rs

Quick wording change + bug fix for the help menu.

other: Clarify help menu

---

Cargo.toml

Ran cargo-sort on the Cargo.toml file, though I manually moved the husky section back to the bottom. Should have no impact other than being a cosmetic (kinda) thing.

other: sort Cargo.toml

---

Cargo.lock
Cargo.toml

Adds the `zfs` feature to the `deploy` feature set.
Run mock nightly: https://github.com/ClementTsang/bottom/actions/runs/3051758558

other: add zfs to deploy feature set

---

src/app/data_harvester.rs
src/app/data_harvester/temperature.rs
src/app/data_harvester/temperature/linux.rs
src/app/data_harvester/temperature/sysinfo.rs

Since we no longer use heim for Linux disk checking, we can remove the async reliance and update some file names/comments to be more appropriate to the current state of the code. We also do some small cleanup.

refactor: minor cleanup of linux disk code

---

build.rs

Removes some redundant build script triggers.
Closes: #817
Worked locally, should also work when building on nightly workflow (see https://github.com/ClementTsang/bottom/actions/runs/3141754427).

other: remove some build script triggers

---

docs/requirements.txt

Update mkdocs-material dependency to 8.5.3.

docs: update mkdocs-material to 8.5.3

---

README.md

docs: add voidlinux install instructions to README

---

.cirrus.yml
.github/workflows/ci.yml

ci: add basic Cirrus CI testing for FreeBSD + M1

---

src/canvas/widgets/cpu_basic.rs
src/canvas/widgets/mem_basic.rs
src/components.rs
src/components/tui_widget.rs
src/components/tui_widget/pipe_gauge.rs

This moves most of the custom users of the pipe gauge to a `tui-rs`-based implementation.
Closes: #

refactor: switch to pipe gauge implementation for basic cpu + mem

---

src/app/data_harvester/cpu/heim.rs
src/app/data_harvester/cpu/heim/linux.rs
src/app/data_harvester/cpu/heim/windows_macos.rs
src/app/data_harvester/processes/linux.rs
src/canvas.rs
src/canvas/widgets/mem_basic.rs
src/canvas/widgets/mem_graph.rs
src/canvas/widgets/network_graph.rs
src/components/time_graph.rs
src/components/tui_widget/time_chart.rs
src/data_conversion.rs

Moves the `Point` type alias to the `tui_rs` widget definition.
Closes: #

refactor: move point definition to `tui_rs` widget

---

src/clap.rs

As per the [clap 4.0 migration guide](https://github.com/clap-rs/clap/blob/bd5a6eab3bb4c8e3bd9f75be83821f316dde8ac8/CHANGELOG.md#migrating), this PR adds a quick test verifying that clap at least builds.
Closes: #

other: add quick test for building clap app

---

CHANGELOG.md

Update changelog with NVIDIA GPU memory usage support and macOS PPID bug fix.
Closes: #

docs: update changelog as of 2022-10-16

---

src/app/layout_manager.rs
src/app/states.rs
src/app/widgets.rs
src/app/widgets/battery_widget.rs
src/app/widgets/mem_graph.rs
src/app/widgets/net_graph.rs
src/options.rs

Just moves some code around prior to making some changes.
Closes: #

refactor: separate out individual widget state code

---

.cirrus.yml

Some cache and conditional fixes for Cirrus CI testing. The test tasks should only run on the default branch and on PRs.
Closes: #
CI should pass, run only when intended, and properly cache.

ci: various Cirrus CI test fixes

---

.cirrus.yml

Since it is a more limited platform for the public free tier, particularly for macOS VMs, it seems better to combine the testing scripts rather than using a matrix.
Closes: #

ci: merge all-feature and no-feature tests on Cirrus

---

.github/workflows/coverage.yml

Deals with the node12 deprecation warning.
Closes: #

ci: update codecov upload action to 3.1.1

---

.cirrus.yml

Fixes the cleanup stage of the build in cirrus due to a missing directory.
Closes: #

ci: fix cirrus ci build cleanup

---

.github/workflows/coverage.yml

Seems like the codecov action can sometimes fail (see [this workflow](https://github.com/ClementTsang/bottom/actions/runs/3316790273/workflow)). See [this issue](https://github.com/codecov/codecov-action/issues/837) for more details about this issue and some workarounds for now.
Closes: #
Workflows should all pass.

ci: add token secret to make codecov action more stable

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/docs.yml
.github/workflows/post-release.yml
.github/workflows/test-docs.yml

Use Github Action's [`concurrency`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) settings to cancel old actions in favour of newer ones.
Closes: #
All affected pipelines should pass.

ci: test cancelling stale actions

---

.cirrus.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/test-docs.yml
deployment/cirrus/build.py

Use one single skip check job for CI like other workflows.
Closes: #
CI should pass.

ci: use one skip check for CI workflow

---

docs/requirements.txt

Updates the following document building libraries:
- `mkdocs` (1.3.1 -> 1.4.1)
- `mkdocs-material` (8.5.3 -> 8.5.7)
- `mkdocs-material-extensions` (1.0.3 -> 1.1.0)
Closes: #
Docs in CI should test successfully to build.

docs: update docs lib versions as of 2022-10-29

---

.github/workflows/docs.yml
.github/workflows/post-release.yml
.github/workflows/test-docs.yml

Updates any workflows with `setup-python` to use v4.3 due to node deprecation warnings.
Closes: #
All relevant CI workflows should succeed.

ci: update workflows with setup-python to v4.3.0

---

.cirrus.yml
.github/workflows/ci.yml

Avoid running the Cirrus CI test task if there aren't relevant changes.
Closes: #
CI should pass when expected and skip when no changes are made.

ci: add skip based on file changes for Cirrus tests

---

.github/pull_request_template.md
.github/workflows/ci.yml

Just use a single final step and unify if-checks; should make the CI workflow requirements a bit cleaner to work with.
Closes: #
CI workflow still works as expected in cases where it should run or should be skipped.

ci: unify CI workflow with one ending step

---

src/app.rs
src/app/data_farmer.rs
src/app/states.rs
src/app/widgets/cpu_graph.rs
src/app/widgets/disk_table.rs
src/app/widgets/process_table.rs
src/app/widgets/temperature_table.rs
src/canvas/widgets.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temperature_table.rs
src/components/data_table.rs
src/components/data_table/draw.rs
src/data_conversion.rs
src/lib.rs
src/units.rs

Small refactor to move where data is passed to the table. This is a step in cutting out some redundant data conversion steps.
Closes: #

refactor: move data passing for table to another step

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/test-docs.yml

Don't enable `cancel-in-progress` for the main branch.
Closes: #
Should still work for non-main.

ci: try only having cancel-in-progress for non-main branch

---

build.rs
src/app.rs
src/app/data_harvester/disks/freebsd.rs
src/app/data_harvester/processes/freebsd.rs
src/app/data_harvester/processes/macos.rs
src/app/widgets/process_table.rs
src/canvas/canvas_colours.rs
src/clap.rs
src/components/data_table/draw.rs
src/components/data_table/sortable.rs

Small code refactoring + clippy fixes.
Closes: #

refactor: clippy and small cleanup/comments

---

Cargo.lock
Cargo.toml

Updates `sysinfo` to 0.26.7 from 0.26.4. See [the changelog](https://github.com/GuillaumeGomez/sysinfo/blob/master/CHANGELOG.md) for more details.
Closes: #

deps: update sysinfo to 0.26.7

---

Cargo.lock
Cargo.toml
src/app/data_harvester/nvidia.rs

Update nvml-wrapper to 0.8.0. See [changelog](https://github.com/Cldfire/nvml-wrapper/blob/master/CHANGELOG.md#080-released-2022-05-26) for more details.
Closes: #
Tested on a Windows VM with an NVIDIA GPU passed through to still work.

deps: update nvml-wrapper to 0.8.0

---

src/app.rs
src/app/widgets/cpu_graph.rs
src/app/widgets/disk_table.rs
src/bin/main.rs
src/lib.rs

Adds basic sorting + shortcuts for disk.
Closes: #567 

feature: basic sortable disk

---

CHANGELOG.md
docs/content/usage/widgets/disk.md

Update docs for #870. 
Closes: #

docs: update docs for disk sorting feature

---

.github/workflows/build_releases.yml
.github/workflows/clear-pr-cache.yml
.github/workflows/test-docs.yml
scripts/clear_cache.py
src/lib.rs

Automatically clear the cache taken up by a PR when merged/closed.
Closes: #

ci: add cache clearing to PR merges

---

docs/content/index.md

docs: add a quick blurb on doc site of what bottom is

---

.github/pull_request_template.md
docs/content/index.md
docs/content/usage/general-usage.md
docs/mkdocs.yml

Quick update to docs to add links to usage/config sections in the main page, as well as some usage section changes.
Closes: #

docs: update usage and config, add blurb in home

---

Cargo.lock
Cargo.toml
src/bin/main.rs
src/lib.rs
src/utils/error.rs

Updates tui-rs to [0.19.0](https://github.com/fdehau/tui-rs/blob/a05fd4595956676404e9edb94f8532bfea1669ea/CHANGELOG.md) and crossterm to [0.25.0](https://github.com/crossterm-rs/crossterm/blob/5d02ed8c37b4e284c9e63fc7d557806ee8d1ab84/CHANGELOG.md).
Closes: #877, closes: #562
Everything should build and work.

deps: Update tui to 0.19.0 and crossterm to 0.25.0

---

.github/workflows/ci.yml

Seems like it was causing some cache key collisions without it.
Closes: #

ci: add back target as cache key

---

scripts/cirrus/build.py

ci: wrap checks with try block to avoid panic

---

Cargo.lock
Cargo.toml
src/bin/main.rs
src/lib.rs

Try using [flume](https://crates.io/crates/flume) for channel message passing.
Closes: #

other: try using flume for channel

---

src/lib.rs

The throttler is only really needed for scrolls (e.g. free scroll wheels in Logitech mice), I don't really see it being needed in any other contexts. Moves/drag is another one I guess but we outright ignore those events right now.
Closes: #

other: remove the mouse throttler except for scroll events

---

.github/workflows/nightly.yml

ci: bump delete-tag-and-release to v0.3.1

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
CONTRIBUTING.md
docs/content/contribution/issues-and-pull-requests.md

Unifies cache keys so that build jobs can reuse the CI cache (read-only).
Closes: #

ci: unify cache keys in actions

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml

Made a mistake in not testing properly and broke the build workflow with missing envs.
Closes: #

ci: fix missing envs in build workflow

---

Cargo.lock
Cargo.toml
src/bin/main.rs
src/lib.rs

In hindsight, pulling in flume is probably overkill and doesn't really help much.
Closes: #

other: remove flume

---

Cargo.lock
Cargo.toml
src/app.rs
src/app/data_harvester/processes/linux.rs

Some dependency bumps and code changes to accommodate them.
Closes: #

deps: update sysctl to 0.5.2, procfs to 0.14.1

---

src/app/data_farmer.rs

Should prevent the times series array from possibly growing indefinitely.
Closes: #

other: shrink the timed data vector in addition to clearing

---

src/app/data_harvester/processes/linux.rs

other: small linux process cleanup

---

Cargo.lock
Cargo.toml
src/app/widgets/process_table.rs
src/canvas/widgets/process_table.rs
src/components/data_table/sortable.rs

Some cleanup. Introduces the `const_format` crate to allow for `const str` formatting.
Closes: #

other: some cleanup in proc widget

---

src/app/data_harvester/processes/macos_freebsd.rs
src/app/data_harvester/processes/windows.rs

Fixes using `.is_nan()` to check if a division by zero occurred.
Closes: #

bug: fix is_nan being incorrectly used to check for division by zero

---

.github/workflows/build_releases.yml

Closes: #
Build passes, see https://github.com/ClementTsang/bottom/actions/runs/3507345803

ci: bump cargo deb to 1.41.1 in CI

---

src/clap.rs

`p` -> `n` to reflect the name change
Closes: #

other: change non-normalized shortcut

---

.cirrus.yml

ci: fix freebsd Cirrus build script

---

CHANGELOG.md
docs/content/configuration/command-line-flags.md
docs/content/configuration/config-file/flags.md
sample_configs/default_config.toml
src/clap.rs

Updates some documentation for #919.
Closes: #

docs: update changelog + docs for default expansion feature

---

README.md

See https://github.com/badges/shields/issues/8671 for details.
Closes: #

docs: fix readme workflow shield

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
README.md

uptick: 0.7.0

---

README.md
src/widgets/process_table/proc_widget_data.rs

docs: update demo to 0.7.0

---

.github/workflows/build_releases.yml

ci: disable cache for cross release gen

---

.github/workflows/build_releases.yml
scripts/cirrus/build.py

ci: default to master branch on tag release

---

scripts/windows/choco/chocolateyinstall.ps1.template

Seems like I had a typo in the template that wasn't caught. This caused issues during the deployment as it means the choco file is invalid.
Closes: #

ci: remove typo in chocolatey template

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml

Follow-up of #846 to update the `action-gh-release` dependency.
Closes: #
Both this [mock](https://github.com/ClementTsang/bottom/actions/runs/3815277530) nightly and [non-mock](https://github.com/ClementTsang/bottom/actions/runs/3815284694) nightly should pass.

ci: update action-gh-release dependency

---

.github/workflows/build_releases.yml
scripts/cirrus/build.py

Reverts #943 with a better way of creating a release based on a tag.
Closes: #
[This](https://github.com/ClementTsang/bottom/actions/runs/3815865678) dummy release workflow and [nightly](https://github.com/ClementTsang/bottom/actions/runs/3815868466) workflow should succeed.

ci: use a better way of getting branch from tagged builds for CirrusCI

---

.github/workflows/build_releases.yml
src/data_conversion.rs

other: run nightly rustfmt

---

.github/workflows/build_releases.yml

ci: add timeout to build workflow caching

---

docs/mkdocs.yml

docs: make stable docs the default

---

src/canvas/widgets/battery_display.rs

This just further shrinks the text in small-window situations.
Closes: #

bug: further shrink battery time-to text

---

README.md

docs: fix debian/ubuntu download links

---

README.md

docs: minor update of Windows installation docs

---

.github/workflows/build_releases.yml
README.md
build.rs

Change the `.deb` file generation back to following standard naming conventions.
Closes: #
See [this](https://github.com/ClementTsang/bottom/actions/runs/3900484030) nightly run.

ci: follow .deb naming conventions

---

.github/workflows/build_releases.yml

Easier to stay consistent, I guess.
Closes: #

ci: remove git hash and nightly tag from deb file name

---

.github/workflows/build_releases.yml

Seems just as fast without it, given how I was trying to re-use the CI cache.
Closes: #

ci: try removing cache from build workflow

---

.github/workflows/clear-workflow-cache.yml
scripts/clear_cache.py

ci: add schedule to clear PR caches

---

Cargo.lock
Cargo.toml

deps: update procfs to 0.14.2

---

Cargo.lock
Cargo.toml

deps: update indexmap to 1.9.2

---

Cargo.lock
Cargo.toml

Updates:
- log
- serde
- itertools
Closes: #

deps: updates some minor deps as of 2023-01-14

---

Cargo.lock
Cargo.toml

deps: update unicode deps to support unicode 15

---

Cargo.lock
Cargo.toml

deps: update regex to 1.7.1

---

Cargo.lock
Cargo.toml

deps: update more dependencies as of 2022-01-14

---

.all-contributorsrc
CHANGELOG.md
README.md

docs: update changelog and all contrib sections

---

Cargo.lock
Cargo.toml
src/app/process_killer.rs
src/utils/error.rs

Switches to the [windows](https://crates.io/crates/windows) crate for handling process killing on Windows.
Closes: #

other: switch to windows-rs for process killing

---

Cargo.toml

other: fix missing memory feature for heim on linux

---

Cargo.toml

Bumps the `Cargo.toml` edition to 2021.
Closes: #

other: bump edition to 2021

---

src/app/data_harvester.rs

Matches what `update_data()` already did.
Closes: #

other: refresh cpu for sysinfo users if proc is used

---

.github/ISSUE_TEMPLATE/bug_report.yml
Cargo.toml
src/app.rs
src/app/states.rs
src/lib.rs
src/options.rs
src/widgets/process_table.rs

Just some renaming for a later commit.
Closes: #

refactor: change name of some stuff, add some comments

---

CHANGELOG.md
src/components/time_graph.rs
src/components/tui_widget/time_chart.rs

Fixes graph axis labels not being styled.
Before (normal, gruvbox and gruvbox light respectively):
After (normal, gruvbox and gruvbox light respectively):
And on Konsole, with a green scheme:
Before:
After:
Closes: #993

bug: fix axis labels not being styled

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md

uptick: 0.8.0

---

.github/workflows/coverage.yml

ci: update cargo-llvm-cov to 0.5.9

---

Cargo.toml

other: run cargo sort on Cargo.toml

---

Cargo.lock
Cargo.toml

other: bump to 0.8.1 for nightly

---

.github/workflows/docs.yml
.github/workflows/post-release.yml
.github/workflows/test-docs.yml
docs/README.md
docs/content/contribution/documentation.md
docs/requirements.txt

`requirements.txt` bump:
- `mkdocs` to 1.4.2
- `mkdocs-material` to 9.0.10
Also update the Actions Python version to 3.11 for doc-related work, which should net a nice speedup (even if not really needed).
Closes: #

docs: update requirements.txt and bump to 3.11

---

docs/requirements.txt

docs: bump mkdocs-material and mkdocs-material-extensions

---

Cargo.toml

other: add no-opt and flamegraph build profiles for convenience

---

CHANGELOG.md
docs/content/usage/widgets/disk.md
docs/content/usage/widgets/process.md

docs: update changelog and missing doc info

---

src/app.rs
src/app/data_harvester/temperature.rs
src/clap.rs
src/options.rs
src/units/data_units.rs
src/widgets/process_table.rs

Clean up a bit of duplicate options code + add some tests. In the future it would be better to fully unify matches + options, but this is probably a bit helpful in heading towards that step.
Closes: #

refactor: clean up some options code

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

Add coverage checks for macOS and Windows.
Closes: #

ci: add coverage actions for macOS and windows

---

Cargo.lock
Cargo.toml

Clean up some deps and bump patch versions where possible.
This does not update some bigger dependencies where a minor+ version bump is needed, those will be a separate PR due to potential breakage (need to verify if it's fine or if small changes are needed). In particular:
- nvml-wrapper
- sysinfo
- crossterm
- toml
Closes: #

deps: bump patch dependency versions as of 2023-02-26

---

Cargo.lock
Cargo.toml

See [here](https://github.com/crossterm-rs/crossterm/releases/tag/0.26.1) for changes. Taking advantage of the kitty protocol stuff would be nice in the future.
Closes: #

deps: bump crossterm to 0.26.1

---

Cargo.lock
Cargo.toml
src/app/data_harvester/processes/linux.rs

deps: bump procfs to 0.15.1

---

CHANGELOG.md
src/app/data_harvester/disks/freebsd.rs
src/app/data_harvester/disks/heim.rs

docs: update changelog and some comments

---

docs/requirements.txt

docs: bump mkdocs-material to 9.1.0

---

src/app/data_harvester/memory/sysinfo.rs

refactor: Clean up memory collection code

---

Cargo.lock
Cargo.toml
src/app.rs
src/app/data_farmer.rs
src/app/data_harvester.rs
src/app/data_harvester/memory.rs
src/app/data_harvester/memory/arc.rs
src/app/data_harvester/memory/gpu.rs
src/app/data_harvester/memory/sysinfo.rs

Clean up memory and general data collection code. Also removes heim's `sensor` feature since I was apparently not using it at all.
Technically affects #812, turns out I didn't need to do anything to migrate Linux temps.

refactor: more data collection cleanup

---

.cirrus.yml

ci: do no feature first in cirrus

---

src/app/data_harvester/processes/macos/sysctl_bindings.rs
src/app/data_harvester/processes/unix.rs
src/app/process_killer.rs
src/bin/main.rs
src/lib.rs

Something I've wanted to add for a while but kept forgetting. This forces comments on the safety invariants we should at least try to consider when using the occasional unsafe; this is mostly used for bindings.
Closes: #

other: deny missing safety docs and add them

---

src/app.rs
src/app/data_harvester/temperature.rs
src/app/layout_manager.rs
src/components/data_table/state.rs
src/data_conversion.rs
src/units/data_units.rs

In particular, `derivable_impls` now triggers a warning, so this resolves it.
Closes: #

clippy: appease clippy as of Rust 1.68.0

---

.cirrus.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/deployment.yml
.github/workflows/nightly.yml

ci: use sparse crates.io registries in CI

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/test-docs.yml

ci: bump fkirc/skip-duplicate-actions to v5.3.0

---

.github/workflows/build_releases.yml

ci: add musl build targets for .deb generation

---

docs/requirements.txt

docs: bump mkdocs-material to 9.1.3

---

src/app/data_harvester.rs
src/app/data_harvester/processes/freebsd.rs
src/app/data_harvester/processes/macos.rs
src/app/data_harvester/processes/macos_freebsd.rs
src/app/data_harvester/processes/windows.rs

Refactor of some data collection code. This also makes it so that sysinfo lists (e.g. sensor list, network list) are now refreshed on loop.
Closes: #

refactor: clean up some data collection refresh code, refresh sysinfo lists on loop

---

src/app/data_harvester.rs
src/app/data_harvester/memory.rs
src/app/data_harvester/memory/arc.rs
src/app/data_harvester/memory/gpu.rs
src/app/data_harvester/memory/sysinfo.rs
src/app/data_harvester/memory/windows.rs
src/app/data_harvester/processes/freebsd.rs
src/app/data_harvester/processes/linux.rs
src/app/data_harvester/processes/macos_freebsd.rs
src/app/data_harvester/processes/windows.rs
src/bin/main.rs
src/data_conversion.rs
src/lib.rs

Unify on using bytes as the unit rather than kilobytes/kibibytes, as well as some other small touchups here and there. No practical functionality should change.
Closes: #

refactor: unify on using bytes for the memory unit when harvesting

---

Cargo.lock
Cargo.toml

deps: bump various dependencies as of 2023-03-27

---

docs/content/troubleshooting.md

docs: add mention for braille font issues on Linux

---

docs/requirements.txt

docs: bump mkdocs-material to 9.1.4

---

src/app/filter.rs

other: add test for multiple regexes in filter

---

docs/requirements.txt

docs: update mkdocs-material to 9.1.5

---

src/bin/main.rs
src/lib.rs

other: add clippy lints to deny todo and unimplemented

---

Cargo.lock
Cargo.toml
src/app/data_harvester/memory/windows.rs

Bump some dependency versions as of April 7, 2023. Note I skipped any updates tied to futures as that's getting removed along with heim in the near future (heh).
Closes: #

deps: update some minor dependency versions

---

docs/requirements.txt

docs: update mkdocs-material to 9.1.6

---

.cirrus.yml
scripts/cirrus/build.py
scripts/packager.py
scripts/windows/choco/choco_packager.py

ci: run black on Python scripts

---

Cargo.lock
Cargo.toml

deps: bump serde to 1.0.160

---

Cargo.lock
Cargo.toml

deps: update starship-battery to 0.8.0

---

src/app/data_harvester.rs

refactor: clean up data init sleep duration code

---

src/constants.rs
src/data_conversion.rs
src/lib.rs

other: clean up code and update default config generation with cache option

---

Cargo.lock
Cargo.toml
src/canvas/dialogs/dd_dialog.rs
src/canvas/widgets/cpu_basic.rs

Migrates from [`tui`](https://github.com/fdehau/tui-rs) to [`ratatui`](https://github.com/tui-rs-revival/ratatui) since the latter is actively maintained right now.
Closes: #1072 

deps: migrate from tui to ratatui

---

rustfmt.toml

other: update deprecated fn_args_layout to fn_params_layout

---

CHANGELOG.md
Cargo.lock
Cargo.toml
build.rs
src/clap.rs
src/options.rs
tests/arg_tests.rs
tests/util.rs

deps: update clap to 4.x

---

src/app.rs
src/canvas/dialogs/dd_dialog.rs

refactor: add fallback process signal

---

CHANGELOG.md
Cargo.lock
Cargo.toml

deps: bump regex to 1.8.0

---

docs/requirements.txt

docs: update mkdocs-material to 9.1.8

---

Cargo.lock
Cargo.toml

deps: bump patch versions as of 2023-04-26

---

Cargo.lock
Cargo.toml

deps: bump clap to 4.2.5

---

sample_configs/default_config.toml

Updates the default config file example after #1115.
Closes: #

docs: update default config file with processes section

---

Cargo.lock
Cargo.toml

deps: bump patch versions as of 2023-04-30

---

Cargo.lock
Cargo.toml

deps: bump dirs to 5.0.1

---

docs/requirements.txt

docs: bump mkdocs-material to 9.1.9

---

.github/workflows/ci.yml

ci: output a failure in the completion step if a previous step failed

---

src/app/data_harvester/temperature.rs

other: use sysinfo for temps for android and ios

---

.github/workflows/ci.yml

ci: allow skipped CI workflow to mean success

---

Cargo.lock
Cargo.toml

deps: bump sysinfo to =0.29.0

---

Cargo.lock
Cargo.toml
src/app/data_harvester/disks/unix/file_systems.rs

deps: bump clap to 4.2.7 and libc to 0.2.143

---

docs/content/configuration/config-file/processes.md
docs/content/usage/widgets/memory.md
docs/content/usage/widgets/process.md
docs/mkdocs.yml

docs: update docs with processes column

---

docs/content/configuration/command-line-flags.md
docs/content/usage/widgets/process.md

docs: update help section of docs

---

docs/requirements.txt

docs: bump mkdocs-material to 9.1.11

---

docs/content/configuration/config-file/processes.md
docs/content/usage/widgets/process.md
src/app.rs
src/options.rs
src/options/process_columns.rs
src/widgets/process_table.rs
tests/invalid_config_tests.rs
tests/invalid_configs/invalid_process_column.toml

bug: fix certain custom column combinations causing issues

---

docs/content/configuration/config-file/processes.md

docs: update process config docs

---

Cargo.lock

Avoids an annoying message when installing with `--locked`.
Closes: #

deps: bump dependencies in Cargo.lock file

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md

uptick: 0.9.0

---

.github/workflows/audit.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/clear-workflow-cache.yml
.github/workflows/coverage.yml
.github/workflows/deployment.yml
.github/workflows/docs.yml
.github/workflows/nightly.yml
.github/workflows/post-release.yml
.github/workflows/test-docs.yml

This pins the `action` and `download-artifact` actions to specific hashes. This also updates `audit-check` to avoid deprecation issues, and bumps `setup-python` and `rust-toolchain`.
Closes: #
Tested most affected actions:

ci: pin and update some workflow actions

---

docs/requirements.txt

docs: bump mkdocs-material to 9.1.12

---

Cargo.lock
Cargo.toml

other: bump version to 0.9.1

---

Cargo.lock
Cargo.toml

deps: bump dependencies as of 2023-05-13

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md

uptick: 0.9.1

---

README.md

docs: add links to the repo locations for installation methods

---

Cargo.lock

deps: bump dependencies as of 2023-05-15

---

Cargo.lock

deps: bump dependencies as of 2023-05-17

---

src/app/layout_manager.rs
src/options/layout_options.rs

refactor: remove TypedBuilder for widget

---

src/app/layout_manager.rs
src/options/layout_options.rs

refactor: remove TypedBuilder for col

---

Cargo.lock
Cargo.toml

deps: bump clap to 4.3.0

---

Cargo.lock
Cargo.toml

deps: bump dependencies as of 2023-05-21

---

docs/requirements.txt

deps: bump dependencies for docs

---

Cargo.lock
Cargo.toml

deps: bump regex, toml_edit, ctrlc

---

.gitignore
src/lib.rs

Removes an enum variant that wasn't used for now, and just cleans up some names/comments.
Closes: #

other: clean up thread event code

---

src/bin/main.rs
src/lib.rs

This just simplifies the logic around ctrl-c and termination logic and event loop logic to something simpler and without the need for timeouts and/or atomics.
Instead, we just make termination an event sent by ctrl-c and use the same receiver for event handling to react to it and break the loop.
Closes: #

other: simplify termination/event loop logic

---

src/app/query.rs
src/bin/main.rs
src/lib.rs

other: clean up some fixmes

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

ci: update rust-cache to 2.4.0

---

.github/workflows/audit.yml

ci: add cache to audit job

---

src/app.rs
src/app/states.rs
src/bin/main.rs
src/canvas.rs
src/canvas/dialogs/dd_dialog.rs
src/canvas/widgets/basic_table_arrows.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/cpu_graph.rs
src/canvas/widgets/disk_table.rs
src/canvas/widgets/mem_graph.rs
src/canvas/widgets/network_graph.rs
src/canvas/widgets/process_table.rs
src/canvas/widgets/temperature_table.rs
src/lib.rs
src/options.rs

Another one on the chopping block. This also moves out the app widget logic to a separate struct.
Closes: #

refactor: remove typed builder from App struct

---

Cargo.lock
Cargo.toml

deps: bump regex and log

---

src/app/data_harvester/processes/linux.rs
src/app/data_harvester/processes/linux/process.rs

refactor: clean up some Linux proc collection code

---

Cargo.lock
Cargo.toml
src/canvas.rs
src/canvas/dialogs/dd_dialog.rs
src/canvas/dialogs/help_dialog.rs
src/canvas/widgets/basic_table_arrows.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/network_basic.rs
src/canvas/widgets/process_table.rs
src/components/data_table/draw.rs
src/components/time_graph.rs
src/components/tui_widget/pipe_gauge.rs
src/components/tui_widget/time_chart.rs
src/components/tui_widget/time_chart/canvas.rs
src/utils/gen_util.rs

deps: bump ratatui to 0.21.0

---

docs/requirements.txt

See the [changelog](https://github.com/squidfunk/mkdocs-material/blob/master/CHANGELOG) for more details.
Closes: #

docs: bump mkdocs-material to 9.1.15

---

Cargo.lock
Cargo.toml
src/app/layout_manager.rs
src/options/layout_options.rs

Removes the last usage of typed-builder and removes the crate dependency.
Closes: #

refactor: remove typed-builder

---

src/app/data_harvester/disks/unix/linux/counters.rs
src/components/tui_widget/time_chart/canvas.rs

other: fix links and broken references in doc comments

---

src/canvas.rs
src/canvas/widgets/process_table.rs

I never fixed this, but we can just do the "check" on compile-time as opposed to checking/storing the value.
Closes: #

refactor: change canvas macOS check to compile-time

---

Cargo.lock
Cargo.toml

Bumps these dependencies, which contains some small fixes/optimizations.
Closes: #

deps: bump clap, ctrc, once_cell

---

src/lib.rs

This was going to be used for in-app config, but it's so old that it's probably better to just rip it out and start anew in that regard.
Closes: #

refactor: remove outdated collection thread code

---

CHANGELOG.md

docs: update changelog to include ntfs3 mount change

---

Cargo.lock
Cargo.toml

deps: bump sysinfo to =0.29.2

---

Cargo.lock
Cargo.toml

deps: bump hashbrown, once_cell, regex, serde, time, libc, clap

---

src/app/data_harvester/disks.rs

other: have dummy fallback for disk I/O for unsupported OSes

---

CHANGELOG.md
src/app/data_harvester.rs
src/app/data_harvester/disks.rs
src/app/data_harvester/disks/freebsd.rs
src/app/data_harvester/disks/other.rs
src/app/data_harvester/disks/unix.rs
src/app/data_harvester/disks/windows.rs
src/canvas/dialogs/dd_dialog.rs

other: remaining changes needed to get android to build

---

.github/workflows/audit.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/clear-workflow-cache.yml
.github/workflows/coverage.yml
.github/workflows/deployment.yml
.github/workflows/docs.yml
.github/workflows/post-release.yml
.github/workflows/test-docs.yml

Updates:
- actions/checkout
- crazy-max/ghaction-choclatey
- actions/setup-python
Closes: #

ci: update various dependencies as of 2023-06-11

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md

uptick: 0.9.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/app/data_harvester/disks.rs
src/bin/main.rs
src/clap.rs
src/lib.rs
src/utils.rs
src/utils/logging.rs

other: post-0.9.2 cleanup

---

README.md

docs: fix Arch Linux package link

---

src/app/layout_manager.rs
src/canvas/dialogs/dd_dialog.rs
src/canvas/widgets/cpu_graph.rs
tests/arg_tests.rs

other: clean up some cfg usage

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml

ci: use cargo-action v0.0.4

---

.github/ISSUE_TEMPLATE/packaging.yml
README.md

docs: add .rpm install instructions to the README

---

docs/requirements.txt

docs: bump mkdocs-material to 9.1.16

---

Cargo.lock
Cargo.toml

deps: bump clap, rustix, serde_json

---

.github/workflows/post-release.yml

ci: add an action to automatically publish a winget PR on release

---

.github/workflows/post-release.yml

ci: add checks to ensure post-release never runs on main/master/nightly

---

src/args.rs

Didn't mean to push this, reverting it.
Closes: #

other: revert color help text change

---

build.rs

Some build script formatting fixes and cleanup of some code. In particular, I found some of the nightly version handling code to look pretty gross so I separated out the parts into functions to clean it up a bit.
Closes: #

other: clean up some build script code

---

docs/content/configuration/command-line-flags.md
docs/content/configuration/config-file/flags.md
sample_configs/default_config.toml
src/args.rs
src/components/data_table/column.rs
src/constants.rs
src/options.rs

Few things:
- Updates the documentation for `default_time_value` and `time_delta` to show support for human times.
- Update the errors to be more human-friendly.
- Support both numerical values (in ms) or strings in the config, along with tests.
- Also update the args' help to be more in-line with what's supported.
Closes: #

other: fix humantime-related documentation, add tests, support numbers + strings in toml

---

CHANGELOG.md
src/app.rs
src/args.rs
src/constants.rs
src/lib.rs
src/options.rs
tests/arg_tests.rs

feature: support human times for rate

---

docs/content/configuration/command-line-flags.md
docs/content/configuration/config-file/flags.md
sample_configs/default_config.toml
src/args.rs
src/options.rs

docs: update time-related documentation

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md

uptick: 0.9.3

---

.github/workflows/deployment.yml
.github/workflows/post-release.yml

ci: clean + fix post-release and deployment actions

---

.github/workflows/post-release.yml

ci: fix winget package identifier

---

docs/requirements.txt

docs: bump mkdocs-material to 9.1.17

---

.github/workflows/deployment.yml

Matches the `CHANGELOG.md` order.
Closes: #

ci: update release template

---

Cargo.lock
Cargo.toml

deps: bump deps as of 2023-06-27

---

Cargo.lock
Cargo.toml
src/app/data_harvester/processes/linux/process.rs

Bumps clap and rustix, and handles some deprecations.
Closes: #

deps: bump deps as of 2023-06-29

---

src/app/data_farmer.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/network_graph.rs

Removes some unnecessary vec allocations throughout the code. Some of these were *super* old bits of code.
Closes: #

other: remove some unnecessary vec allocations

---

CHANGELOG.md
src/app.rs
src/canvas/widgets/battery_display.rs
src/data_conversion.rs

other: hide battery tab selector if there is only one battery

---

Cargo.lock
Cargo.toml

deps: bump dependencies as of 2023-07-03

---

src/widgets/cpu_graph.rs

other: remove the percentage sign for CPU usage in CPU widget

---

src/canvas/widgets/battery_display.rs

other: removes the percent sign from battery widget labels

---

Cargo.lock
Cargo.toml

Bumps some dependencies. Of particular interest is `regex 1.9.0`, which might increase compilation times but may be more performant.
Closes: #

deps: bump deps as of 2023-07-06

---

docs/requirements.txt

docs: bump mkdocs material to 9.1.18

---

Cargo.lock
Cargo.toml

deps: bump regex, serde, thiserror

---

CHANGELOG.md

other: update changelog with ZFS I/O counters

---

src/app/data_harvester/disks.rs
src/app/data_harvester/disks/freebsd.rs
src/app/data_harvester/disks/unix/linux/counters.rs
src/app/data_harvester/disks/unix/macos/counters.rs
src/app/data_harvester/disks/windows.rs
src/app/data_harvester/disks/zfs_io_counters.rs

refactor: flatten IoCounter return value

---

Cargo.lock
Cargo.toml

deps: clean and update deps in Cargo.toml

---

docs/requirements.txt

docs: bump mkdocs-material to 9.1.19

---

src/canvas/widgets/battery_display.rs

Add full width bar in battery widget with spacing between charge info e battery info
Closes: #1238

Full width battery bar

---

CHANGELOG.md

docs: update changelog to include full width battery change

---

Cargo.lock
Cargo.toml

deps: bump some dependencies as of 2023-07-19

---

Cargo.lock
Cargo.toml
src/components/tui_widget/pipe_gauge.rs

deps: Update ratatui 0.22.0

---

Cargo.lock
Cargo.toml

deps: pin sysinfo to 0.29.6

---

Cargo.lock
Cargo.toml

deps: bump dependencies as of 2023-07-24

---

CHANGELOG.md

docs: update changelog with ARC max usage fix

---

Cargo.lock
Cargo.toml

deps: pin sysinfo to 0.29.7

---

docs/requirements.txt

docs: bump mkdocs-material to 9.1.21 and mkdocs to 1.5.1

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md

uptick: 0.9.4

---

CHANGELOG.md
Cargo.lock
Cargo.toml

deps: bump deps as of 2023-08-08

---

Cargo.lock
Cargo.toml

deps: pin sysinfo to 0.29.8

---

Cargo.lock
Cargo.toml

See: https://github.com/serde-rs/serde/issues/2538
Closes: #

deps: pin serde to <=1.0.171

---

Cargo.lock
Cargo.toml

deps: bump dependencies as of 2023-08-18

---

Cargo.lock
Cargo.toml
src/app/data_harvester/disks/windows/bindings.rs
src/app/data_harvester/memory/windows.rs
src/app/process_killer.rs

deps: bump windows to 0.51.1

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md

Update that only pins sysinfo, in case anyone wants to build it without pulling in the serde_derive binary.
Closes: #

uptick: 0.9.5

---

Cargo.lock
Cargo.toml
src/lib.rs

deps: bump dependencies as of 2023-08-26

---

.github/ISSUE_TEMPLATE/bug_report.yml
README.md

uptick: 0.9.6

---

docs/requirements.txt

docs: bump mkdocs and mkdocs-material versions

---

.github/ISSUE_TEMPLATE/bug_report.yml

github: add section on whether you're using ZFS

---

Cargo.lock
Cargo.toml

deps: bump sysinfo to =0.29.10

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml
Cargo.lock
Cargo.toml
build.rs

bump clap and add nushell/fig completions

---

.github/workflows/docs.yml
.github/workflows/post-release.yml
CHANGELOG.md
docs/content/contribution/documentation.md
docs/content/contribution/issues-and-pull-requests.md
docs/content/contribution/packaging-and-distribution.md
docs/content/troubleshooting.md
docs/content/usage/widgets/process.md
src/app/data_harvester/disks/unix/linux/partition.rs

Just some text cleanups
Includes a CI pass code change (same as all other PRs)

Chore: Run an spell cheker, and gramar cheker

---

src/app/data_harvester/disks/unix/file_systems.rs
src/app/data_harvester/disks/unix/linux/partition.rs

Small refactor to make the function use a less weird match statement.
Closes: #

refactor: comment on convoluted `Filesystem::from_str` code

---

src/app/data_farmer.rs
src/app/data_harvester/disks/unix/file_systems.rs
src/app/query.rs
src/canvas/widgets/network_graph.rs
src/data_conversion.rs
src/lib.rs
src/utils/data_prefixes.rs
src/utils/gen_util.rs

refactor: clean up some query code and some ascii-only string comparisons

---

docs/content/contribution/documentation.md
docs/mkdocs.yml
docs/requirements.txt
docs/serve.sh

Update doc generation to use [mike v2.0.0](https://github.com/jimporter/mike/releases/tag/v2.0.0).
Closes: #

docs: bump mike to v2.0.0

---

Cargo.lock
Cargo.toml

Update `toml_edit` to [0.21.0](https://github.com/toml-rs/toml/blob/main/crates/toml_edit/CHANGELOG.md#0210---2023-11-06).
Closes: #1319

deps: bump toml_edit to 0.21.0

---

.github/workflows/audit.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/clear-workflow-cache.yml
.github/workflows/coverage.yml
.github/workflows/deployment.yml
.github/workflows/docs.yml
.github/workflows/post-release.yml
.github/workflows/test-docs.yml

Updates to https://github.com/actions/checkout/releases/tag/v4.1.1
Closes: #

ci: bump actions/checkout to v4.1.1

---

docs/content/configuration/config-file/processes.md

docs: fix typo in process column config

---

src/options.rs
src/widgets/process_table/proc_widget_column.rs

Quick follow-up PR to #1276 with some small tweaks.
Closes: #

change: small gpu proc changes

---

CHANGELOG.md

docs: update changelog ordering and some wording

---

.github/workflows/coverage.yml

Update to using [cargo-llvm-cov 0.5.37](https://github.com/taiki-e/cargo-llvm-cov/tree/v0.5.37) for coverage testing.
Closes: #

ci: update cargo-llvm-cov to 0.5.37

---

.github/workflows/audit.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml

Update to use the [rust-cache v2.7.0](https://github.com/Swatinem/rust-cache/releases/tag/v2.7.0) GitHub action.
Closes: #

ci: update rust-cache to 2.7.0

---

.gitignore
src/utils/gen_util.rs

This is just a first attempt to speed up what looked like a hot spot in samply's profiling results.
Benchmark code and results here: https://gist.github.com/ClementTsang/e242f12f7e1d1902ed414dcc18c3b321
Some generated charts:
Closes: #

refactor: add fast branch for ascii-only string truncate

---

src/constants.rs

other: update generated config file

---

src/utils/gen_util.rs

other: preallocate space for ellipsis

---

Cargo.lock
Cargo.toml

deps: update sysinfo to 0.29.11

---

Cargo.lock
Cargo.toml

deps: bump dependencies as of 2023-11-27

---

.github/ISSUE_TEMPLATE/bug_report.yml

github: update filesystem issue template section

---

.github/ISSUE_TEMPLATE/bug_report.yml

github: update more wording of the bug issue template

---

CHANGELOG.md
docs/content/configuration/command-line-flags.md
src/args.rs
src/options.rs

Was brought to my attention in #1339 that there was still an inconsistency between the `group` arg and the `group_processes` config file field. I had a TODO sitting around to update `group` for years but thought it was a breaking change to do so, so I guess now is a good time since the next update I plan on is a minor bump.
Closes:

other: change group -> group_processes for consistency between config and command-line args

---

.github/ISSUE_TEMPLATE/bug_report.yml

github: update wording around filesystem section in issue template

---

.cirrus.yml
.github/workflows/ci.yml
.github/workflows/clear-workflow-cache.yml
.github/workflows/coverage.yml
.github/workflows/docs.yml
CONTRIBUTING.md
README.md
docs/content/configuration/config-file/layout.md
docs/content/contribution/development/build_process.md
docs/content/contribution/development/deploy_process.md
docs/content/contribution/documentation.md
docs/content/contribution/issues-and-pull-requests.md
docs/content/contribution/packaging-and-distribution.md
docs/content/support/unofficial.md
docs/content/troubleshooting.md
docs/mkdocs.yml
scripts/windows/choco/bottom.nuspec.template

I'm so used to using `main` branch now that it's actually kinda annoying to use `master` for just this repo... so might as well rename it now.
Closes: #

other: master -> main

---

CHANGELOG.md

docs: update changelog with #1353

---

src/app/data_harvester/temperature/linux.rs

refactor: some more cleanups around linux temp code

---

src/app/data_farmer.rs

refactor: fix macro formatting in disk data collection code

---

Cargo.lock
Cargo.toml

deps: bump anyhow, clap, and thiserror

---

src/canvas/widgets/cpu_basic.rs
src/lib.rs

other: quick lint fixes for some warnings

---

Cargo.toml
src/app/filter.rs
src/lib.rs

I have `missing_docs` disabled for now as that'll take a long time to get through... maybe in a separate PR.
Closes: #

other: update lints

---

src/canvas.rs
src/canvas/dialogs/help_dialog.rs
src/canvas/widgets/battery_display.rs
src/canvas/widgets/process_table.rs
src/constants.rs

I was pre-initializing the help text and storing it on initialization, which I think is really unnecessary.
Closes: #

refactor: clean up help drawing code

---

README.md
docs/content/configuration/command-line-options.md
docs/content/usage/general-usage.md
sample_configs/default_config.toml
src/constants.rs

Fixes some wording around command line options, as well as some missing code blocks in docs.
Closes: #

docs: use consistent wording around command-line options

---

docs/requirements.txt

docs: bump mkdocs-material to 0.9.6

---

docs/.gitignore
docs/mkdocs.yml

docs: change code font and enable privacy

---

.github/workflows/audit.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
Cargo.toml

In CI, just some cleanup, and some action version bumps.
Closes: #

ci: clean up some jobs in CI; bump Rust-related actions

---

.github/workflows/coverage.yml

ci: add logic to retry codecov upload

---

src/canvas/styling.rs
src/options.rs
src/options/colours.rs
src/options/config.rs
src/options/config/ignore_list.rs
src/options/config/layout.rs
tests/integration/util.rs

Separating the PRs to avoid too much change at once. This just moves files and imports around.
Closes: #

refactor: move some files around in prep for a future options refactor

---

.cirrus.yml

ci: add an explicit timeout for jobs on cirrus

---

.cirrus.yml
.github/workflows/build_releases.yml
.github/workflows/deployment.yml
.github/workflows/nightly.yml
scripts/cirrus/build.py

Note that `upload-artifact` v4 has breaking changes; this follows [this migration guide](https://github.com/actions/upload-artifact/blob/199a58f54fa418c391917374e9d11f5a5e618ae9/docs/MIGRATION.md) on how to move forward.
Closes: #
Mock nightly build: https://github.com/ClementTsang/bottom/actions/runs/7688896071

ci: update upload-artifact to v4.3.0 and download-artifact to v4.1.1

---

Cargo.lock
Cargo.toml

deps: update root dependencies (2024-02-14)

---

Cargo.lock

deps: update lock dependencies (2024-02-14)

---

docs/content/index.md

docs: some clarification

---

docs/content/troubleshooting.md

docs: fix numbering for Windows font troubleshooting guide

---

docs/content/troubleshooting.md

docs: actually fix numbering for Windows font troubleshooting guide

---

.github/workflows/post_release.yml

ci: update sha for auto winget PR action

---

Cargo.lock
Cargo.toml

Bump to sysinfo [0.30.6](https://github.com/GuillaumeGomez/sysinfo/blob/master/CHANGELOG.md#0306).
Closes: #

deps: bump sysinfo to 0.30.6

---

Cargo.lock
Cargo.toml

deps: bump root dependencies as of 2024-03-04

---

Cargo.lock
Cargo.toml

Changelog: https://github.com/GuillaumeGomez/sysinfo/blob/master/CHANGELOG.md#0307
Closes: #

deps: bump sysinfo to =0.30.7

---

.github/workflows/deployment.yml
.github/workflows/nightly.yml

Update resolves node deprecation warnings.
Closes: #

ci: bump action-gh-release to 2.0.1

---

docs/requirements.txt

docs: bump deps as of 2024-03-23

---

Cargo.lock
Cargo.toml

deps: bump dependencies as of 2024-03-23

---

src/data_collection.rs
src/data_collection/memory.rs
src/data_collection/memory/sysinfo.rs
src/data_collection/memory/windows.rs

Since it's a bit confusing, let's use sysinfo's swap calculation for the value we display as swap, and we'll add in a separate PR the committed memory as an extra field.
Closes: #1433 #1052 

change: use sysinfo's swap value for Windows

---

README.md

add install instructions to Exherbo Linux

docs: add install instructions to Exherbo Linux in README.md

---

Cargo.lock
Cargo.toml

deps: bump dependencies as of 2024-04-10, including sysinfo 0.30.10

---

README.md

docs: update some docs about install methods

---

Cargo.lock
Cargo.toml
src/utils/general.rs

deps: bump deps as of 2024-04-28

---

Cargo.lock

deps: bump lock deps as of 2024-04-28

---

src/canvas/components/tui_widget/time_chart/canvas.rs

other: comment out some dead code

---

.github/workflows/nightly.yml

ci: forgot to add if statement for nightly skip check

---

.github/workflows/build_releases.yml

Closes: #
Test run: https://github.com/ClementTsang/bottom/actions/runs/9009986402

ci: bump cargo-deb to 2.2.0

---

.github/workflows/audit.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml

Bump `rust-toolchain` and `rust-cache` in CI/workflows.
Closes: #

ci: bump rust-cache and rust-toolchain

---

Cargo.lock
Cargo.toml

deps: update deps as of 2024-05-26

---

CHANGELOG.md
Cargo.lock
Cargo.toml
build.rs
docs/content/configuration/command-line-options.md
docs/content/configuration/config-file/flags.md
sample_configs/default_config.toml
schema/v1.0/bottom.json
src/bin/main.rs
src/canvas/styling.rs
src/constants.rs
src/data_collection/temperature.rs
src/lib.rs
src/options.rs
src/options/args.rs
src/options/config.rs
src/options/config/layout.rs
src/utils/error.rs
src/widgets/process_table.rs
tests/integration/arg_tests.rs

refactor: use struct for args instead of builder interface

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Note that I'm not releasing 0.10.0 _yet_, will do so after a few more changes are done.
Closes: #

uptick: 0.10.0

---

Cargo.lock
Cargo.toml
schema/nightly/bottom.json
schema/v1.0/bottom.json
src/main.rs
src/options.rs
src/options/args.rs
src/options/colours.rs
src/options/config.rs
src/options/config/cpu.rs
src/options/config/disk.rs
src/options/config/ignore_list.rs
src/options/config/layout.rs
src/options/config/network.rs
src/options/config/process.rs
src/options/config/temperature.rs
src/widgets/process_table.rs

Uses [schemars](https://github.com/GREsau/schemars) to automatically generate them as needed. Ideally we do this with a build script but I don't see an easy way of doing it. We can probably at least automate/enforce doing this with CI though.
Closes: #

feat: add way to automatically generate new json schemas

---

Cargo.lock
Cargo.toml

Tested to build for 1.74 as well.
Closes: #

deps: bump root deps and lockfile as of 2024-06-19

---

Cargo.lock
Cargo.toml
src/utils/strings.rs

deps: bump root + lock deps as of 2024-06-27

---

Cargo.lock
Cargo.toml

deps: bump deps as of 2024-07-03

---

src/app/query.rs
src/data_collection/processes/unix/user_table.rs
src/options.rs
src/utils/error.rs
src/utils/logging.rs

The overall plan is to slowly clean up the `thiserror`/`BottomError` parts of the code, either consolidating on more code-area-specific error types or just using `anyhow`, where appropriate.
I may break this overall change into multiple PRs to keep the PR change size smaller. This first PR updates some low-hanging fruit in the logging errors and the process query errors.
Closes: #
_If relevant, ensure the …

refactor: error refactoring, part 1

---

src/app/layout_manager.rs
src/canvas.rs
src/canvas/dialogs/dd_dialog.rs
src/canvas/styling.rs
src/canvas/styling/colour_utils.rs
src/data_collection/processes/macos.rs
src/data_collection/temperature.rs
src/options.rs
src/options/args.rs
src/options/config/layout.rs
src/options/error.rs
src/utils/error.rs
tests/integration/arg_tests.rs

Switch out any config/arg/option-related errors for a new one. Also make user error messages related to this area more consistent.
Closes: #

refactor: out with arg/config error, and make user messages more consistent

---

src/app/process_killer.rs
src/canvas/styling.rs
src/utils/error.rs

refactor: convert more errors over

---

src/app/query.rs
src/canvas/widgets/process_table.rs

refactor: run clippy after updating to Rust 1.80

---

Cargo.toml
rust-toolchain.toml

other: include a rust-toolchain file

---

.github/workflows/audit.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
rust-toolchain.toml

other: remove toolchain, clean up CI

---

Cargo.lock
Cargo.toml
src/data_collection/nvidia.rs

deps: bump deps as of 2024-07-027

---

scripts/schema/requirements.txt
scripts/schema/validator.py

Bump `jsonschema-rs` version in validation script to fix `time` compilation issue with Rust bump, and also don't use `toml` in favour of the built-in `tomllib`, especially since it was unable to parse inline tables for whatever reason.
Closes: #

ci: update and fix schema validation script

---

README.md

Let's hope this doesn't lead to more issues where people try installing the wrong package though... sigh.
Closes: #

docs: add the binary name to the title again

---

docs/content/configuration/config-file/index.md
src/main.rs
src/options.rs

other: clarify config file creation logic/code

---

docs/content/configuration/config-file/data-filtering.md
sample_configs/default_config.toml
src/constants.rs
src/options/config.rs
src/options/config/cpu.rs
src/options/config/disk.rs
src/options/config/flags.rs
src/options/config/ignore_list.rs
src/options/config/layout.rs
src/options/config/network.rs
src/options/config/process.rs
src/options/config/style.rs
src/options/config/temperature.rs
tests/integration/valid_config_tests.rs
tests/valid_configs/filtering.toml

Updates some outdated docs on filtering, and adds some tests as well. In particular, this also adds a `cfg_attr` on tests to try and catch unknown fields; we'll be more lenient in prod builds though and allow them.
Closes: #

docs: update docs on filter

---

.github/workflows/post_release.yml

ci: bump winget-releaser

---

CHANGELOG.md

docs: update changelog for 0.10.0

---

src/options/args.rs

other: add test to catch issues with incorrect long arg names

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
desktop/bottom.desktop

uptick: 0.10.1

---

.cirrus.yml
.github/workflows/build_releases.yml
build.rs
scripts/cirrus/release.py

Ideally we add this behaviour back in.
Closes: #

ci: clean up cirrus CI

---

.github/workflows/build_releases.yml
.github/workflows/coverage.yml

Bump cargo-llvm-cov and cargo-deb.
Closes: #

ci: bump installed tools from cargo

---

README.md

Just updating the wording for some of the installation docs.
Closes: #

docs: update some of the installation docs

---

README.md

Switch solus and snap.
Closes: #

docs: fix alphabetical ordering of the linux install docs

---

.github/workflows/coverage.yml

ci: bump codecov action to v4.5.0

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
desktop/bottom.desktop

uptick: 0.10.2

---

README.md

Fixes .deb package links in examples.
Closes: #1549

docs: fix Debian package links

---

.github/workflows/ci.yml
CHANGELOG.md
src/constants.rs
src/options/config.rs
src/options/config/style/memory.rs

Follow-up to #1552 after I accidentally merged it.
Closes: #

other: add another test to validate default config

---

CHANGELOG.md
docs/README.md

docs: update doc about mkdocs, changelog, and versioning

---

README.md

Update README.md to add new Terra RPM repository instructions for installs on Fedora / CentOS / AlmaLinux / Rocky Linux

README.md: Add Terra RPM repo instructions

---

sample_configs/default_config.toml

As noted in #1571, the default sample config was outdated.
Closes: #

other: regenerate the sample default config to match 0.10.2

---

.github/workflows/audit.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/clear_workflow_cache.yml
.github/workflows/coverage.yml
.github/workflows/deployment.yml
.github/workflows/docs.yml
.github/workflows/nightly.yml
.github/workflows/post_release.yml
.github/workflows/test_docs.yml
.github/workflows/validate_schema.yml

Bumps:
- `actions/checkout`
- `actions-attest-build-provenance`
- `actions/download-artifact`
- `softprops/action-gh-release`
Closes: #

deps: bump some CI actions as of 2024-09-01

---

.github/workflows/ci.yml

ci: fix CI pass check conditions

---

Cargo.lock
Cargo.toml

I didn't touch the TUI ones (crossterm, ratatui) or sysinfo for now.
Closes: #

deps: bump a few root deps as of 2024-09-03

---

Cargo.lock
Cargo.toml

deps: bump a few root deps

---

CHANGELOG.md

docs: update changelog for #1596

---

.github/workflows/nightly.yml

ci: fix nightly job not skipping if no change

---

CHANGELOG.md
Cargo.lock
Cargo.toml

deps: bump starship-battery to 0.10.0

---

Cargo.lock
Cargo.toml

deps: bump lockfile deps

---

docs/requirements.txt

docs: bump docs requirements.txt

---

Cargo.lock
Cargo.toml

Bump a few root and lockfile deps.
Closes: #

deps: bump lock and some root deps

---

.github/ISSUE_TEMPLATE/bug_report.yml

github: update bug report template around filesystem type

---

src/widgets/process_table/proc_widget_column.rs

refactor: clean up some unused serde code

---

schema/nightly/bottom.json
src/options.rs
src/widgets/process_table/process_columns.rs

other: add missing process column comment/schema description

---

Cargo.toml
src/canvas/components/time_graph.rs
src/canvas/components/tui_widget/pipe_gauge.rs
src/canvas/components/tui_widget/time_chart/canvas.rs
src/data_collection/disks/unix/file_systems.rs

refactor: clean up some clippy lints from 1.83

---

.github/workflows/ci.yml
schema/nightly/bottom.json
schema/v0.10/bottom.json
schema/v0.9/bottom.json
src/bin/schema.rs
src/options/config.rs

Was using the incorrect titles/links in some schema files.
Closes: #

bug: fix incorrect versions in schemas

---

.github/workflows/validate_schema.yml
scripts/schema/requirements.txt
scripts/schema/validator.py

Bump `jsonschema-rs` to 0.26.1.
Closes: #

ci: update jsonschema to 0.26.1 for schema validation

---

CHANGELOG.md

docs: update changelog for #1642

---

CHANGELOG.md

docs: update changelog for #1641

---

Cargo.lock

deps: bump lockfile as of 2024-12-20

---

Cargo.lock
Cargo.toml

deps: bump dependencies

---

Cargo.lock
Cargo.toml
src/data_collection/disks/windows/bindings.rs

deps: bump Cargo.toml and Cargo.lock dependencies

---

src/app/data/store.rs
src/widgets/disk_table.rs

refactor: use cow for disk widget io read/write strings

---

README.md

docs: mention conda as an install option

---

src/app/data/store.rs

Ideally I also introduce a way to ensure basic mode widgets straight up cannot accidentally access ts data, but this works for now.
Closes: #

other: don't collect time series data in basic mode

---

docs/requirements.txt

docs: bump mkdocs-material to 9.6.5

---

CHANGELOG.md
src/options/args.rs

This PR allows both args like `--autohide-time` _and_ `--autohide_time` to work.
Closes: #

other: allow for hyphen versions of arguments to be used

---

README.md

Adds openSUSE Tumbleweed installation instructions to README.

README: Add openSUSE

---

README.md

Adds installation instructions for Alpine Linux to the README, including extra packages.

README: Add Alpine Linux

---

Cargo.lock
Cargo.toml

Tried this with cursor, worked alright after some nudging.
Closes: #

deps: bump root dependencies as of 2025-03-19

---

Cargo.lock
Cargo.toml

deps: bump lock deps as of 2025-03-19

---

docs/content/troubleshooting.md

docs: update font-related troubleshooting

---

README.md

I haven't updated this in too long. There's some thankin' that needs to go around.
Closes: #

docs: update thanks again

---

README.md
docs/content/index.md
docs/content/usage/autocomplete.md
docs/mkdocs.yml

docs: update README and autocomplete docs

---

src/app/data/store.rs

Turns out I already did this. Nice.
Closes: #

other: remove comment about skipping timeseries in basic

---

src/lib.rs

Disable mouse capture when `disable_click` is set in order to pass events through to the terminal.
Closes: https://github.com/ClementTsang/bottom/issues/1705

fix: Disable mouse capture when `disable_click` is set

---

src/app/data/store.rs
src/collection/processes/linux/process.rs
src/options/config/style/utils.rs

other: fix clippy warnings

---

src/canvas/widgets/network_graph.rs

bug: revert accidental time start change from another commit

---

CHANGELOG.md
docs/content/usage/widgets/process.md
src/app.rs

This was something I actually had code for but was broken...
Note that on macOS, it's `fn + delete`.
Closes: #

feature: support delete key to kill processes

---

Cargo.lock
Cargo.toml

deps: bump root deps as of 2025-04-20

---

Cargo.lock

deps: bump lock deps as of 2025-04-20

---

.github/workflows/ci.yml

Pin to https://github.com/cross-rs/cross/commit/df3309709a4a26b3dc3b1567239c3f38b9da0425
Closes: #

ci: update the cross version for the Android CI test

---

Cargo.lock
Cargo.toml

deps: bump root and lock deps as of 2025-04-29

---

src/app/data/store.rs
src/collection/processes.rs
src/lib.rs
src/widgets/process_table.rs
src/widgets/process_table/process_data.rs

Remove one clone for process grouping.
Closes: #
Tested by comparing to a stable version.

refactor: refactor some process grouping code

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

ci: bump rust-cache to 2.7.8

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml
src/collection.rs

Hopefully this fixes the issues with it failing?
Closes: #

ci: bump freebsd-vm to v1.2.0

---

README.md

Second thoughts on this, it's useful I guess.
Closes: #

docs: add back CI badge

---

.gitignore

other: add other samply files to gitignore

---

.github/workflows/validate_schema.yml
Cargo.lock
Cargo.toml
schema/nightly/bottom.json
src/bin/schema.rs

Mostly updated using `cargo upgrade --exclude sysinfo`, then bumping nvml-wrapper and schemars manually.
Main two bumps:
- nvml-wrapper: https://github.com/rust-nvml/nvml-wrapper/blob/main/CHANGELOG.md#0110-released-2025-03-28
- schemars: https://github.com/GREsau/schemars/blob/master/CHANGELOG.md#090---2025-05-26
Closes: #

deps: bump root deps as of 2025-06-01

---

0.10.0/404.html
0.10.0/assets/javascripts/bundle.bd41221c.min.js
0.10.1/404.html
0.10.1/assets/javascripts/bundle.bd41221c.min.js
0.10.2/404.html
0.10.2/assets/javascripts/bundle.fe8b6f2b.min.js
0.6.1/404.html
0.6.2/404.html
0.6.3/404.html
0.6.4/404.html
0.6.5/404.html
0.6.6/404.html
0.6.7/404.html
0.6.8/404.html
0.7.0/404.html
0.7.1/404.html
0.8.0/404.html
0.9.0/404.html
0.9.1/404.html
0.9.2/404.html
0.9.3/404.html
0.9.4/404.html
0.9.5/404.html
0.9.6/404.html
0.9.7/404.html
404.html
nightly/404.html
nightly/assets/javascripts/bundle.c8b220af.min.js

This fixes a few issues:
- Cloudflare Pages will endlessly redirect without a proper 404 page
- Styling is broken on 404 pages since they refer to absolute paths that don't exist
- JS is also broken on 404 pages for the same reason.
Closes: #

docs: add 404 for docs

---

src/canvas/dialogs/process_kill_dialog.rs

- Fix bug around Linux missing signals 32 and 33
- Add back multi-key timeouts
Closes: #

bug: fix some bugs around key bindings with new process kill dialog

---

Cargo.lock
Cargo.toml
src/app/data/time_series.rs
src/canvas/widgets/cpu_basic.rs
src/collection.rs
src/collection/cpu.rs
src/collection/cpu/sysinfo.rs
src/collection/processes/freebsd.rs
src/collection/processes/macos.rs
src/collection/processes/unix/process_ext.rs
src/collection/processes/windows.rs
src/collection/temperature/sysinfo.rs
src/widgets/cpu_graph.rs

Following https://github.com/GuillaumeGomez/sysinfo/blob/master/migration_guide.md.
Closes: #

deps: bump sysinfo to 0.35

---

Cargo.lock
Cargo.toml

deps: bump dependencies as of 2025-06-09

---

.github/workflows/build_releases.yml

_A description of the change, what it does, and why it was made. If relevant (such as any change that modifies the UI), 
**please provide screenshots** of the changes:_
The 20.04 runner image is deprecated, see https://github.com/actions/runner-images/issues/11101
If a 20.04-based build is needed, I can look to provide one via cirrus.
Closes: #
Test CI run: https://github.com/ClementTsang/bottom/actions/runs/15596215804

ci: update ubuntu version for builds to 22.04

---

README.md

docs: fix CI shield

---

README.md

docs: actually fix actions shield

---

Cargo.lock
Cargo.toml

deps: bump root and lock deps

---

src/canvas/components/time_graph/base/time_chart/points.rs
src/canvas/widgets/network_graph.rs

refactor: fix clippy warnings for 1.88.0

---

CHANGELOG.md
src/collection/processes.rs
src/collection/processes/linux/mod.rs
src/collection/processes/linux/process.rs
src/collection/processes/unix/process_ext.rs
src/collection/processes/windows.rs
src/options/args.rs
src/options/config/process.rs
src/widgets/process_table.rs
src/widgets/process_table/process_columns.rs
src/widgets/process_table/process_data.rs
src/widgets/process_table/query.rs
tests/integration/valid_config_tests.rs
tests/valid_configs/proc_columns.toml

This adds a virtual memory column.
Closes: #

feature: support virtual memory column for processes

---

CHANGELOG.md

docs: forgot some entries in my changelog

---

.github/ISSUE_TEMPLATE/packaging.yml
.github/workflows/post_release.yml

Seems like it's not necessary for me to do this anymore?
Closes: #

ci: remove winget job

---

Cargo.lock
Cargo.toml

deps: bump deps as of 2025-08-14

---

Cargo.lock
Cargo.toml

other: bump btm's cargo version to 0.11.1

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
README.md

uptick: 0.11.1

---

Cargo.lock

other: fix lockfile

---

Cargo.lock
Cargo.toml

deps: bump deps as of 2025-08-19

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml
Cargo.toml

Do basic checks in CI + build binaries for Windows ARM.
Closes: #1795
https://github.com/ClementTsang/bottom/actions/runs/17143933217

ci: build and check Windows ARM

---

sample_configs/default_config.toml

Updates the default config in the repo.
Closes: #

docs: update default config

---

Cargo.lock
Cargo.toml
src/app.rs
src/canvas/dialogs/process_kill_dialog.rs
src/widgets/process_table.rs
src/widgets/process_table/process_data.rs
tests/integration/invalid_config_tests.rs

deps: bump deps and lockfile

---

CHANGELOG.md

docs: update changelog with #1817

---

Cargo.lock
Cargo.toml

deps: bump deps as of 2025-09-23

---

.github/workflows/build_releases.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml

Mostly what the title says, this should hopefully not break anything.
Closes: #
See CI + https://github.com/ClementTsang/bottom/actions/runs/17995915085

 ci: bump cargo-action to 0.0.7, rust-cache to 2.8.1, and rust-toolchain to e97e2d8

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/build_releases.yml
.github/workflows/ci.yml

ci: update freebsd-vm to v1.2.4
